tektoncd/plumbing

.github/issue-template.md, .github/pull_request_template.md, CONTRIBUTING.md, DEVELOPMENT.md, OWNERS, README.md, boskos/boskos-config.yaml, boskos/boskos.yaml, boskos/storage-class.yaml, code-of-conduct.md, gubernator/config.yaml, prow/config.yaml, prow/ingress.yaml, prow/plugins.yaml
This configuration was previously at https://github.com/tektoncd/pipeline/tree/master/infra
but now we want to use this same infrastructure for multiple `tektoncd`
projects.
Permissions for accessing this infrastructure are given to Tekton
governing board members (see
https://github.com/tektoncd/community/pull/15).
This also brings the repo up to its requirements: https://github.com/tektoncd/community/blob/master/process.md#project-requirements :tada:
=> Move test infrastructure to this repo 🚚

README.md, prow/config.yaml
Before this change only `community` and `pipeline` had automatic tide
merging via Prow. Now all of the existing repos will have it.
Partially addresses #3
(Also simplified the config, looking at the knative config as an example
https://github.com/knative/test-infra/blob/691caf51f2bb9ef86888772a8cc5d7952687b7c6/ci/prow/config.yaml#L51-L65
it looks like we can use the same stanza for multiple repos)
p.s. I have already applied this manually :innocent: 
review them:
=> Add tide to all tektoncd repos 🌊

prow/config.yaml
This commit adds unit, build and integration tests to the catalog repo.
The pending PR: https://github.com/tektoncd/catalog/pull/23 adds the boilerplate
required to run these tests.
review them:
=> Add tests for the catalog repo.

prow/config.yaml
I missed the "tektoncd/catalog" section in yaml before. This
correctly moves the catalog tests to run on the right repo.
=> Fix the catalog tests.

dummy.go
It seems go modules (and most likely dep too) need a go file in any
parent package of a package to be import.
cc @abayer 
review them:
=> Add dummy go file to make dep and go modules happy

scripts/presubmit-tests.sh
This should allow user of these scripts to do extrat setup steps they
need for their tests to run later on. On example is, on
tektoncd/dashboard, to get `node` and `npm`.
The end goal is to create specific image, with the recipes hosted
here, for those cases 😉.
/cc @abayer @bobcatfish 
review them:
=> Add an extra_initialization step before running tests

prow/config.yaml
The `context` field default to the job name. As in our configuration,
all the `context` are the exact same as the name, they are not
required 😉
/cc @abayer @bobcatfish 
review them:
=> Remove context from presubmit configuration

boskos/boskos-config.yaml, boskos/boskos.yaml
Somehow I never committed this the first time I setup boskos.
This picks up a new set of images and adds a new test project as well.
=> Add the boskos configuration and update images.

prow/config.yaml
This is the first take on having postsubmits jobs on tektoncd, to
publish nightly builds. We start with the simplest, aka dashboard
/cc @dlorenc 
Does the job definition make sense ?
review them:
=> Add a postsubmits to dashboard to push nightly images

scripts/library.sh
Reverts repo path from tektoncd to knative. This repo does not exist in tekton, but in https://github.com/knative/test-infra
review them:
=> Revert dep-collector repository path to knative.

scripts/library.sh
This repo exists in knative/test-infra. This repo does not exist in
tekton. We missed one in the previous fix :bowing_man: sorrryy !
cc @wlynch @bobcatfish 
review them:
=> Additional revert dep-collector repository path to knative.

README.md, boskos/boskos-config.yaml
We have been seeing errors in our automated end to end tests which
indicate that boskos (which use use to manage GCP projects for our end
to end tests - see #34 about maybe not using it anymore) had no projects
left. So this PR doubles the number of boskos projects.
Note that I have already manually applied this change to the boskos
cluster.
As you can see in https://github.com/tektoncd/community/pull/25 I
decided to not give everyone access to all 7 new projects b/c managing
fine grained access across 14 boskos projects is no fun at all 😩 but I
can add them anyway if folks want them.
Fixes #29
review them:
for more …
=> Double the number of boskos projects 📈

prow/config.yaml
The new image (at the tag latest) causes issues for our setup. It looks
like https://github.com/knative/test-infra/pull/852 hardcodes some default
values.
=> Rollback the coverage image to the last tag.

prow/config.yaml
I want to be able to see status and logs for this job, and currently
it doesn't show up in prow.tekton.dev, so moving it to postsubmit.
review them:
=> Moveci-tekton-pipeline-nightly-release to postsubmit

prow/config.yaml
The cli is built for several targets (linux, windows, darwin) and
architecture (x86, x86_64, arm, …). Those takes time, so adding a job
for those to run in parallel of build.
It's already deployed.
review them:
=> Add a build-cross-tests job to the cli 🏗

README.md, boskos/README.md, gcp.md, gubernator/README.md, prow/README.md, prow/config.yaml, prow/helloscott.yaml, prow/prow.yaml
A step toward https://github.com/tektoncd/pipeline/issues/922 !
This commit adds configuration and supporting docs to get Prow to execute a simple Pipeline on every pull request to the plumbing repo.
I am also working on docs in the Prow repo (for https://github.com/kubernetes/test-infra/issues/13874 and https://github.com/tektoncd/pipeline/issues/1187) to explain how one could put this all together from scratch.
One important caveat is that we were previously using the Tekton installation in this cluster to do manual releases, and we were keeping our release configuration up to date with the latest version of Tekton Pipelines. Because of https://github.com/kubernetes/test-infra/issues/13948 the newest version we can use with Prow is v0.3.1 so we need to keep our release configs in sync …
=> Add a "hello world" Pipeline to be executed via Prow 🌏

prow/config.yaml
I think I forgot to commit this, thus it got reseted when updating the
prow configuration from elsewhere.
/cc @abayer @bobcatfish
review them:
=> Put securityContext on the right place for tektoncd/pipeline postsubmit

prow/README.md, prow/config.yaml
Unfortunately this PR is a mix of 2 different changes b/c the changes all had to go into the same file and I had to fix them at the same time to apply them. They are in 2 separate commits tho!
Add nightly Pipelines release crescent_moon
This is the configuration to run the Pipeline + Tasks being added in
tektoncd/pipeline#1274 every night at midnight
PDT.
I've successfully run this by setting the cron to every 5 minutes. This
configuration is already applied to the repo.
Status can be seen at https://prow.tekton.dev/?type=periodic.
Part of tektoncd/pipeline#860
Trying to get upgrade test working construction
It looked like the indentation was off, and also some of the environment
variables (e.g. $PULL_REF) provided to presubmit jobs aren't provided
to presubmit jobs. I tried to copy …
=> Add nightly Pipeline + try to fix some upgrade test stuff

prow/plugins.yaml
The implicit self approve means that every PR submitted by an owner
may be inadvertently approved and merged by any member of the
tektoncd org with an /lgtm, where it should generally speaking be
reviewed and approved first by another member of the OWNERS team.
I think it's best to err on the safe side :)
review them:
=> Remove implicit self approve

scripts/library.sh
The function start_latest_tekton_serving is not used and it's not
doing anything useful either. It looks like it came from
's/knative/tekton/g'.
review them:
=> Remove unused start_latest_tekton_serving

prow/config.yaml
`ci-tekton-pipeline-upgrade-tests` should not be decorated (see
https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md
for what decorate does).
/cc @abayer @afrittoli @bobcatfish 
Already deployed, the job is running :tada: (it might fail, but if it fails, the fix would be on on tektoncd/pipeline) (logs [here](https://prow.tekton.dev/log?job=ci-tekton-pipeline-upgrade-tests&id=1180049492594921472))
review them:
=> Fix tektoncd/pipeline upgrade tests periodics job : no decorate 🍂

pipelinerun-logs/Dockerfile, pipelinerun-logs/deployment.yaml
Prior to this commit working on pipelinerun-logs required pulling the
code down locally and then manually constructing a container from it.
This commit adds a Dockerfile and example kubernetes deployment for
running pipelinerun-logs.
=> Add a dockerfile and deployment description for pipelinerun-logs

prow/config.yaml, prow/images/tekton/pipeline-test-runner-image.yaml, prow/images/tekton/resources.yaml, prow/images/tekton/task-kaniko.yaml, prow/images/test-runner/Dockerfile
This does a few things:
- Fix the current image build (`make images` fails on `liche`)
- Add tkn to the image
- Add a prow job using `tektoncd-pipeline` to build it nightly − that way, it's gonna be quicker to see that the build fails *and* we won't need to build the image manually when we need to update it on the cluster.
I decided to go with prow but we may want to use the dogfooding cluster for this instead (and thus not be stuck in 0.3.x)
This is linked to https://github.com/tektoncd/pipeline/pull/1414
review them:
=> Add tkn to test runner

tekton/prerelease_checks.yaml
Add a tasks that verifies if a release already exists. This is
useful before generating a release, to make sure we do not
overwrite an existing release. Checks are:
- tag already exists in git
- release file already exists in the bucket
- release already defined in GitHub
Closes bug tektoncd/pipeline#983
review them:
=> Add a task for preprelease checks

prow/images/test-runner/Dockerfile
Also had to pin mdl to 0.5.0 the new version does
not work with ruby < 2.4
Fixes #71 
review them:
=> Update test-runner image to use go 1.13

pipelinerun-logs/README.md, pipelinerun-logs/cmd/http/main.go, pipelinerun-logs/cmd/http/server.go, pipelinerun-logs/config/deployment.yaml, pipelinerun-logs/go.mod
This PR updates the import paths and deployment for the pipelinerun-logs
app so that it can be built and deployed simply using `ko`.
In doing this I realized that I'd left imports pointing to my personal github so those have been fixed with this commit as well.
review them:
=> Deploy pipelinerun-logs with ko

prow/config.yaml
- go 1.13
- `tkn` is present in the image
Uses latest image built by the nightly job (fixed here : https://github.com/tektoncd/plumbing/pull/92)
review them:
- [.] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
=> Bump test-runner image to latest built 🏗

pipelinerun-logs/cmd/http/query.go, pipelinerun-logs/cmd/http/query_test.go, pipelinerun-logs/cmd/http/server.go, pipelinerun-logs/cmd/http/server_test.go
We'd like to be able to annotate our dogfooding pipelineruns with uuid
Build IDs so that we can look them up using the pipelinerun log viewer.
At the moment the viewer only accepts "prow-format" build IDs which are
just strings of ints. This commit updates the server to also accept
UUIDs.
=> Accept UUID as well as Prow-format Build IDs

README.md, addpermissions.py
In https://github.com/tektoncd/pipeline/issues/1500 @vdemeester wanted
to be able to access our boskos projects to try to debug it but I had
been lazy and not given everyone access b/c there are so many of them. I
didn't want to do it (lazy) but then I realized that a script would make
it easy! So I wrote this script; it doesn't have any tests or automation
yet but eventually we could execute it as part of a Tekton pipeline and
use it to make sure permissions are always what we expect.
I've run this for @vdemeester @afrittoli @abayer @kimsterv 
review them:
=> Add script for setting up GCP project permissions 🔒

prow/config.yaml, tekton/resources/pipeline-nightly-build-trigger.yaml
See tektoncd/pipeline#1503.
/cc @afrittoli @ImJasonH
review them:
=> As `cmd/{bash,nop,gsutil}` image are gone, removing them from plumbing ⛏

pipelinerun-logs/README.md, pipelinerun-logs/config/deployment.yaml
The pipelinerun-logs app needs access to stackdriver APIs in order to show log entries for pipelineruns. GCP supports a feature called workload identities that enables a k8s serviceaccount to refer to an IAM serviceaccount and use its credentials when accessing google cloud apis. This means we don't need to download JSON keys and inject them as secrets for apps running in the cluster to utilize cloud apis.
I've created a service account in GCP that has access to stackdriver, I've created a corollary service account in k8s (in the default namespace) that references the GCP service account, and I've created a node pool that has the workload identity metadata service running. The pipelinerun-logs deployment has been updated to schedule its pods on the new nodes and after manual testing the …
=> Configure stackdriver access for pipelinerun-logs app

prow/images/test-runner/Dockerfile, scripts/presubmit-tests.sh
- Add yamllint binary to the test-runner image
- Add an yamllint check to `build_test`, that can be disabled using
the environment variable `DISABLE_YAML_LINTING`
This is related to tektoncd/catalog#101 but should be useful for more repositories :wink: 
/cc @chmouel @afrittoli @abayer @bobcatfish 
I'll update the test-runner image once the nightly builds it and bump `tektoncd/plumbing` on the tektoncd repositories :wink: 
review them:
=> Add yamllint to the test-runner image and scripts 📦

.yamllint, boskos/boskos-config.yaml, boskos/boskos.yaml, gubernator/config.yaml, label_sync/labels.yaml, prow/ingress.yaml, tekton/config/nightly-image-build-cron-base/trigger-image-build.yaml, tekton/config/nightly-release-cron-base/trigger-with-uuid.yaml, tekton/resources/install_tekton_release.yaml
Next update of plumbing will enable `yamllint` check, so this make
sure we have linted yaml before 👼
Related to tektoncd/catalog#101 (not closing it yet as the CI is not hooked up, needs tektoncd/plumbing#111 and a prow config update :stuck_out_tongue: 
review them:
=> Linting yamls with yamllint 🏷

pipelinerun-logs/config/deployment.yaml
I tried deploying the pipelinerun logs app with the latest version
of the deployment, but it fails unless quotes are used for "true".
review them:
=> Add quotes to fix the pipelinerun logs app deployment

tekton/config/nightly-image-build-cron-base/trigger-image-build.yaml, tekton/resources/image-build-trigger.yaml
Add the image name to the taskrun name as well as in a labels on
the taskrun. Embed the resources in the taskrun to reduce waste.
=> Make image build runs more discoverable

tekton/images/test-runner/Dockerfile
Install golangci-lint from a pinned version
Let's install golangci-lint from a stable pinned version instead of master which
can brings weird CI breakage.
Closes #125
review them:
- [?] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=>  Install a pinned stable version of golangci-lint  instead of master

tekton/config/hub-image-nightly-build-cron/cronjob.yaml, tekton/config/hub-image-nightly-build-cron/kustomization.yaml, tekton/images/hub/Dockerfile
Hub is a CLI interface to GitHub. This image will be used to run release automation scripts.
Add a cronjob that builds the image nightly to tag "latest".
=> Add a image with `hub` and a nightly build job

prow/config.yaml
This should allow us to update the test-runner without having to bump
the prow config each time.
Related to https://github.com/tektoncd/plumbing/pull/130#discussion_r351765456 and https://github.com/tektoncd/plumbing/pull/129
/cc @chmouel @afrittoli @wlynch 
review them:
=> Use tag latest for test-runner instead of a digest 😅

tekton/images/tkn/Dockerfile
Update tektoncd cli container image to pull out from the latest tektoncd-cli release (0.5.1)
=> Use tektoncd CLI 0.5.1

scripts/presubmit-tests.sh
For large PRs, presubmit tests break if we store the changed files in a
global variable. This changes the behavior to store the filepaths on
disk to avoid this issue.
Example in production: https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/1607/pull-tekton-pipeline-build-tests/1202649284323840002/
Simple shell reproduction:
```
$ FILES=$(find $GOPATH/src/github.com/tektoncd/pipeline -type f)
$ ls
<works fine>
$ export FILES
$ ls
bash: /usr/bin/ls: Argument list too long
```
review them:
=> Write changed files to file instead of storing in a global var.

tekton/config/ko-gcloud-image-nightly-build-cron/cronjob.yaml, tekton/config/ko-gcloud-image-nightly-build-cron/kustomization.yaml, tekton/images/ko-gcloud/Dockerfile
The release job uses gcloud for auth in the ko step, so we need an image
with both ko and gcloud. This is inspired on the image from the pipeline
repo, and it's built nightly to a dedicated tag of the ko repo:
ko:gcloud-latest
review them:
=> Add a ko-gcloud image

prow/clusterissuer.yaml, prow/ingress.yaml
This is what was required (with some crazy, not useful hack on my part
😹) to fix https on prow.tekton.dev
As follow-up, we need a little bit more docs/link to help debug potential problems :angel: 
review them:
=> Fix ingress annotation and cert-manager configuration 👼

prow/config.yaml
This will (hopefully!) disable the markdown link checker that is currently blocking a couple PRs over in the Pipelines repo.
:crossed_fingers: 
review them:
=> Hopefully disable the markdown link checker

tekton/cd/pipeline/base/kustomization.yaml, tekton/cd/pipeline/overlays/dogfooding/config-artifact-bucket.yaml, tekton/cd/pipeline/overlays/dogfooding/kustomization.yaml, tekton/resources/release/install_tekton_release.yaml
Add support for deploying a release of a Tekton service using
overlays for kustomize. Add an overlay for pipeline that set
up the artifact bucket for the dogfooding environment.
review them:
=> Deploy Tekton services from release with overlay

tekton/images/tkn/Dockerfile
This was updated for [test-runner](https://github.com/tektoncd/plumbing/blob/847dcf196de9555b15ff6ebb397d11513aa920d2/tekton/images/test-runner/Dockerfile#L51), but now updating version to v0.6.0 for tkn image.
=> Update Version to 0.6.0 for tkn Image

prow/config.yaml
This made `hook` and `plank` fail and crashloop…
/cc @sbwsg @afrittoli @bobcatfish 
review them:
=> An EnvVar needs to be a string otherwise prow fails 😟

label_sync/labels.yaml
I was build cop today and I noticed in our "build cop runbook" we
talked about the purposes of a few labels, but definitely not all of
them. Since this is the authoritative source on what labels we have, I
think it makes sense to make this our documentation as well, and also to
clean out labels we don't need (many are copied from knative which
copied from kubernetes)
Removed some labels:
- triage/duplicate: Can use "Duplicate of" instead
(https://help.github.com/en/github/managing-your-work-on-github/about-duplicate-issues-and-pull-requests)
- triage/needs-information: Could use zenhub "waiting for response"
and/or "kind/question" instead
- triage/not-reproducible, triage/support, triage/unresolved - not
really sure what these would mean for us
- kind/api-change, "api-review": Can use …
=> Make labels a bit easier for build cops 👮‍♀️

tekton/README.md, tekton/cd/README.md, tekton/cd/triggers/base/kustomization.yaml, tekton/cd/triggers/overlays/dogfooding/kustomization.yaml, tekton/resources/images/image-build-trigger.yaml, tekton/resources/mario-github-comment.yaml, tekton/resources/mario-image-build-trigger.yaml, tekton/resources/nightly-release/base/eventlistener.yaml, tekton/resources/org-permissions/peribolos-trigger.yaml, tekton/resources/release/nightly-release-logs-trigger.yaml
Migrate resources to triggers v0.2.0:
- eventlistener.binding -> bindings
- eventlistener.interceptor -> interceptors
- gjson to JSONPath in bindings
- select an element from an array
Fixes #183
=> Migrate resources to work with triggers v0.2.0

boskos/boskos.yaml
Update the container image used by Boskos components in an attempt
to solve https://github.com/tektoncd/plumbing/issues/186.
=> Update the boskos image

tekton/resources/mario-bot/mario-image-build-trigger.yaml, tekton/resources/nightly-release/base/kustomizeconfig/eventlistener.yaml, tekton/resources/nightly-release/base/serviceaccount.yaml
Change the kustomize config for event listener to support binding*s*
Add a role to the service account used to nightly releases.
Make sure service accounts for release and Mario bot can get/list/watch configmaps.
review them:
=> Fix the eventlistener kustomize config

tekton/resources/nightly-release/base/template.yaml
Fixes #183
The pipeline resource for the release bucker didn't derefernce the
projectName parameter correctly, so fixing that.
review them:
=> Fix the trigger template for nightly releases

boskos/boskos.yaml
Using the same boskos version the prow folks are using, e.g.,
https://github.com/kubernetes/test-infra/blob/b2471685eed6a7d063d7e1e19032282bb33679db/prow/cluster/boskos.yaml#L65
which they bumped to in the context of dealing with the same issue we
ran into on Friday (#186)
(Already applied manually to the cluster)
review them:
=> Use the latest boskos ✨

scripts/presubmit-tests.sh
If you specify a YAML_LINT_CONFIG variable and have a yamllint config file in
there the projects would be able to add some project specific rules.
Some examples of yamllintrc files : 
https://github.com/adrienverge/yamllint#features
review them:
=> Allow project to specify a yamllint config

tekton/resources/release/README.md, tekton/resources/release/github_release.yaml, tekton/resources/release/save-release-logs.yaml
- Fix release documentation
- Add missing `\` to the command calls
- Add tekton-logs service account to the save-logs task
- Add "namespaces" get/list to the tekton-logs-reader role
- Remove prepending `v` to the release number :pray: 
review them:
=> Few releases documentation and tasks fixes

tekton/resources/release/github_release.yaml
Add the new `release.notags.yaml` release file that only contains
digests in the release that we create using `hub`.
Related to tektoncd/plumbing#1829
/hold
review them:
=> Add release.notags.yaml file to the release page 💫

tekton/images/ko/Dockerfile
Bump the version for dashboard release pipeline changes
For background: https://github.com/tektoncd/dashboard/issues/960 and https://github.com/tektoncd/dashboard/issues/950
Bump it 🎉 
review them:
Tested this using `docker run -it adamroberts/custom-ko-gcloud:latest sh` (which is my own image but with 3.5.4) and running 
```
kustomize build overlays/dev | ko resolve --preserve-import-paths -f - > /workspace/output/bucket/$(inputs.params.bucketName)/tekton-dashboard-release.yaml
kustomize build overlays/dev-locked-down | ko resolve --preserve-import-paths -f - > …
```
=> Upgrade to Kustomize 3.5.4

tekton/resources/mario-bot/mario-image-build-trigger.yaml
Some of mario resources do not have "mario" in the name.
If they are applied to the wrong namespace they may override
other resources.
review them:
=> Prepend "mario" to mario-bot resources

tekton/cd/dashboard/base/kustomization.yaml, tekton/cd/dashboard/base/release.yaml, tekton/cd/dashboard/overlays/dogfooding/ingress.yaml, tekton/cd/dashboard/overlays/dogfooding/kustomization.yaml, tekton/cd/dashboard/overlays/dogfooding/tekton-dashboard-service.yaml, tekton/certificates/clusterissuer.yaml
Add an overlay for the dashboard in the dogfooding cluster.
The overlay includes:
- an ingress resource
- setting the service to "nodePort", which is required for
the ingress to work with GKE.
This patch includes also a ClusterIssuer that can be used for
any ingress in the cluster. Using the cluster issuer requires
cert-manager to be installed first:
https://cert-manager.io/docs/installation/kubernetes/#installing-with-regular-manifests
GKE load balancer setup the health check to point to the
readiness probe defined in the pods associated to the service.
The probe is expected to return 200, while in the latest
dashboard it returns 204 No Content. This patch fixes the issue:
https://github.com/tektoncd/dashboard/pull/1017
Partially fixes #182
These are the criteria that every PR should …
=> Deployment overlay for the dashboard in dogfooding

prow/config.yaml
In PR https://github.com/tektoncd/dashboard/pull/1030 we saw an error
reported by Prow that the "tekton-dashboard-publish-images" job
had failed. This job isn't intended to run on PRs. Christie pointed
out that Prow will run a postsubmit job against every branch unless
a branch list is specified for it. This info is documented for Prow
here:
https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#how-to-configure-new-jobs
This PR adds a branch list to limit the postsubmit job to only run
against master.
review them:
=> Limit the branches that dashboard's publish images job runs against

tekton/images/test-runner/Dockerfile
/cc @afrittoli @chmouel 
review them:
=> Bump golangci-lint to 1.23.3 (from 1.21) 🚌

boskos/boskos.yaml
Boskos used to register its CRDs from code, however now it
expectes the CRDs to be registered via a manifest, like in
https://github.com/kubernetes/test-infra/blob/76626ab4c4559f768e6519a5c5438c4b8c37b40f/prow/cluster/boskos.yaml#L15-L79
Adding the CRDs to Tekton's Boskos deployment.
review them:
=> Add CRDs to the boskos deployment

boskos/boskos.yaml
Added a service for the metrics endpoint, so that it becomes easier to check the status of boskos resources. The service is of type NodePort, so that it can work with an ingress on top if we decide to expose this endpoint publicly.
review them:
=> Add a service for the metrics endpoint

scripts/presubmit-tests.sh
If we find a `go.mod` and there is a root `vendor` folder, we define
`-mod=vendor` in order to use the vendor code instead of downloading
the dependencies all the time.
/cc @chmouel 
review them:
=> Add a default GOFLAGS for specific cases 🌔

addpermissions.py
@afrittoli has been debugging a lot of boskos problems recently that
have resulted in and/or been caused by GCP compute disks not being
cleaned up. Adding the compute storage admin capability to all the folks
either in the build cop rotation or on the governing board will let
folks delete these disks if needed.
Also made it so you can run this for a bunch of users at once instead of
repeatedly for each user.
review them:
=> Add compute storage privileges for boskos clusters 💿

tekton/resources/cd/label-sync-cd.yaml, tekton/resources/kustomization.yaml
The taskrun name is copy pasted from the prow config deploy.
Fixes: #251 
review them:
=> Fix the taskrun name for label sync

buildbot/cmd/generate-rotation-csv/README.md, buildbot/cmd/generate-rotation-csv/main.go, buildbot/cmd/generate-rotation-csv/main_test.go
This commit adds a small go program to generate the rotation csv that
the buildbot uses to notify buildcops.
Example usage:
```bash
go run ./main.go -names jules,ronda,gavin,paula,don,carol
```
review them:
=> Add a tool to generate rotation csv

tekton/resources/cd/label-sync-cd.yaml
The job definition wants `labels.yaml` and not `config.yaml`.
review them:
=> Fix the configmap key for label_sync job 🕹

buildbot/cmd/generate-rotation-csv/README.md, buildbot/cmd/generate-rotation-csv/main.go, buildbot/cmd/generate-rotation-csv/main_test.go, buildbot/rotation-overrides.csv
People on rotation often need others to cover a shift, swap
with them or cancel a rotation over a holiday period.
This PR adds an -overrides flag to the rotation generator tool that
reads a CSV file describing these kinds of overrides.
I've re-generated the buildbot's overrides.csv using this new flag to
see if it would produce the same output, and it does.
Regenerated rotation using following command:
```bash
go run ./buildbot/cmd/generate-rotation-csv/main.go \
-start-date 2020-03-09 \
-days 297 \
-names wlynch,vdemeest,andrea.frittoli,dibyo,christiewilson,sbws \
-overrides ./buildbot/rotation-overrides.csv
```
review them:
_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBU …
=> Add support to rotation generator for swaps and holidays

label_sync/labels.yaml
This label is meant to be used, at least by the CLI WG, to be able to
mark issues or PR to be discussed during the WG calls. With the proper
automation, it will appear on the WG Project we use to track those
discussion.
/cc @afrittoli @danielhelfand @sbwsg 
review them:
=> Adding a triage/wg-discuss 😅

label_sync/labels.yaml, prow/plugins.yaml
The prow plugin *and* the label. I tend to agree with the comment on
the label, so removing it.
/cc @afrittoli @bobcatfish 
review them:
=> Disable shrug ¯\\\_(ツ)_/¯

buildbot/README.md, buildbot/cmd/buildbot/kodata/rotation.csv, buildbot/cmd/buildbot/main.go, buildbot/cmd/buildbot/rotation.go, buildbot/cmd/buildbot/rotation_test.go, buildbot/cmd/buildbot/testdata/rotation-invalid.csv, buildbot/cmd/buildbot/testdata/rotation.csv
Build cop bot will now load the csv file from github every time it checks it.
Previously the buildbot binary was being built with the rotation csv as
part of the binary itself, which meant that updating the rotation would
require rebuilding and redeploying the image.
This change makes it so that the rotation can be updating without
needing to update the image - the downside is that the running binary is
now coupled to the repo but I think it's worth it!
Follow up TODOS:
* run unit tests on every PR https://github.com/tektoncd/plumbing/issues/283
* deploy build bot binary automatically https://github.com/tektoncd/plumbing/issues/282
review them: …
=> Update build bot to load rotation dynamically 🚚

buildbot/cmd/buildbot/main.go, buildbot/cmd/buildbot/rotation.go, buildbot/cmd/buildbot/rotation_test.go
Addressing feedback in #281
Decouple the file / url functionality from the logic to create a new
Rotation object. Also moving the file based logic into the tests since
it is only used by the tests. (Thanks for the feedback @vdemeester!)
Use standard log lib instead of pulling in a kubernetes dependency 😅 
review them:
=> Respond to PR feedback

robocat/cadmin/200-rbac.yaml, tekton/cd/pipeline/overlays/robocat/config-artifact-bucket.yaml, tekton/cd/pipeline/overlays/robocat/kustomization.yaml, tekton/cd/pipeline/overlays/robocat/pre/100-inject-minio-creds.sh, tekton/cd/pipeline/overlays/robocat/pre/tekton-storage-secret.yaml.tpl, tekton/cronjobs/README.md, tekton/cronjobs/configmap-cd-cron-base/trigger-resource-cd.yaml, tekton/cronjobs/folder-cd-cron-base/trigger-resource-cd.yaml, tekton/cronjobs/helm-cd-cron-base/trigger-resource-cd.yaml, tekton/cronjobs/robocat-pipeline-deploy-latest-cron/README.md, tekton/cronjobs/robocat-pipeline-deploy-latest-cron/cronjob.yaml, tekton/cronjobs/robocat-pipeline-deploy-latest-cron/kustomization.yaml, tekton/cronjobs/tekton-service-cd-cron-base/README.md, tekton/cronjobs/tekton-service-cd-cron-base/kustomization.yaml, tekton/cronjobs/tekton-service-cd-cron-base/trigger-resource-cd.yaml, tekton/resources/cd/bindings.yaml, tekton/resources/cd/configmap-template.yaml, tekton/resources/cd/eventlistener.yaml, tekton/resources/cd/tekton-template.yaml, tekton/resources/kustomization.yaml, tekton/resources/release/README.md, tekton/resources/release/install_tekton_release.yaml
Start CD of pipeline in the robocat cluster. To do setup some preconditions:
- extend the deployment pipeline to accept version "latest"
- extend the configmap deployment pipeline to create a configmap on first run
- add a pipeline overlay for the robocat cluster
- extend the deployment pipeline to accept pre-deploy script, so we can deploy secrets
- add a service in the tektoncd trigger to run the deployment pipeline
- add a cronjob to deploy pipeline nightly from latest to robocat
Work on #224 
Depends on https://github.com/tektoncd/plumbing/pull/270 and https://github.com/tektoncd/plumbing/pull/271
review them: …
=> Nightly deploy of latest pipeline to robocat cluster

tekton/resources/release/prerelease_checks.yaml
Previously the prerelease check would fail if any tag in the git repo _contained_ the version tag supplied to the Task.  For example, `v0.11.0` would be disallowed if there was an existing tag of `v0.11.0-rc1`.
This PR changes the prerelease check so that the tag endings must match exactly.  `v0.11.0` will be allowed even if tag `v0.11.0-rc1` exists.
review them:
=> Prerelease Check: Only fail if version tag endings are exact match

prow/config.yaml
This PR adds a presubmit job for linting helm charts in the experimental repository.
This is related to https://github.com/tektoncd/experimental/pull/494
=> Add pull-tekton-experimental-helm-lint

prow/config.yaml
Use kubernetes agent instead of pipeline.
This is related to tektoncd/experimental#494
=> Improve tekton-experimental-helm-lint prow job

tekton/images/test-runner/Dockerfile, tekton/images/test-runner/entrypoint.sh, tekton/images/test-runner/runner.sh
It doesn't depend on k8s.io/test-infra anymore. This is an "almost"
naive import of the `kubeins-e2e` and `bootstrap` images from
k8s.io/test-infra.
Will need to be cleaned up as we go.
/cc @afrittoli @bobcatfish 
review them:
=> test-runner: self-contained dockerfile

prow/config.yaml
Added `decorate: true` on `pull-tekton-experimental-helm-lint` prow job.
=> Add decorate flag on pull-tekton-experimental-helm-lint

robocat/README.md, tekton/resources/cd/clusters.yaml
It may be useful to drive deployments on the dogfooding cluster
from robocat, since both recent updates on pipelines and
triggers require deleting resources.
Adding the pipeline resource and docs required to do that.# Submitter Checklist
review them:
=> Add the resource and docs to drive dogfooding from robocat

prow/config.yaml
Added missing entrypoint.
It should be ok now, sorry for the inconvenience, it's not easy to get the job definition right first try.
=> Fix pull-tekton-experimental-helm-lint

tekton/images/test-runner/Dockerfile, tekton/images/test-runner/entrypoint.sh
The k8s/test-infra bootstrap python script doesn't work on Python 3,
so let's force it to use Python 2.
review them:
=> Fix test-runner image: use python2 for bootstrap

tekton/images/tkn/Dockerfile
Not sure if this image is used in any capacity like the [test runner image](https://github.com/tektoncd/plumbing/blob/f2cb918059f532b0a2ef97370fc237774bbf9161/tekton/images/test-runner/Dockerfile#L207), but wanted to keep it up to date with the latest version of `tkn`.
=> Update tkn Image to v0.8.0

buildbot/Dockerfile
The README directs us to use ko to build and deploy the buildbot,
doesn't seem like we need this dockerfile anymore (maybe!)
Unless there's a reason we still need it @vdemeester ?
review them:
=> Remove buildbot Dockerfile 🤖

prow/config.yaml
This PR adds dashboard and triggers charts to the linter job.
Related issue: #306 
~~Do not merge before https://github.com/tektoncd/experimental/pull/513 is merged~~
=> Add missing charts to be linted

prow/config.yaml
The pipeline and triggers post submit go-coverage jobs were using
the `safe` tag which does not exist. This commit moves them back to
using the latest tag.(The CLI coverage job uses a non-latest tag and
is not affected).
Fixes #328
review them:
=> Switch to latest tag for post coverage jobs

prow/config.yaml
This PR adds a prow job to check helm charts docs are up to date in `tektoncd/experimental` repository.
Related issue: #309 
The script for checking helm docs was added here: https://github.com/tektoncd/experimental/pull/510
=> Add prow job to check helm doc is up to date

prow/config.yaml
Adding `needs-rebase` and `needs-ok-to-test` to `missingLabels`.
For prow, `missingLabels` are labels that prevent `tide` to merge pull-requests.
/cc @afrittoli @sbwsg @bobcatfish 
review them:
=> Add more missingLabels 🏷

prow/config.yaml
The job can still be invoked on demand via the command, but we
don't really need to run this on every PR.
review them:
=> Disable the try-out-prow-plus-tekton job

prow/config.yaml
This PR adds a prow job to check chart version is incremented when a chart is modified.
Related issue: https://github.com/tektoncd/plumbing/issues/337
Do not merge before https://github.com/tektoncd/experimental/pull/518
=> Add prow job to check chart version increment

tekton/images/test-runner/entrypoint.sh
This is a workaround, and should be fixed once
https://github.com/google/licenseclassifier/issues/20 is fixed.
review them:
=> Clone licenseclassifier in GOPATH to fix go-licenses

scripts/presubmit-tests.sh
Do not rely on `githubhelper` to list the changed files.
`githubhelper` is going to query the GitHub API for information that
is already present in the workspace, on the CI (with Prow, but it
would be even true without Prow).
Prow gives us `PULL_BASE_SHA` and `PULL_SHA`, which is all we need to
ask gently `git` for the modified files by the pull request, no need
to query the github api.
/hold
Validating on https://github.com/tektoncd/pipeline/pull/2487 
review them:
=> Simpler list_changed_files 🍶

prow/config.yaml
The command was missing for this job, and it is required with
`decorate: true`.
/cc @afrittoli @nikhil-thomas @chmouel 
review them:
=> Fix pull-tekton-operator-unit-tests prow job 🕹

tekton/images/test-runner/Dockerfile
As we now control the full image definition, we know there is no
`golang` installed before this step, so this `rm -rf` is useless.
review them:
=> test-runner: remove useless rm -rf GOROOT 🐇

tekton/images/ko-gcloud/Dockerfile
We were installing ko from master @ head which means if any bugs are
introduced, we'll hit them. A bug was introduced in how -P works which
was fixed in https://github.com/google/ko/pull/163 by @mattmoor almost
immediately so let's pin to the version with that fix so we can deal
with changes to ko at our leisure vs. surfacing ko errors in our CI.
Fixes #370
review them:
=> Pin verison of ko we install 📌

tekton/cronjobs/ko-gcloud-image-nightly-build-cron/cronjob.yaml, tekton/resources/release/install_tekton_release.yaml
Using the "gcloud-latest" tag breaks the default image pull policy,
we should use the "latest" tag instead.
Work towards #370 
review them:
=> Change ko:gcloud-latest image to ko-gcloud:latest

tekton/images/test-runner/Dockerfile
There is some *mem usage* changes recently on `golangci-lint`, so let's use the latest release.
review them:
=> Bump golangci-lint to 1.26.0

README.md, mariobot/README.md, prow/README.md, tekton/README.md
I tried to update some of the secrets today but I had to guess which
ones were the right ones because our docs had fallen way behind what is
actually in the cluster. There are many many secrets in these clusters
and I don't know what they all do, but I tried to make a start at
writing some of them down.
I'd really like to have a "clusters" folder which has all the config
(e.g. robocat and prow dirs) and docs for the clusters we are using, but
I have a feeling moving these around will mean our configuration needs
to be updated and I didn't feel I could take that one on today.
review them:
=> Add docs on secrets in the clusters 🤫

tekton/ci/checks/check-pr-has-kind-label.yaml, tekton/ci/eventlistener.yaml, tekton/ci/plumbing-template.yaml
Change the CI pipeline name for plumbing to "tekton-plumbing-ci-pipeline"
Added CEL filters to ensure we only run the plumbing pipeline on
changes to the plumbing repo.
Make it possible for several repos to use the kind label check.
review them:
=> Add support for multi-repo on the ci webhook

README.md
I went searching for a bit of info on dogfooding secrets and got lost when
I couldnt find the word "webhook". I should've read more closely but
figured I'd add the term here since it's what they're labelled in
GitHub as well.
Also fixes a small link type (goverance.md -> governance.md) and adds
an entry describing the ci-webhook Secret in the tektonci namespace.
review them:
=> Fix a small link typo, add the word "webhook" and ci-webhook entry

README.md, prow/README.md
We updated the other github tokens we found in the prow cluster but
actually this is the one prow was using, which we found out the hard way
by deleting the old credentials.
Not actually clear now if the other 2 are important at all. The mystery
continues.
review them:
=> Add the most important prow credential! 🤫

tekton/images/test-runner/Dockerfile
The tool is not used anymore and is deprecated upstream (knative.dev)
Fixes #391
review them:
=> test-runner: remove githubhelper binary

prow/config.yaml
Enables prow job for Hub 🐱 
DOCKER_IN_DOCKER is enabled for all test since it requies a database
to be running for api tests to execute
Signed-off-by: Sunil Thaha <sthaha@redhat.com>
review them:
- [🙅 ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=> tektoncd/hub: enable prow job

tekton/ci/jobs.yaml, tekton/ci/plumbing-template.yaml, tekton/ci/tekton-golang-lint.yaml
Closes #378 
Adding a golang lint CI job to be run against the plumbing repository. Follows a very similar structure to #336 and makes use of `golangci-lint` image.
=> Add golang lint CI Job

tekton/ci/plumbing-template.yaml, tekton/cronjobs/alpine-git-nonroot-image-nightly-build-cron/README.md, tekton/cronjobs/alpine-git-nonroot-image-nightly-build-cron/cronjob.yaml, tekton/cronjobs/alpine-git-nonroot-image-nightly-build-cron/kustomization.yaml, tekton/images/alpine-git-nonroot/Dockerfile
In order to test Pipelines credentials in environments without
root users (i.e. in openshift clusters, or other more locked-down
envs) we need a container image that has a non-root user along
with a tool to exercise the credentials.
This commit adds an alpine-git-nonroot image to our plumbing repo
for use in testing credentials in non-root environments. It uses
alpine/git as its base and then adds a user called nonroot with
UID 1000 to it. This image's first intended use is as a Step in
an example TaskRun that will test creds-init credentials with
non-root securityContext. That PR is ongoing here:
https://github.com/tektoncd/pipeline/pull/2671
=> Add a Dockerfile that adds a non-root user to alpine/git base

tekton/resources/release/README.md
Updated the env var lists to include `export` so you can copy paste the
commands into your terminal if you want.
Also while using the draft release task I looked at previous runs and it
looks like the bucket being used previously was actually the pipelines
specific bucket, the one in the example was at the root of the bucket
and so I panicked when I ran it initially and saw the dashboard bucket
being affected in the logs.
review them:
=> Fixes to draft release docs 📝

tekton/resources/release/github_release.yaml
In tektoncd/pipeline#2786 @ckadner pointed out that the one liner installation line
didn't work because "Pipeline" was capitalized in the path (kind of
surprising that the path is case-sensitive but that's another story!)
It seems that `TEKTON_PROJECT=${p^}` is a bash 5.0 syntax that
capitalizes the word and in the one liner we are using that value, so
instead we will use the uncapitalized value and only captialize in the
spot where we need it.
Closes tektoncd/pipeline#2786
review them:
for more …
=> Use lowercase project name in installation one-liner 🎣

tekton/images/hub/Dockerfile
The only available versions in alpine 3.11 for git is 2.24.3-r0, and the only available hub package in the edge/testing repo is 2.14.2-r1.
Fixes #379.
Signed-off-by: Tom George <tg82490@gmail.com>
- install git 2.24.3-r0
- install hub 2.14.2-r1
review them:
=> Set correct git and hub versions

README.md
A while ago I added a workload-id node pool to support the pipelinerun-logs
app for watching stackdriver logs of pipelineruns.
This PR adds a few lines of documentation explaining the difference between
the default and workload-id node pools.
review them:
=> Document usage of workload-id node pool in dogfooding

tekton/resources/nightly-release/base/eventlistener.yaml, tekton/resources/nightly-release/base/kustomizeconfig/eventlistener.yaml
Triggers v5 changed bindings.name to bindings.ref, which breaks the
kustomise configuration. Fixing that.
review them:
=> Change the kustomise setup to use bindings ref

tekton/ci/jobs.yaml
The pull request updates the golang-lint CI job running against the plumbing repo to using golangci-lint version 1.27.0. This is motivated by #430 to keep the golang-lint experience consistent across projects.
=> Update golangci-lint CI Job Version to 1.27.0

prow/config.yaml
The coverage tool doesn't handle very well when the go code is not on
the root of the repository, so disabling it on the hub. This is temporary.
/cc @sthaha @afrittoli @bobcatfish @chmouel @nikhil-thomas 
review them:
=> prow: disable go-coverage jobs on tektoncd/hub

tekton/cronjobs/robocat-dashboard-deploy-latest-cron/cronjob.yaml
The dashboard robocat deployment cronjob was using extra values that don't
appear in the pipeline or triggers cronjobs.
This PR makes the cronjobs match and hopefully will allow the dashboard
nightly deployments in robocat to resume.
review them:
=> Update Dashboard Robocat deployment cronjob to match pipeline and triggers

tekton/cronjobs/cleanup-cd-cron-base/README.md, tekton/cronjobs/cleanup-cd-cron-base/kustomization.yaml, tekton/cronjobs/cleanup-cd-cron-base/trigger-resource-cd.yaml, tekton/cronjobs/dogfooding-cleanup-default-cron/README.md, tekton/cronjobs/dogfooding-cleanup-default-cron/cronjob.yaml, tekton/cronjobs/dogfooding-cleanup-default-cron/kustomization.yaml, tekton/cronjobs/dogfooding-cleanup-tektonci-cron/README.md, tekton/cronjobs/dogfooding-cleanup-tektonci-cron/cronjob.yaml, tekton/cronjobs/dogfooding-cleanup-tektonci-cron/kustomization.yaml, tekton/resources/cd/bindings.yaml, tekton/resources/cd/cleanup-template.yaml, tekton/resources/cd/clusters.yaml, tekton/resources/cd/eventlistener.yaml, tekton/resources/cd/serviceaccount.yaml, tekton/resources/kustomization.yaml
Add a new trigger to the tekoncd event listener, for cleanup.
The triggers runs tkn pr|tr delete --all with a --keep param,
to keep the latest N runs.
Add a cluster role and a service account bound to it in the
default and tektonci namespaces. The cluster role gives
permission to list and delete prs and trs.
Add a cluster resource that uses the new service account.
This is used by the cleanup task to direct tkn to the
dogfooding cluster.
Add a new cronjob base for cleanup jobs, and a two jobs
based out of it, to cleanup in the default and tektonci
namespaces on the dogfooding cluster,
Once this is in place, it will be easy to add more cronjobs
to cleanup other namespaces / clusters if needed.
It will also be possiblo iterate on the cleanup task adding
more features and nobs to it.
The …
=> Automatically delete old pr and tr on dogfooding

tekton/resources/cd/cleanup-template.yaml
The "--keep" option in tkn does not require "--all" anymore
since tkn v0.9.0, so removing that.
review them:
/kind cleanup
=> Simplify cleanup task

label_sync/labels.yaml
While we are trying to fix the kind/ label check on repositories,
removing all label single quote from label descriptions as a temporary
fix.
This is to get a fix quickly than #449 (that make the eventlistener panic)
review them:
=> Temporarly remove quotes from label description

buildbot/cmd/buildbot/main.go
Don't send a daily ping message like:
> Hello :wave: today's <@> is the buildcop :cop:
This message can still be sent if you ask buildcopbot directly and there is nobody currently assigned.
/assign @vdemeester 
review them:
- [nope] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [yep] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
=> Don't send daily ping if there is no buildcop

tekton/cd/pipeline/overlays/dogfooding/config-defaults.yaml, tekton/cd/pipeline/overlays/dogfooding/kustomization.yaml, tekton/resources/cd/bindings.yaml, tekton/resources/cd/eventlistener.yaml, tekton/resources/cd/notification-template.yaml, tekton/resources/kustomization.yaml
Configure tekton in the dogfooding cluster to send cloud events to an
event listener. Add the event listener along with an hello world
trigger template that reacts to tasktun from the configmaps tekton cd
service.
In future, we can use this service to send notifications upon successful
or failed completion of tasks and pipelines, for instance to the
build-cop slack channel, to github checks and more.
review them:
/kind feature
=> Setup the initial infra for dogfooding events

tekton/cronjobs/ko-gcloud-image-nightly-build-cron/README.md, tekton/images/ko-gcloud/Dockerfile, tekton/resources/release/install_tekton_release.yaml
The latest version of the ko-gcloud image does not include kubectl
anymore, so adding it back. This allows running deployments with that
image and restore the CD to the robocat cluster.
review them:
/kind bug
=> Fix release deployment

tekton/images/ko-gcloud/Dockerfile
Fixes https://github.com/tektoncd/plumbing/issues/426 - hopefully. Todo build ourselves and prove it fixes this, and check the upgrade is safe for everything else in Tekton.
review them:
=> Bump ko version in ko-gcloud to v0.5.1 from v0.5.0

tekton/images/ko/Dockerfile, tekton/images/test-runner/Dockerfile
Follow up on #427
This should hopefully fix the nightly too (they might use `ko` 0.5.0 with this patch).
review them:
=> Pin ko to 0.5.1 in test-runner and ko

prow/config.yaml
This PR creates new prow jobs to run integration tests against multiple versions of pipelines:
- v0.11.3
- v0.12.1
- v0.13.2
Those versions should be supported by the current dashboard, therefore it makes sense to test them.
/cc @a-roberts @AlanGreene @afrittoli @vdemeester 
review them:
=> Add dashboard integration tests with different pipelines versions

addpermissions.py
I'd been pasting in everyone's emails as I went for really no good
reason at all, esp. since there's no reason to re-run it for everyone
that already has permissions every time I add someone (and that is
sloooooow).
I re-ran this today for @savitaashture @nikhil-thomas and they are now
listed at https://github.com/tektoncd/plumbing/tree/master/buildbot#tekton-buildcop
so I felt like it made sense to remove this list.
review them:
=> Remove emails from script example

prow/config.yaml
This would start a container in the pod with postgres for the hub
testing need, and thus removing the requirement to depend on docker.
Let's get #451 in to unblock current tektoncd/hub PRs, and do that after :upside_down_face: 
/cc @sthaha @nikhil-thomas @afrittoli 
/hold
review them:
=> prow: add postgres sidecar and remove dind for hub

prow/config.yaml
This reverts commit 8203b6fd95d12222134ff31233a052a579535e3c.
Adding the postgres sidecars appears to have put `hook` into a bad state:
"Invalid presubmit job pull-tekton-hub-build-tests: pod spec must specify
exactly 1 container, found: 2"
review them:
=> Revert "prow: add postgres sidecar and remove dind for hub"

prow/config.yaml
https://github.com/tektoncd/hub/pull/30 removes the need for running
Docker in Docker, hence removing the flags 🤞
Signed-off-by: Sunil Thaha <sthaha@redhat.com>
review them:
- [🙅 ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=> Hub: remove DIND and privileged securityContext

docs/dogfooding.md, tekton/ci/checks/check-pr-has-kind-label.yaml, tekton/ci/kustomization.yaml, tekton/cronjobs/bases/folder/trigger-resource-cd.yaml, tekton/cronjobs/dogfooding/manifests/kustomization.yaml, tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs-nightly/README.md, tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs-nightly/kustomization.yaml, tekton/cronjobs/dogfooding/manifests/plumbing-tekton-nightly/README.md, tekton/cronjobs/dogfooding/manifests/plumbing-tekton-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/manifests/plumbing-tekton-nightly/kustomization.yaml, tekton/images/kubectl/Dockerfile, tekton/resources/cd/clusters.yaml, tekton/resources/cd/folder-template.yaml, tekton/resources/cd/kustomization.yaml, tekton/resources/cd/serviceaccount.yaml, tekton/resources/kustomization.yaml, tekton/resources/release/kustomization.yaml
Add a tekton-cd account that is admin on default, tektonci and
mario namespaces (it can control all resource types that are
included in the deploy in those namespaces).
Add a pipeline resource associated to that service account.
Add a cron job that deploys resources from the tekton folder in
the plumbing repo to the dogfooding cluster, using the tektoncd
account. Runs at 10:30pm UTC daily.
Add a cron job that deploys cronjobs from the tekton folder in
the plumbing repo to the dogfooding cluster, using the tektoncd
account. Runs at 9:30pm UTC daily.
Since kubectl includes version v2.0.3 of kustomize, which still
uses bases instead of resources, add kustomize v3 to the kubectl
image, and change the folder trigger template to use kustomize
build for overlays instead of kubectl -k.
Improve …
=> Deploy dogfooding nightly

tekton/ci/plumbing-template.yaml
The check name is wrong for tekton-golang-lint so /test tekton-golang-lint
does not work. Fixing that.
review them:
/kind bug
=> Fix check name for tekton-golang-lint

tekton/resources/cd/bindings.yaml, tekton/resources/cd/eventlistener.yaml, tekton/resources/cd/notification-template.yaml
Replace the hello world task with a slack notification that is
sent to the build-cop channel when a configmap deployment fails.
review them:
/kind feature
=> Setup slack notifications for failed configmap deploys

prow/config.yaml
As part of addressing https://github.com/tektoncd/pipeline/issues/2917 the PR creates a test job just like the existing integration test job, but with the difference of enabling the new validation webhook that enforces get permissions to ClusterTask's for the SAs associated with PipelineRuns and TaskRuns
The existing integration job will run with the new webhook disabled.
This new job turns it on.
At least initially, this will be an optional job, as we vet things in https://github.com/tektoncd/pipeline/pull/2797
As reviews progress, if deemed satisfactory by the community I will follow up with a PR that make this mandatory.
/assign @vdemeester 
review them:
- [ n/a ] Includes …
=> add prow job that enables cluster task auth webhook integration tests

buildbot/README.md
@vdemeester requested giving @sthaha access to the dogfood cluster to
setup the preview tekton hub instance (very exciting!!). The simplest
way to do this is to run this script, though it gives @sthaha access to
a bunch of unnecessary clusters as well. I wanted to record somewhere
who we have given access to and why so I'm adding that here. In the long
run it'd be cool to have automation grant this access based on a list of
names we commit here :D
review them:
=> Record having given build cop access to @sthaha

tekton/images/test-runner/Dockerfile
I think this is causing the current presubmit error:
Error: cannot register licenses from archive: open /home/prow/go/pkg/mod/github.com/google/licenseclassifier@v0.0.0-20190926221455-842c0d70d702/licenses/licenses.db: no such file or directory
This was changed to use modules in https://github.com/tektoncd/plumbing/commit/fb80e6b4c5b88032c8cf6eadcf04d4b9532ac076
review them:
=> Don't use go modules for licenseclassifier.

tekton/images/test-runner/Dockerfile
go-licenses save is still failing in CI across our repos. I missed this in
https://github.com/tektoncd/plumbing/pull/485
I'm still mostly just guessing at fixes because I don't have a great way to repro this locally.
review them:
=> Also disable go modules for go-licenses.

tekton/ci/checks/check-pr-has-kind-label.yaml
Labels are extracted from the JSON payload of the github
event, so they must be a valid JSON fragment. The problem
of labels with single quotes in the description begins when
we assign that JSON fragment to a variable so we can later
parse it with json.loads.
The solution to that is to use the triple-quotes syntax
to define the variable that holds the json.
review them:
/kind bug
=> Handle the issue of labels with quotes within description

prow/config.yaml
cleaning up since we will not be going with a "native" webhook based approach re: https://github.com/tektoncd/pipeline/pull/2797 https://github.com/tektoncd/community/pull/152 and https://github.com/tektoncd/pipeline/issues/2917 (if we even consider the scenario in tektoncd* at all)
/assign @vdemeester
=> remove job related to https://github.com/tektoncd/pipeline/pull/2797

tekton/resources/nightly-release/overlays/pipeline/template.yaml
Add nop-image resource to pipelinerun as the referred pipeline has a new
`builtNopImage` param (https://github.com/tektoncd/pipeline/pull/3041)
review them:
=> Add nop-image resource to pipline trigger template

tekton/resources/ci/github-template.yaml
Update the trigger template that is responsible to update checks
in github so that the taskrun is run as non-root.
This ensures that the upload step of the resource has read access
to the content of the PR on file system.
review them:
/kind bug
=> Run the GitHub check update task as non-root

tekton/resources/nightly-release/overlays/dashboard/template.yaml, tekton/resources/nightly-release/overlays/pipeline/template.yaml, tekton/resources/nightly-release/overlays/triggers/template.yaml
Missed some files to update to use $(tt.params) while doing this PR https://github.com/tektoncd/plumbing/pull/494
And it caught after upgrading triggers version to 0.7.0 on dogfooding cluster and now all nightlies are failing because of this with below error
```
Warning  Failed         4m12s  PipelineRun  PipelineRun default/triggers-release-nightly-ppwl6 can't be Run; it tries to bind Resources that don't exist: error following resource reference for source-repo: pipelineresource.tekton.dev "git-source-$(params.projectName)-ppwl6" not found
``` 
/cc @afrittoli
review them:
_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTIN …
=> Update params to tt.params in missed files

prow/config.yaml
Currently, Tekton Build Cops have to manually check issues and pull
requests then ping authors if they haven’t been updated in a while.
This is a cumbersome process that can be automated and save build cops
time.
In this PR, we have automated this Build Cop task by adding lifecycles
management to issues and pull requests across the tektoncd github org. 
The [prow lifecycle plugin](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/lifecycle) is [already added](https://github.com/tektoncd/plumbing/blob/bd59601a4f2c0f1ce95a9ce0bb4342bfcf8d4489/prow/plugins.yaml#L35) in tektoncd org -- this PR enables 
it to handle the issues/prs lifecycle management and save build cops time.
The lifecycles states are:
- `active`: issue or PR actively being worked on by a contributor
- …
=> Automate Issues and Pull Requests Lifecycle

tekton/ci/plumbing-template.yaml
It looks like the pipeline params is not replace into resource specs
so use the trigger template tt.params instead.
review them:
/kind bug
=> Use tt.params in resourceSpec

tekton/ci/kustomization.yaml, tekton/mario-bot/mario-github-comment.yaml, tekton/mario-bot/mario-image-build-trigger.yaml, tekton/resources/cd/configmap-template.yaml, tekton/resources/cd/folder-template.yaml, tekton/resources/ci/github-template.yaml, tekton/resources/nightly-release/base/template.yaml, tekton/resources/nightly-release/overlays/dashboard/template.yaml, tekton/resources/nightly-release/overlays/pipeline/template.yaml, tekton/resources/nightly-release/overlays/triggers/template.yaml, tekton/resources/org-permissions/peribolos-trigger.yaml
Until we stop using pipeline resources alltogether,
stop creating pipeline resources in the cluster, embed them
instead wherever possible in the *run definitions.
review them:
/kind cleanup
=> Stop creating pipeline resources in trigger templates

prow/config.yaml
As of today, an issue is close after 30 days (without necessarly been
rotten) because it does filter them out. Same for lifecycle/rotten, it
does not do 30 + 90 days, but only 90 days.
It seemed there was way too much issue being closed :sweat_smile: 
/cc @jerop @afrittoli @bobcatfish 
review them:
=> prow: fix query for stale, rotten and close issues

tekton/resources/nightly-release/base/template.yaml, tekton/resources/nightly-release/overlays/dashboard/template.yaml, tekton/resources/nightly-release/overlays/pipeline/template.yaml, tekton/resources/nightly-release/overlays/triggers/template.yaml
The nightly releases were previously creating a new storage resource for each
run.  This was changed in #514 to re-use the same per project bucket for each
run. However, we still had the PipelineResource in the nightly TriggerTemplate
which means Triggers will try to create the same PipelineResource on each run
-- and in the process fail because the resource already existed.
This commit fixes the error by changing the nightly pipelinerun templates to
use an embedded storage resource.
Found while investigating #516
review them:
=> Use embedded storage resources for nightly releases

tekton/resources/nightly-release/overlays/dashboard/template.yaml, tekton/resources/nightly-release/overlays/pipeline/template.yaml, tekton/resources/nightly-release/overlays/triggers/template.yaml
The url for the git resources for each of the nightlies is
missing from the trigger template. The nightlies are
currently failing with errors like this:
```
Error running git [fetch --recurse-submodules=yes --depth=1 origin
--update-head-ok --force f39feca70117455dbd765cdb9a3c8fbcad134977]: exit
status 128\nfatal: no path specified; see 'git help pull' for valid url
syntax
```
This commit adds the url to the git resources from the
base trigger template's parameters.
=> Add git url to templates for nightlies

tekton/resources/nightly-release/overlays/dashboard/template.yaml, tekton/resources/nightly-release/overlays/pipeline/template.yaml, tekton/resources/nightly-release/overlays/triggers/template.yaml
The earlier path ("/spec/") would mean that resources would contain an
"" field i.e.
```
spec:
"":
resourcetemplates:
```
Thanks @sbwsg for finding this!
review them:
=> Fix json patch path for templates

tekton/resources/nightly-release/overlays/dashboard/template.yaml, tekton/resources/nightly-release/overlays/pipeline/template.yaml
There's a typo in the apiVersions of the resourceTemplates for dashboard
and pipeline TriggerTemplates.
This commit fixes those typos. v1beta -> v1beta1
=> Fixup apiVersion appearing in resourceTemplates

tekton/resources/nightly-release/overlays/dashboard/template.yaml, tekton/resources/nightly-release/overlays/pipeline/template.yaml, tekton/resources/nightly-release/overlays/triggers/template.yaml
Fixes #526 
Problem statement: At the moment our nightly TriggerTemplates are
built without a crucial `params` field that is defined in the base TriggerTemplate.
This means our nightlies aren't building - the params include information like
the correct git repo to fetch.
The current path in the nightly TriggerTemplate overlays is
"/spec". Using this path causes the spec field of the base
template to be completely replaced. The spec field of the base
includes a "params" field that we want to keep in each built
TriggerTemplate. Replacing "/spec" means we lose the "params" field.
This commit changes the path to "/spec/resourcetemplates" and
updates the value to be an array entry. The result is that the
final built document includes both the base template's params
field as well as the …
=> Update TriggerTemplate overlays to use different path

tekton/resources/cd/eventlistener.yaml, tekton/resources/ci/bindings.yaml, tekton/resources/ci/github-template.yaml
The log app is taking too much time to load, so revert to
the dashboard even after a CI job is completed, at least
until we have a working alternative.
Improve the link to the dashboard to point to a pipelinerun
(when available) and to the specific pipeline task instead
of always pointing to the the taskrun directly.
This gives visibility into the checks that were executed too.
review them:
/kind cleanup
=> Stop using log app in CI links and improve dashboard link

tekton/resources/ci/github-template.yaml
It may happen that the "start" event is processed after
the "complete" one. To handle this case, we can check
the check status before updating, and skip the update
if we see that a "complete" was already processed.
This does not fully eliminate the possibility of race,
as the two update jobs may still run in parallel,
but it reduces the chances considerably.
review them:
/kind bug
=> Reduce the chance of race condition on github update

tekton/ci/interceptors/add-pr-body/README.md, tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main.go, tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main_test.go
`add-pr-body` interceptor only works with the public GitHub. This PR simply adds the GitHub OAuth authentication feature to the `add-pr-body` interceptor.
review them:
=> GitHub Enterprise authentication for add-pr-body interceptor

tekton/ci/bindings.yaml, tekton/ci/eventlistener.yaml, tekton/ci/interceptors/add-team-members/README.md, tekton/ci/interceptors/add-team-members/cmd/add-team-members/kodata/LICENSE, tekton/ci/interceptors/add-team-members/cmd/add-team-members/main.go, tekton/ci/interceptors/add-team-members/cmd/add-team-members/main_test.go, tekton/ci/interceptors/add-team-members/config/100-namespace.yaml, tekton/ci/interceptors/add-team-members/config/200-serviceaccount.yaml, tekton/ci/interceptors/add-team-members/config/add-team-members.yaml, tekton/ci/kustomization.yaml, tekton/ci/tekton-cd-template.yaml
Add a custom interceptor for team members
Add a custom interceptor that fetches the public list of members
and private least of maintainer team members for the org/project
in the payload.
The interceptor can be used in combination with existing event
listener to add filters that only allow certain pipeline to be
executed by owners or org members.
review them:
/kind feature
=> Add a custom interceptor for team members

boskos/boskos.yaml
The current boskos janitor was failing to clean up projects which seems to be
due to GCP adding two new logging sinks that cannot be deleted. The new boskos
image fixes this. See kubernetes-sigs/boskos#37 for more details.
I'm using the staging GCR like https://github.com/kubernetes/k8s.io/pull/1161 in order to unblock our tests. 
Fixes #534
review them:
=> Update boskos images to latest

tekton/resources/ci/github-template.yaml
When the job is pending, we currently set it to error.
This issue was introduced in #531
Restore the correct behaviour.
Add more details to the github update log
Currently we do not log anything in the github update step log.
This makes it difficult to troubleshoot issues, so add some logging.
review them:
/kind cleanup
=> Fix github check status while pending 

tekton/resources/nightly-release/overlays/dashboard/template.yaml
Closes https://github.com/tektoncd/plumbing/issues/553
As part of the changes for https://github.com/tektoncd/dashboard/issues/1505
the `bucketName` param was removed from the dashboard release pipeline.
A new `releaseAsLatest` param was introduced, consistent with other Tekton projects,
which defaults to `true` and so can be omitted here as that's the desired behaviour
for the nightly releases.
**Note:**
The following changes should be applied on the cluster before merging this:
- https://github.com/tektoncd/dashboard/blob/8498a7e0e104b1075f1d7add652cb2e649067288/tekton/publish.yaml
- https://github.com/tektoncd/dashboard/blob/0357f0d41c9bc95341e13948a2dcdef7bcc39001/tekton/release-pipeline.yml
review them: …
=> Update dashboard nightly release template

boskos/boskos.yaml
This change deploys Boskos as a Deployment rather than a StatefulSet, to enable quicker feedback in the deployment process, and removing the need to delete the Boskos pods before new pods are started.
This addresses #193
review them:
- [] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=> Change Boskos StatefulSet to Deployment.

tekton/ci/eventlistener.yaml, tekton/ci/templates/bindings.yaml, tekton/ci/templates/tekton-cd-template.yaml
PR https://github.com/tektoncd/plumbing/pull/513 added a reference
to the tekton-cd-template but failed to include the file, which
is causing the resource deployment to fail.
Adding the file back and fixing the template used for the `all`
triggers.
review them:
/kind bug
=> Add missing tetkon-cd-template

tekton/ci/eventlistener.yaml
Run plumbing CI when using `/test <jobname>`.
The event listener must have all four triggers:
- pull request event, plumbing repo
- comment event, plumbing repo
- pull request event, all repos
- comment event, all repos
review them:
/kind bug
=> Run plumbing specific tests on comment

tekton/ci/README.md, tekton/ci/templates/all-template.yaml, tekton/ci/templates/plumbing-template.yaml, tekton/resources/cd/eventlistener.yaml, tekton/resources/ci/bindings.yaml, tekton/resources/ci/github-template.yaml
The PullRequestPipelineResource that is used today to update the
GitHub status tries to update all statuses for which it finds a
change - which causes the racy behaviour described in #589.
Stop using pipeline resources for pull requests, use a task from
the catalog instead to update a single status at the time.
This depends on v0.2 of the task defined in https://github.com/tektoncd/catalog/pull/516
Using the Tasks requires a little extra work in CEL filters and
bindings, but overall the new solution is simpler.
This drops support for CI jobs as tasks (instead of pipelines) as
now we documented that pipeline is the required format and the only
task CI job (check label) has now been migrated to pipeline.
Fixes #589
These are the …
=> Update one commit status at the time

tekton/resources/release/github_release.yaml
If no PR in the release has release notes, or all of them do, one
of the two greps will fail and fail the step. Fix that with || true.
review them:
/kind bug
=> Handle the cases of many or no release notes

tekton/images/ko-gcloud/Dockerfile, tekton/images/ko/Dockerfile, tekton/images/test-runner/Dockerfile
Bump `ko` version to be able to use new `--platform=all` feature to build multi-arch images.
Part of work to build multi-arch Tekton images using `--platform=all`, see https://github.com/tektoncd/pipeline/pull/3314
Verified that [pipeline](https://github.com/tektoncd/pipeline/commit/f51e09ed1bf5b6b31a9df120292b5d3439911899), [triggers](https://github.com/tektoncd/triggers/commit/be425738ab62582ba28045efc8a91b37dcb4ab98), [operator](https://github.com/tektoncd/operator/commit/183659a26b9d832aeba851322084581a193b6be6) and [dashboard](https://github.com/tektoncd/dashboard/commit/e43ff02ebafaa0da491e6628e05b17cfeb6aff79) use now `ko://` prefix, as for `v0.6.0` it's a requirement.
review them: …
=> Bump ko version to v0.6.0

catlin/pkg/validator/task_validator.go, catlin/pkg/validator/task_validator_test.go, catlin/pkg/validator/validate_test.go
This allows images to have a specific tag along with digest. 
It will give a warning if an image doesn't have a tag or have the latest tag when it has a digest.
Fixes: #602 
review them:
Valid Image 
```
docker.io/ansible/ansible-runner:1.4.6@sha256:bd09ef403f2f90f2c6bd133d7533e939058903f69223c5f12557a49e3aed14bb
```
Now, Warns if the image has the `latest` or no tag along with the digest.
Invalid Images
```
WARN : Step "s2" uses image "docker.io/ansible/ansible-runner@sha256:bd09ef403f2f90f2c6bd133d7533e939058903f69223c5f12557a49e3aed14bb"; consider using a image tagged with specific version along with digest eg. abc.io/img:v1@sha256:abcde
```
```
WARN : Step …
```
=> Catlin: Fixes warning for images having tag along with digest

tekton/cronjobs/dogfooding/images/buildx-gcloud-nightly/README.md, tekton/cronjobs/dogfooding/images/buildx-gcloud-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/buildx-gcloud-nightly/kustomization.yaml, tekton/images/buildx-gcloud/Dockerfile
This image will be used to build multi-arch images with `docker buildx`
and push them to Google cloud.
/kind misc
review them:
=> Add buildx-gcloud image to plumbing

tekton/ci/eventlistener.yaml, tekton/ci/jobs/kustomization.yaml, tekton/ci/jobs/tekton-python-test.yaml, tekton/ci/templates/kustomization.yaml, tekton/ci/templates/website-template.yaml
The tekton ci website has the responsibility of syncing the documentation and delivering this information in the form of a website. The sync script has tests to ensure that it is functioning as expected. This is a problem because we are not ensuring all the tests as part of our ci/cd pipeline for the tekton website. This issue can be solved by adding a task to the ci/cd netlify pipeline, adding a task to ci/cd in prow, or setting up a pipeline in tekton ci/cd. The best approach is to add the pipeline to tekton because it allows us to add other tests from the tekton catalog. This provides us greater flexibility. It also presents itself as a great opportunity to dog food tekton. These changes allow the tests to run as part of the ci process for the tekton website. Adding more tasks to the …
=> add CI/CD pipeline for the tekton website

DEVELOPMENT.md, hack/tekton_in_kind.sh
fix issues when setup tekton with kind:
1. remove -u: if no arguments are specified when executing hack/tekton_in_kind.sh, it reports error './tekton_in_kind.sh: line 50: TEKTON_PIPELINE_VERSION: unbound variable'
2. set 120 seconds as the timeout value for 'kubectl wait'
3. sleep 2 seconds to get smee client ready
review them:
=> fix issues when setup tekton with kind

tekton/ci/templates/website-template.yaml
The name of the trigger template does not match the one
specified in the event listener and that of other trigger
templates, so fixing that.
review them:
/kind bug
=> Fix the name of the tekton website trigger template

tekton/cronjobs/README.md, tekton/cronjobs/dogfooding/images/kustomization.yaml
Add `buildx-gcloud-nightly` to kustomization list.
Also update documentation how to add daily builds for new images.
/kind misc
review them:
=> Add the buildx cronjob to kustomize so it gets deployed

tekton/cronjobs/bases/image-build/trigger-image-build.yaml, tekton/cronjobs/dogfooding/images/alpine-git-nonroot-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/skopeo-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/tkn-nightly/cronjob.yaml, tekton/resources/images/bindings.yaml, tekton/resources/images/eventlistener.yaml, tekton/resources/images/kustomization.yaml, tekton/resources/images/multi-arch-template.yaml, tekton/resources/images/single-arch-template.yaml, tekton/resources/kustomization.yaml
Extend current cronjobs/triggers setup to build dogfooding images in multi-arch form when it's necessary:
- create 2 TriggerTemplates and TriggerBindings for single-arch and multi-arch cases
- extend eventlistener to decide which build to do (based on platforms parameter value)
- add PLATFORMS parameter to cronjobs to be able to specify for which platforms multi-arch image should be
- extend several image cronjobs to use multi-arch build (`tkn`, `alpine-git-nonroot`, `skopeo`)
- for multi-arch build `buildx` in main container and `dind` sidecar are used
- builds will be done on amd64 dogfooding cluster, not other native hardware is required.
Not every image can be built with this approach, so I suggest to use it only for images, which are required for the tests.
The build cronjobs were …
=> Add build of dogfooding images in multi-arch form

tekton/resources/org-permissions/peribolos.yaml
The old version of periobolos failed to manage team access to repos
with read permissions. Updating to a more recent version fixes the
issue.
review them:
/kind misc
=> Update the version of peribolos

scripts/deploy-release.sh
We were calling `getopts` with only `:p:v:` which means
only the -p and -v flags were considered valid.
This commit expands the set of valid flags to include b,e,f.
review them:
=> Add bef args as valid to deploy-release script

prow/config.yaml
In #621 `TEST_RUN_ALL_TESTS` environment variable was added to `tektoncd/pipeline`
periodic job instead of `tektoncd/catalog`. This is to ensure we run
all the tests during the nightly tests of the catalog.
/cc @vdemeester @afrittoli 
/kind misc
review them:
=> prow: Fix catalog periodic jobs

scripts/presubmit-tests.sh
In `git --no-pager diff --name-only 65dd35a5e8a7e63443b52df70ea5bbc0bc621dac..`
`${Pull_SHA}` doesn't gives `SHA` of the PR so fixed that to `${PULL_PULL_SHA}`.
review them:
=> scripts: Fix list_changed_files in presubmit-tests

prow/config.yaml
Changing the value of `TEST_RUN_ALL_TESTS` env variable to string value `true` since the periodic job is not running properly
/kind misc
/cc @vdemeester @piyush-garg 
review them:
=> prow: Fix catalog periodic job

scripts/e2e-tests.sh, scripts/library.sh, scripts/presubmit-tests.sh
If `cat` is called with no params, it assumes that it needs to read from
stdin, and will block for user input. This is problematic if
${CHANGED_FILES} is unset (i.e. when not running in a PR), since it
looks like the script just hangs.
Long term we should probably look into modifying the ${CHANGED_FILES}
behavior to fallback to a local diff, but for now make sure params are
quoted so that the script fails fast.
review them:
=> scripts: Make sure `cat` params are quoted.

prow/config.yaml
Remove the legacy postsubmit job for the Dashboard repo. It is no
longer necessary (or complete) as we have nightly releases running
on dogfooding for quite a while now with a different set of output
artifacts.
review them:
=> Remove Dashboard postsubmit job

tekton/cronjobs/dogfooding/images/kubectl-nightly/cronjob.yaml
Fix the URL set in the cronjob to build the kubectl container
image nightly:
tekton/plumbing -> tektoncd/plumbing
Fixes #649
review them:
/kind bug
=> Fix the plumbing URL in the kubectl nightly

tekton/images/test-runner/Dockerfile
Adds [Kubernetes-in-Docker (kind)](https://kind.sigs.k8s.io/) to test-runner image. This is being
used for e2e tests (see
https://github.com/tektoncd/experimental/tree/master/results/test/e2e).
Blocking https://github.com/tektoncd/experimental/pull/673
review them:
=> Add kind to test-runner image.

prow/config.yaml
Enables dind to allow usage of kind - this is currently blocking https://github.com/tektoncd/experimental/pull/673 with the following error:
```
ERROR: failed to create cluster: failed to list clusters: command "docker ps -a --filter label=io.x-k8s.kind.cluster=tekton-results --format '{{.Names}}'" failed with error: exit status 1
Command Output: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
suggesting that docker is not available in the worker.
Looking at existing configs, it looks like the [`DOCKER_IN_DOCKER_ENABLED` environment variable](https://github.com/tektoncd/plumbing/blob/ac9002f78f97fd133d028378bce5748cd8be9f22/tekton/images/test-runner/runner.sh#L50) is used to configure this behavior, and based on [other Tekton project …
=> [experimental] Enable dind for integration tests.

robocat/cadmin/200-rbac.yaml
Add the the ability to work with HPA and disruption budgets to the
tekton-admin cluster role, used by the tekton deployer.
This is needed by the deployer role since these resources are now
used for the pipeline webhook.
review them:
/kind misc
=> Add HPA and disruption budget to tekton-admin

bots/buildbot/README.md, bots/buildbot/cmd/buildbot/main.go, bots/buildbot/cmd/buildbot/rotation.go, bots/buildbot/cmd/buildbot/rotation_test.go
We recently surveyed folks on their preferred name for the infra
monitoring rotation we run to keep an eye on our nightlies and
PR infra. "BuildCaptain" won the day.
Updating as many references as I can find here. I haven't updated the deployment yet, just the
buildbot code.
review them:
=> Update infra monitoring role name to buildcaptain

tekton/images/buildx-gcloud/Dockerfile
Use the latest buildx version can help with sporadic multi-arch image build failures connected to buildkit startup.
review them:
=> Bump buildx version to the latest one

tekton/ci/interceptors/add-pr-body/config/add-pr-body.yaml
It seems like the `ko` prefix is missing in the `add-pr-body` `Deployment` manifest. I also set runAsUser uid for nonroot distroless image, otherwise I'd get `container has runAsNonRoot and image will run as root` when trying to deploy.
review them:
=> Add missing ko prefix to image

tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs-robocat/README.md, tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs-robocat/cronjob.yaml, tekton/cronjobs/dogfooding/manifests/plumbing-tekton-cronjobs-robocat/kustomization.yaml
We already have a cronjob to the deploy the definitions of
cronjobs that run on dogfooding and target dogfooding;
add one that deploys the definitions of cronjobs that run
on dogfooding and target robocat.
review them:
/kind misc
=> Add a cronjob to deploy cronjobs that target robocat

robocat/cadmin/200-rbac.yaml
The Tekton deployer role should be able to deploy HPA and
disruption budgets. They're in the role already, but missing
and "s".
review them:
/kind bug
=> Fix the deployer role to deploy hpa and disruption budget

tekton/resources/nightly-release/overlays/pipeline/template.yaml
The pipelines overlay template still had mention of creds-init
image which was removed from the pipelines project.
See commit https://github.com/tektoncd/pipeline/commit/c8a1623def283939193cb3d1ec3ab7954f404e53
for the removal.
This commit removes mention of creds-init from the list of built images
in the pipeline overlay.
review them:
=> Remove creds-init image from pipeline overlay

tekton/resources/release/github_release.yaml
Fix the task so that it extract release notes when available and
it does not fail if no release notes are available or if all PRs
do have release notes.
review them:
/kind bug
=> Fix the task that extracts release notes

tekton/resources/nightly-release/overlays/triggers/template.yaml
Add `builtCoreInterceptorsImage` resource reference to `triggers-release`trigger template
review them:
=> Update triggers-nightly trigger template

tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main.go, tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main_test.go
This indirectly follows https://github.com/tektoncd/triggers/issues/857 - add-pr-body is broken with the latest release of triggers because it looks in the pr root for its fields. By default these fields have been moved to `extensions`. This PR fixes add-pr-body to actually check in the extensions field.
review them:
/kind bug
=> Structure pr-body to use extensions field

docs/dogfooding.md, tekton/cronjobs/bases/nightly-tests/README.md, tekton/cronjobs/bases/nightly-tests/kustomization.yaml, tekton/cronjobs/bases/nightly-tests/trigger-nightly-test.yaml, tekton/cronjobs/dogfooding/cleanup/bastion-z-nightly/README.md, tekton/cronjobs/dogfooding/cleanup/bastion-z-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/cleanup/bastion-z-nightly/kustomization.yaml, tekton/cronjobs/dogfooding/kustomization.yaml, tekton/cronjobs/dogfooding/nightly-tests/kustomization.yaml, tekton/cronjobs/dogfooding/nightly-tests/pipeline-nightly-test/README.md, tekton/cronjobs/dogfooding/nightly-tests/pipeline-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/pipeline-nightly-test/kustomization.yaml, tekton/resources/nightly-tests/bastion-z/deploy_test_cleanup.yaml, tekton/resources/nightly-tests/bastion-z/kustomization.yaml, tekton/resources/nightly-tests/eventlistener.yaml, tekton/resources/nightly-tests/kustomization.yaml, tekton/resources/nightly-tests/pipeline-deploy-test-template.yaml, tekton/resources/nightly-tests/serviceaccount.yaml
Add cronjob, trigger and pipeline to run s390x pipeline repo e2e tests on remote s390x cluster. Access to s390x cluster is already available on top of dogfooding cluster in bastion-z namespace.
Cronjob allows to specify:
- registry to be used for ko builds
- namespace where pipelinerun should be executed
- name of secret with kubeconfig for s390x cluster
- architectire for code build and tests
Pipeline consists of:
- pipeline code deployment via `ko apply`
- e2e test
- cleanup, which will be performed despite success of failure of previous steps
This setup expects to have kubeconfig for s390x cluster available as secret.
The source code to test is always from master branch.
Cleanup cronjob is extended to control number of stored pipelineruns in bastion-z
namespace.
These are the criteria …
=> Add nightly pipeline tests for s390x

adjustpermissions.py, bots/buildbot/README.md, docs/README.md
In https://github.com/tektoncd/plumbing/pull/481 we gave @sthaha access
to the dogfood cluster for setting up the preview hub instance but
@vdemeester mentione dthat @sthaha is working on other things now, but
@piyush-garg will be working on the hub in the dogfood cluster, so this
commit records that permissions were removed for @sthaha and added for
@piyush-garg.
This is the first time we've removed permissions, so I updated the
script to make that possible :D (not super robust tho haha)
review them:
=> Update permissions script to support removing permissions ✏️

tekton/ci/templates/bindings.yaml, tekton/mario-bot/mario-image-build-trigger.yaml
Fix a binding that was still referring to body.extensions
review them:
/kind bug
=> Fix a binding that was still referring to body.extensions

tekton/ci/templates/all-template.yaml
With v11, strings with quotes are not espaced anymore in trigger
templates, which breaks the all-comment-ci trigger template.
Add an annotation that restores the old behaviour for now, so that
CI may continue working. Eventually we should use marshalJSON or
some alternative to solve the issue without the annotation.
review them:
/kind bug
/cc @dibyom @vdemeester
=> Annotate the tekton-all-ci-pipeline

tekton/resources/kustomization.yaml, tekton/resources/nightly-release/kustomization.yaml, tekton/resources/org-permissions/kustomization.yaml
Several s390x test related resources should be created in `bastion-z` namespace. With default namespace specified in kustomize config of parent `tekton/resources` directory, all resources inside will be created in `default` namespace, see issue https://github.com/kubernetes-sigs/kustomize/issues/880
The idea is not to specify namespace value in `tekton/resources/kustomization.yaml`, but to do it in underlying directories(ci, nightly-release, etc)
/kind feature
/cc @afrittoli
review them:
=> Change namespaces specification for kustomize in tekton resources

tekton/mario-bot/mario-image-build-trigger.yaml
When I deleted the namespace from the secret, I deleted it from the
webhook too incorrectly, restoring it now.
review them:
/kind bug
=> Restore the namespace in mario's webhook

catlin/go.mod, catlin/pkg/cmd/linter/linter.go, catlin/pkg/cmd/linter/script.go, catlin/pkg/cmd/validate/validate.go, catlin/pkg/linter/linter.go, catlin/pkg/linter/script.go, catlin/pkg/linter/script_test.go, catlin/pkg/validator/result.go
This add a command to catlin to launch a language linter on a script field :
`catlin lint script`
Assuming a task as argument it will go over all the tasks and validate according
to a linter.
Configuration is pretty static and in code at the moment, and only has linter
for posix shell/bash and python, will expand on this in further version to be
able to provide a configuration file.
This doesn't handle TaskSpec from taskRuns and pipeline/pipelineRuns
Output would look like this : 
```sh
$ catlin lint script $GOPATH/src/github.com/tektoncd/catalog/task/*/*/*.yaml
WARN : step: ansible-runner is not using #!/usr/bin/env 
WARN : Couldn't find the linter shellcheck in the path
WARN : Couldn't find the linter shellcheck in the path
WARN : Couldn't find the linter shellcheck in the path
WARN : …
```
=> [Catlin] Add a script linter command

tekton/resources/nightly-release/base/serviceaccount.yaml
Nightly release ELs are currently failing trying to list cluster level
bindings for ClusterTriggerBindings. Open question whether this is expected behavior in Triggers,
but this will at least fix our triggers short term.
It's unclear whether this will also fix the `unknown` errors we are
seeing - we are going to fix this first and see if this resolves all the
errors  (i.e. if this error just log-cascaded as the unknown errors).
For #693 
review them:
=> Add ClusterTriggerBindings role for the nightly release service accounts.

tekton/resources/nightly-release/base/kustomizeconfig/eventlistener.yaml, tekton/resources/nightly-release/base/serviceaccount.yaml
This PR fixes following issues for Pipeline, Triggers, Dashboard nightly job
* Triggering nightly job was failing because of permission issue
```
E0128 04:54:56.364871       1 reflector.go:383] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:125: Failed to watch *v1alpha1.EventListener: unknown (get eventlisteners.triggers.tekton.dev)
E0128 04:55:11.864806       1 reflector.go:383] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:125: Failed to watch *v1alpha1.TriggerTemplate: unknown (get triggertemplates.triggers.tekton.dev)
E0128 04:55:16.076674       1 reflector.go:383] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:125: Failed to watch …
```
=> Fix permission issue for all nightly jobs

prow/config.yaml
See
https://github.com/kubernetes/test-infra/blob/8cf1debdff208b12cbee71a6d603a26bcd7f89ce/config/prow/config.yaml#L775-L792
for what this actually does. We suspect this is necessary to configure
prow to be able to run kind properly (but we're not 100% sure).
Part of https://github.com/tektoncd/results/issues/15
review them:
=> Add preset-kind-volume-mounts label to results e2e prow config.

tekton/ci/README.md, tekton/ci/templates/all-template.yaml, tekton/ci/templates/community-template.yaml, tekton/ci/templates/plumbing-template.yaml, tekton/ci/templates/tekton-cd-template.yaml, tekton/ci/templates/website-template.yaml, tekton/resources/cd/cleanup-template.yaml, tekton/resources/cd/configmap-template.yaml, tekton/resources/cd/folder-template.yaml, tekton/resources/cd/helm-template.yaml, tekton/resources/cd/notification-template.yaml, tekton/resources/cd/tekton-template.yaml, tekton/resources/ci/github-template.yaml, tekton/resources/images/multi-arch-template.yaml, tekton/resources/images/single-arch-template.yaml, tekton/resources/nightly-release/overlays/dashboard/template.yaml, tekton/resources/nightly-release/overlays/pipeline/template.yaml, tekton/resources/nightly-release/overlays/triggers/template.yaml, tekton/resources/release/nightly-release-logs-trigger.yaml
The event ID has changed to a UUID in triggers, which makes it
unfit to be part of resource names - it's too long.
Replace the $(uid) with generateName in all trigger templates
review them:
/kind misc
=> Use generateName instead of $(uid) in templates

tekton/ci/jobs/tasks.yaml, tekton/ci/jobs/tekton-kind-label.yaml, tekton/ci/templates/all-template.yaml
The git pipeline resource is not used by the label check, so
remove it from the task, pipeline and trigger template.
review them:
/kind misc
=> Remove unused git resource from label check

tekton/cronjobs/robocat/manifests/plumbing-tekton-resources-nightly/cronjob.yaml
At this moment only installed resources in `default` namespace are taken into account in diff procedure to identify whether updates from `tekton/resources` directory should be applied to CI cluster.
However there are already resources in `bastion-z` namespace, specified in the directory.
To fix the problem namespace parameter in apply cronjob just should be empty, then corresponding diff/apply task will work for all namespaces.
/kind misc
/cc @afrittoli
review them:
=> Allow to update resources from tekton/resources in different namespaces

bots/buildcaptain/cmd/buildcaptain/main.go
While updating build cop -> build captain, I noticed (which I think
other folks have been saying all along!) that the list of ppl in the csv
is loaded once on startup, meaning if there are any updates, you have to
restart to bot. With this change, the list will be loaded every time it
is accessed.
review them:
=> Hot reload the build captain csv 🔥

tekton/ci/jobs/tasks.yaml, tekton/ci/jobs/tekton-kind-label.yaml, tekton/ci/templates/all-template.yaml
The check labels job uses the PR pipeline resource to add a comment
to the PR with instructions for developers in case of failure.
That doesn't work though because in case of failure the sync-up side
of the pipeline resource is not processed, so the commit is not
written.
Fix that by removing the pipeline resource and writing the instructions
to the step log instead. The step log is linked in the github status
details through the tekton dashboard.
In future we might extend the github update service to include
support for comments, but that would require support for results on
failure: https://github.com/tektoncd/pipeline/issues/3749
review them:
_See …
=> Fix the check labels job

tekton/cronjobs/dogfooding/images/catlin-nightly/README.md, tekton/cronjobs/dogfooding/images/catlin-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/catlin-nightly/kustomization.yaml
There is no nightly releases of `catlin` container image as of now.
This PR adds the `CronJob` to enable this.
/cc @afrittoli @vdemeester @savitaashture @piyush-garg 
review them:
=> CronJob to enable nightly build for Catlin

tekton/cronjobs/dogfooding/images/catlin-nightly/cronjob.yaml
Changing the CONTEXT_PATH to `catlin` instead of `tekton/catlin`.
Wrongly passed earlier. My bad :(
review them:
=> Fix CONTEXT_PATH in catlin CronJob

catlin/Dockerfile, catlin/pkg/cmd/validate/testdata/task/maven/0.1/maven.yaml, catlin/pkg/cmd/validate/testdata/task/npm/0.1/npm.yaml, catlin/pkg/cmd/validate/validate.go, catlin/pkg/cmd/validate/validate_test.go, catlin/pkg/test/cobra.go
With the patch now you can run catlin on directories and also you can
now run catlin on multiple inputs.
Sample execution command would be
```sh
$ catlin validate task/black/0.1 task/maven/0.2
```
- Also added tests for the above command.
- Modified Dockerfile to include bash so that user can use catlin as per their script
Closes #715 
Closes #716 
/cc @SM43 @piyush-garg @vdemeester 
review them:
=> Run catlin when task dir path is passed as argument

catlin/Dockerfile
Dockerfile for catlin contains BUILD which is all in UpperCase and kaniko
doesn't supports this so renaming this to `build` all lowercase
review them:
=> Catlin: Fix Dockerfile

docs/dogfooding.md, tekton/cd/dashboard/overlays/dogfooding/ingress.yaml, tekton/cd/dashboard/overlays/robocat/ingress.yaml, tekton/ci/ingress.yaml, tekton/mario-bot/ingress.yaml
Garndener external DNS manager is now installed in the dogfooding
cluster. Add documentation on the installation and configuration process
as well as add annotations to all ingress we use in dogfooding to match
existing DNS record on Netlify side.
For new records, we will not need to provision them manually anymore,
they can be provisioned via annotations on ingresses, services or via
the DNSEntry CRD.
review them:
=> Add DNS manager docs and annotations

catlin/pkg/validator/task_validator.go, catlin/pkg/validator/task_validator_test.go
- This patch fixes validate command which gives warning when tagging
the image as docker.io/cytopia/black:latest-0.2@sha256:abcdef
Signed-off-by: Puneet Punamiya <ppunamiy@redhat.com>
review them:
=> Fix: Catlin validate command

tekton/resources/nightly-release/tasks.yaml
Add golang-build-legacy and golang-test-legacy.
Theres are identical copies of the existing ones, designed to allow
pipeline, dashboard and triggers to switch to them.
This step uncouples the various projects so that we way then:
- switch pipeline, dashboard and triggers one at the time to a publish
task and release pipeline that use workspaces, no resources and thus
the catalog version of golang-build and golang-test
- once the three projects are migrated, the legacy tasks will be
removed
review them:
/kind misc
=> Add legacy tasks to plumbing releases

tekton/ci/interceptors/add-team-members/README.md, tekton/ci/interceptors/add-team-members/cmd/add-team-members/main.go, tekton/ci/interceptors/add-team-members/cmd/add-team-members/main_test.go
/kind feature
We want to make sure only members from our organization can trigger pipelines. We don't use the same team schema that you folks are using, and changing the code to work with different team terminologies would be too hard I think. That's why I thought about making the team part optional. With these changes, the interceptor will not fail if the `team` key is not in the body payload. If you want to use it, you can still set it, but if you don't, that's fine.
review them:
=> Only try to fetch team members if team key is present in body

tekton/ci/eventlistener.yaml, tekton/ci/jobs/kustomization.yaml, tekton/ci/jobs/tekton-catlin-lint.yaml, tekton/ci/templates/catalog-template.yaml, tekton/ci/templates/kustomization.yaml
- Adds a Tekton Task and Pipeline which will run catlin on catalog
tasks.
- Add corresponding TriggerTemplate.
- Modify EventListener to add catlin jobs.
review them:
=> Add Catlin to Catalog CI

tekton/resources/nightly-release/base/template.yaml, tekton/resources/nightly-release/overlays/pipeline/template.yaml
The new pipeline nightly builds will run using workspaces instead of
pipeline resources - once https://github.com/tektoncd/pipeline/pull/3788
is merged.
Change the trigger template to be able to run the new format of the
pipeline.
review them:
/kind misc
=> Run the new pipeline nightlies

tekton/resources/release/prerelease_checks.yaml
Stop using pipeline resources, use workspaces instead.
For the gcs object, use gsutils directly to stat the object,
which saves us downloading the whole bucket to check a single file.
review them:
/kind misc
=> Rework the prerelease-check task to use workspaces

tekton/ci/eventlistener.yaml
Catalog repository doesn't require the check-pr-kind-label as of now so
removing it from the `EventListener` filter.
review them:
=> Remove check-kind-label check from catalog

tekton/ci/interceptors/add-team-members/README.md, tekton/ci/interceptors/add-team-members/cmd/add-team-members/main.go
We are currently fetching the public members of an organization from the `add-team-members` interceptor. This PR changes `add-team-members` to fetch all members instead.
For that, we change the Github API endpoint from `/public_members` to `/members`. Old behavior can still be achieved if the passed `GITHUB_TOKEN` does not belong to the organization, in which case only public members will be listed. If the user owning the `GITHUB_TOKEN` is in the organization, then [both public and private members will be listed](https://docs.github.com/en/rest/reference/orgs#list-organization-members).
review them:
for more …
=> List all members of the org, not just public members

tekton/ci/interceptors/add-team-members/cmd/add-team-members/main.go
/kind bug
When I did the change I didn't take into consideration the new place (`extensions`) where some fields are placed now.
review them:
=> Try to find team key in the right place of the payload

prow/config.yaml
This is a continuation of https://github.com/tektoncd/plumbing/pull/703.
Previously we added the label, but there wasn't any matching definition for\
this label so it didn't actually do anything.
This adds the label definition, as well as the definition for dind for
completeness to match the kubernetes/test-infra environment (https://github.com/kubernetes/test-infra/blob/1d4b6a6db932c31c3996387420401316c9180fc9/config/jobs/kubernetes-sigs/kind/kind.yaml)
Part of tektoncd/results#15
review them:
for more …
=> prow: Add dind and kind presets.

tekton/cronjobs/dogfooding/nightly-tests/s390x/cli-nightly-test/README.md, tekton/cronjobs/dogfooding/nightly-tests/s390x/cli-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/s390x/cli-nightly-test/kustomization.yaml, tekton/cronjobs/dogfooding/nightly-tests/s390x/kustomization.yaml, tekton/resources/nightly-tests/bastion-z/cleanup_tekton.yaml, tekton/resources/nightly-tests/bastion-z/deploy_tekton_component.yaml, tekton/resources/nightly-tests/bastion-z/kustomization.yaml, tekton/resources/nightly-tests/bastion-z/test_tekton_cli.yaml, tekton/resources/nightly-tests/bastion-z/test_tekton_component.yaml, tekton/resources/nightly-tests/cli-deploy-test-s390x-template.yaml, tekton/resources/nightly-tests/eventlistener.yaml, tekton/resources/nightly-tests/kustomization.yaml, tekton/resources/nightly-tests/pipeline-deploy-test-s390x-template.yaml, tekton/resources/nightly-tests/triggers-deploy-test-s390x-template.yaml
- add corresponding cronjob to trigger s390x tekton cli test
- add separate task for cli tests (default e2e test task cannot be used, because cli e2e test has another setup)
- add template to run s390x cli test pipeline
- git clone all required tekton repos
- k8s cluster installation
- pipeline and triggers deployment
- e2e cli test
- k8s cluster removal
As discussed at https://github.com/tektoncd/plumbing/pull/732#discussion_r581833660 pipeline resources were removed in favour of [git-clone](https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.2) task. 
/kind misc
review them:
=> Add pipeline to run s390x cli tests

tekton/ci/jobs/tekton-catlin-lint.yaml
As of now catlin CI is failing whenever someone raises a PR on catalog
and the file changes are not related to task dir. Checking that and
skipping in that case.
/kind bug
/cc @vdemeester @piyush-garg @afrittoli 
review them:
=> Fix Catlin CI to skip validation if no task change

tekton/cronjobs/dogfooding/releases/kustomization.yaml, tekton/resources/nightly-release/kustomization.yaml
Add the two new cronjobs for nightly builds to kustomize so that they
are deployed and executed. Add the corresponding nightly resources to
the kustomize file.
review them:
/kind misc
=> Add the two new cronjobs to kustomize

tekton/resources/nightly-tests/triggers-deploy-test-s390x-template.yaml
The volume size should be large enough to store pipeline, triggers, plumbing source code. So size of workspace volume should be 1Gi.
/kind bug
review them:
=> Fix size of workspace volume for s390x triggers pipeline

tekton/resources/nightly-tests/cli-deploy-test-s390x-template.yaml, tekton/resources/nightly-tests/pipeline-deploy-test-s390x-template.yaml, tekton/resources/nightly-tests/triggers-deploy-test-s390x-template.yaml
Initial 1Gi size of workspaces was not enough to store source code and do the image builds for s390x testing. Propose is to have 2Gi instead.
Current usage is around 1.2Gi-1.5Gi, but to be on the safe side better to have extra disk space.
/kind bug
review them:
=> Use larger workspaces for s390x pipelines

tekton/cronjobs/dogfooding/nightly-tests/s390x/kustomization.yaml, tekton/cronjobs/dogfooding/nightly-tests/s390x/operator-nightly-test/README.md, tekton/cronjobs/dogfooding/nightly-tests/s390x/operator-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/s390x/operator-nightly-test/kustomization.yaml, tekton/resources/nightly-tests/eventlistener.yaml, tekton/resources/nightly-tests/kustomization.yaml, tekton/resources/nightly-tests/operator-deploy-test-s390x-template.yaml
- add corresponding cronjob to trigger s390x tekton operator test
- add template to run s390x operator test pipeline
- git clone all required tekton repos
- k8s cluster installation
- e2e operator test(with operator image build and installation)
- k8s cluster removal
/kind misc
/cc @afrittoli @vdemeester 
review them:
=> Add pipeline to run s390x operator tests

tekton/cronjobs/bases/release/trigger-with-uuid.yaml
The nightly version name is generated from the sha of the last commit.
Depending on the repo that may be on main or master (at least during
the transition), so handle both.
review them:
/kind misc
=> Handle mixed main repo names in triggers

tekton/cd/pipeline/overlays/dogfooding/feature-flags.yaml, tekton/ci/jobs/kustomization.yaml, tekton/ci/jobs/tasks.yaml, tekton/ci/jobs/tekton-golang-tests.yaml, tekton/ci/templates/plumbing-template.yaml
Add a unit test CI job for the plumbing repo.
We have several packages that include unit tests. To test all of them
in a single CI job and dedicated tasks, use a task loop.
The taskloop controller has been deployed to dogfooding on nightly
version v20210216. This PR includes a patch to the tekton controller
config to enable support for custom tasks integration in pipeline.
review them:
/kind feature
=> Add unit tests CI for the plumbing repo

tekton/ci-workspace/community/template.yaml, tekton/mario-bot/mario-github-comment.yaml, tekton/mario-bot/mario-image-build-trigger.yaml
Triggers v0.12.0 changed the event UID form a short string to
a UUID. Do not use $(uid) anymore in resource names as it creates
invalid names.
review them:
/kind misc
=> Stop using $(uid) for resource names in templates

tekton/cronjobs/bases/release/trigger-with-uuid.yaml
Fix the branch selection in cronjobs by:
- checking for main before master
- make the regex more robust by adding a $ to avoid partial matches
review them:
/kind misc
=> Fix the branch selection in cronjobs

docs/dogfooding.md, tekton/cronjobs/dogfooding/cleanup/bastion-p-nightly/README.md, tekton/cronjobs/dogfooding/cleanup/bastion-p-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/cleanup/bastion-p-nightly/kustomization.yaml, tekton/cronjobs/dogfooding/cleanup/kustomization.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/kustomization.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/pipeline-nightly-test/README.md, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/pipeline-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/pipeline-nightly-test/kustomization.yaml, tekton/resources/nightly-tests/bastion-p/cleanup_tekton.yaml, tekton/resources/nightly-tests/bastion-p/deploy_tekton_component.yaml, tekton/resources/nightly-tests/bastion-p/kustomization.yaml, tekton/resources/nightly-tests/bastion-p/test_tekton_component.yaml, tekton/resources/nightly-tests/eventlistener.yaml, tekton/resources/nightly-tests/kustomization.yaml, tekton/resources/nightly-tests/pipeline-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/serviceaccount.yaml
This PR is similar to #663. It adds `cronjob`, `tasks` & `service account` to run nightly pipeline tests on remote `ppc64le` cluster.
- Add secret & resource details to docs.
- Update nightly test EventListener to include ppc64le architecture.
- Add TriggerTemplate for nightly pipeline tests on ppc64le.
- Add cronjob to trigger nightly ppc64le pipeline tests.
- Add tasks to deploy, test & clean pipeline components on remote ppc64le cluster.
- Add service account for triggering nightly tests.
The job configurations expect following resources to be present on dogfooding 
- `ppc64le-kubeconfig` used to access ppc64le remote k8 cluster
- `registry-credentials` used to access registry on remote machine
- `registry-certificate` self-signed certificate for registry on remote machine
- …
=> Add pipelines nightly tests for ppc64le architecture

tekton/cronjobs/README.md, tekton/resources/cd/serviceaccount.yaml
Several cleanup pipelineruns fail to execute, because there are no permissions to access resources in corresponding namespaces. Addition of the RoleBindngs to allow access to the pipelineruns and taskruns in the `bastion-z`, `tekton-ci` and `tekton-nightly` namespaces will fix this problem.
/kind bug
review them:
=> Add corresponding RoleBindings for cleanup pipelineruns

tekton/ci/jobs/tekton-catlin-lint.yaml
git diff step in Catlin Task was detecting the changed files which
catlin was unable to find.
modified the script which will check for the deleted tasks and if any is task
being removed from the catalog then it will not be tested by catlin.
review them:
=> Fix Catlin to skip deleted tasks

tekton/resources/cd/kustomization.yaml
Currently the "cleanup old prs/trs" pipeline fails when target namespace is not default one, because there are no permissions to do actions with prs/trs in non-default namespace. The reason is that kustomize applies default namespace value to all resources in the tekton/resources/cd folder and overwrites desired(non-default) namespaces for corresponding RoleBindings which grant the permissions.
Suggested fix is
- set default namespace value to all resources except RoleBindings and ClusterRoleBindings.
- set default namespace only for subject of RoleBindings and ClusterRoleBindings.
/kind bug
review them:
for more …
=> Fix namespace specification with kustomize for cleanup RoleBindings

bots/mariobot/README.md, tekton/ci-workspace/shared/eventlistener.yaml, tekton/ci/eventlistener.yaml, tekton/mario-bot/mario-image-build-trigger.yaml
The legacy (?) load balancing infrastructure in Google cloud required
services to be use NodePort for the healthcheck to be able to work.
With NEGs and cloud-native load balancing cluster IP services are
required instead:
- https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing
- https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#health_checks
Removing the service type from the event listener, so that the default
ClusterIP is used.
review them:
/kind misc
/cc @dibyom @vdemeester
=> Switch Event Listener sinks to ClusterIP

prow/config.yaml
DOCKER_IN_DOCKER_ENABLED is duplicated due to the dind preset applied
to the job. Remove the env variable as it is inherited by the preset,
otherwise it is duplicated and it seems prow fails…
/cc @afrittoli @wlynch @ImJasonH 
review them:
=> Fix duplicate DIND env var due to preset 🧙

tekton/resources/nightly-tests/bastion-z/deploy_tekton_pipeline.yaml, tekton/resources/nightly-tests/bastion-z/deploy_tekton_triggers.yaml, tekton/resources/nightly-tests/bastion-z/kustomization.yaml, tekton/resources/nightly-tests/cli-deploy-test-s390x-template.yaml, tekton/resources/nightly-tests/pipeline-deploy-test-s390x-template.yaml, tekton/resources/nightly-tests/triggers-deploy-test-s390x-template.yaml
Now triggers installation from source code cannot be unified with pipeline installation. 
Instead 2 separate tasks for s390x test pipelines are created.
/kind misc
review them:
=> Have separate installation task for triggers for s390x tests

tekton/cronjobs/dogfooding/nightly-tests/ppc64le/cli-nightly-test/README.md, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/cli-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/cli-nightly-test/kustomization.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/kustomization.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/operator-nightly-test/README.md, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/operator-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/operator-nightly-test/kustomization.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/triggers-nightly-test/README.md, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/triggers-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/triggers-nightly-test/kustomization.yaml, tekton/resources/nightly-tests/bastion-p/cleanup_tekton.yaml, tekton/resources/nightly-tests/bastion-p/deploy_tekton_pipeline.yaml, tekton/resources/nightly-tests/bastion-p/deploy_tekton_triggers.yaml, tekton/resources/nightly-tests/bastion-p/kustomization.yaml, tekton/resources/nightly-tests/bastion-p/test_tekton_cli.yaml, tekton/resources/nightly-tests/cli-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/eventlistener.yaml, tekton/resources/nightly-tests/kustomization.yaml, tekton/resources/nightly-tests/operator-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/triggers-deploy-test-ppc64le-template.yaml
This PR adds nightly e2e tests on `ppc64le` architecture for `cli`, `triggers` & `operator`. Nightly `pipeline` tests on ppc64le hardware is already enabled via #762.
/kind feature
/cc @afrittoli
review them:
=> Add nightly tests for cli, triggers & operator on ppc64le architecture

tekton/ci/jobs/tekton-catlin-lint.yaml, tekton/ci/templates/catalog-template.yaml
As of now catlin is running on PRs of catalog and validate them as per
TEP-0003 but there are some warnings which are produced by catlin which
maybe left un-noticed by the PR author as catlin check doesn't fails.
This PR adds a script which will search whether catlin has produced any
warning or error and if found will post the output as comment on the PR.
/kind feature
review them:
=> Catlin: Report logs back to the PR after execution

tekton/cronjobs/dogfooding/nightly-tests/s390x/pipeline-nightly-test/cronjob.yaml
Change time when nightly s390x pipeline test suites are running to use less loaded time of s390x server and avoid Docker pull rate limit errors.
/kind misc
review them:
=> Move s390x pipeline test cronjob to another time

tekton/ci-workspace/README.md, tekton/resources/cd/eventlistener.yaml
Condition tasks are used to evaluate whether a CI job should be
executed or not. Cloud events generated before a CI task is
executed should be ignored, which is achieved today by using
a specific annotation on the Task "ci.tekton.dev/condition" and
filtering out matching events in the trigger using a CEL filter.
However, because of https://github.com/tektoncd/pipeline/issues/3864,
the annotations are not immediately available in the TaskRun,
which causes the filtering to fail, CI jobs to be marked as started
in GitHub but never completed if the condition was false and thus
no CI job is executed.
Add an extra check based on the name. If the task name starts with
"check-", the event is ignored and no github update is sent.
These …
=> Fix handling of condition tasks in CI

tekton/ci-workspace/README.md, tekton/ci/README.md, tekton/ci/jobs/tasks.yaml, tekton/ci/jobs/tekton-kind-label.yaml
In a previous PR, we added a CEL filter to the tekton-events sink
to exclude events related to taskruns with "-check-" in the name,
to allow filtering out tasks associated to conditions, which should
not trigger github updates.
The new filter however matches the name of the "check-kind-label"
task, which is a CI job and should trigger github updates instead.
Renaming the task to "kind-label" instead, to avoid the conflict
and restore GitHub notifications for the task.
review them:
/kind bug
/cc @jerop @bobcatfish
=> Rename check-kind-label to kind-label

catlin/Dockerfile, tekton/ci/jobs/tekton-catlin-lint.yaml
We are adding the output of the command :
```
catlint lint script
```
to the existing job that would do `catlin validate` on catalog tasks.
We add linters for shells and python.
The output for example when you have your task with a python script
would be something like this :
```
************* Module catlin-script-linter178031378
github-create-deployment-create-deployment:17:0: W0125: Using a conditional statement with a constant value (using-constant-test)
github-create-deployment-create-deployment:36:0: E1111: Assigning result of a function call, where the function has no return (assignment-from-no-return)
-----------------------------------
Your code has been rated at 7.60/10
```
review them:
_See [the …
=> Add script linting to catlin catalog check job

tekton/ci/jobs/tekton-catlin-lint.yaml
Fix catlin script lint job by only launching on yaml files and only
showing the headers if there is actual errors set
Signed-off-by: Chmouel Boudjnah <chmouel@redhat.com>
review them:
=> Fix catlin script lint job

tekton/cronjobs/dogfooding/nightly-tests/s390x/dashboard-nightly-test/README.md, tekton/cronjobs/dogfooding/nightly-tests/s390x/dashboard-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/s390x/dashboard-nightly-test/kustomization.yaml, tekton/cronjobs/dogfooding/nightly-tests/s390x/kustomization.yaml, tekton/resources/nightly-tests/README.md, tekton/resources/nightly-tests/dashboard-deploy-test-s390x-template.yaml, tekton/resources/nightly-tests/eventlistener.yaml, tekton/resources/nightly-tests/kustomization.yaml
- add corresponding cronjob to trigger s390x tekton dashboard test
- add template to run s390x operator test pipeline
- git clone dashbooard repo
- k8s cluster installation
- e2e dashboard test(backend and frontend)
- k8s cluster removal
/kind misc
review them:
=> Add pipeline to run s390x dashboard tests

tekton/resources/cd/serviceaccount.yaml
`cleanup-pr-tr` task is currently failing to remove pr/tr from bastion-p namespace due to missing permissions. The solution for this is similar to one described in #767
/kind bug
review them:
=> Add RoleBinding to cleanup pr/tr from bastion-p namespace

docs/README.md, tekton/ci-workspace/jobs/kustomization.yaml, tekton/ci-workspace/jobs/tekton-docs-reviews.yaml, tekton/ci-workspace/shared/template.yaml, tekton/ci-workspace/shared/trigger.yaml
Add a pipeline that runs on all repos with the webhook installed.
This pipeline requests the @tektoncd/docs.reviewers team as reviewer
if files changed in the PR match "(^docs\/.*|^(?!vendor\/)(?!thirdparty\/).*\.(md|rst)$)"
Note that even if the team is only added to the list of reviewers if
it is a collaborator of the repo, a notification email is sent to
the team regardless.
Update the DNS docs in the main README
review them:
/kind feature
=> Add a pipeline to request doc reviewers

tekton/resources/nightly-tests/dashboard-deploy-test-s390x-template.yaml
2Gi space is enough and test fails with "no space left on device" error. 
/kind bug
review them:
=> Add more space to s390x dashboard integration test

robocat/cadmin/200-rbac.yaml
Adds `patch` privilege to tekton-deployer to patch namespace `tekton-pipelines` on robocat cluster.
Taskruns of Task `install-tekton-release` are failing as `tektin-deployer` serviceaccount
doesn't have the privillege to patch `tekton-pipelines` namespace.
ref: https://dashboard.dogfooding.tekton.dev/#/namespaces/default/taskruns/deploy-pipeline-release-robocat-c5s7m?step=deploy-tekton-project
review them:
=> Add 'patch' privillege to tekton-deployer sa

robocat/cadmin/200-rbac.yaml, scripts/README.md, scripts/deploy-release.sh, tekton/cronjobs/bases/tekton-service/trigger-resource-cd.yaml, tekton/resources/cd/bindings.yaml, tekton/resources/cd/tekton-template.yaml, tekton/resources/release/base/install_tekton_release.yaml
Tekton triggers installation is now split into two files. The
second one can only be installed once CRDs are established.
To support this, split the tekton install task in three steps:
- install the main release file with overlays, like before
- wait for pods ready and CRD established that match the project
being installed
- install the post release file, in any
In the script, set the default post file to "interceptors.yaml"
for triggers, to keep the script easy to use.
review them:
/kind misc
=> Add post release file to Tekton install task and script

tekton/ci-workspace/infra/0001_rbac.yaml, tekton/ci/0001_rbac.yaml, tekton/resources/cd/serviceaccount.yaml, tekton/resources/nightly-release/serviceaccount.yaml, tekton/resources/nightly-tests/serviceaccount.yaml
The tetkoncd service account is used to run the tektoncd and tekton
events event listener, and it requires access to read the
clusterinterceptors to operate.
Same goes for the tekton-ci-listener and tekton-ci-workspace-listener
service accounts, that serve the event listeners for the two
Tekton based CI webhooks.
review them:
/kind misc
=> Add the clusterinterceptors to clusterroles

tekton/cd/pipeline/overlays/dogfooding/kustomization.yaml
Feature flags are configured for pipeline in the dogfooding overlay,
but the config map YAML is not included in kustomize.yaml, so the
changes are not applied. Add feature-flags.yaml to kustomize so that
custom tasks are enabled.
review them:
/kind misc
=> Add feature flags config to pipeline overlay

tekton/resources/cd/eventlistener.yaml
Replicas has been deprecated in event listeners starting v0.13.0.
Moving to the new syntax, before support is removed in the next
release.
review them:
/kind misc
=> Stop using depreacted replicas in event listeners

scripts/e2e-tests.sh
1.19 removes support for basic auth, which breaks our current e2e tests
- https://cloud.google.com/kubernetes-engine/docs/release-notes#119_ga.
This flag pins the cluster version to 1.18. See
https://cloud.google.com/sdk/gcloud/reference/container/clusters/create#--cluster-version
for details.
Long term, we're looking to remove the basic auth with
https://github.com/tektoncd/plumbing/pull/811, but this is an easy quick
fix just in case.
review them:
=> e2e-test.sh: Pin cluster version to GKE 1.18.

scripts/e2e-tests.sh, scripts/library.sh
This change pins the cluster version that will be picked up by kubetest via k8s_extract. Currently, after #818, kubetest will pick up two different --cluster-version flags, and only take the second.
review them:
=> Pin GKE cluster version for e2e tests

scripts/e2e-tests.sh, scripts/library.sh
See
https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication#legacy-auth
for more details for what this flag does.
This flag, and the related code to uses it, shouldn't be needed - the Prow SA
should have sufficient permissions via IAM
(https://cloud.google.com/kubernetes-engine/docs/how-to/iam#predefined)
to interact with the created cluster.
Additionally, this feature is going away in GKE 1.19, so we're better
off disabling it ASAP in preparation.
review them:
for more …
=> Remove --enable-basic-auth from e2e test clusters.

tekton/ci/interceptors/github/README.md, tekton/ci/interceptors/github/config/service.yaml, tekton/ci/interceptors/github/main.go, tekton/ci/interceptors/github/pkg/github/server.go
This makes several small changes to the interceptor:
- Standardizes naming on `tekton-triggers-interceptor-github`, and
component as `tekton-interceptors`
- Adds webhook secret volume in deployment config.
- Adds documentation for generating the secret.
- Fixes webhook validation due to trailing `\n` in the read secret.
review them:
=> GitHub Simple Interceptor: Standardize naming, fix webhook validation.

catlin/Dockerfile, pipelinerun-logs/Dockerfile, tekton/images/coverage/Dockerfile, tekton/images/ko-gcloud/Dockerfile, tekton/images/ko/Dockerfile, tekton/images/kubectl/Dockerfile, tekton/images/test-runner/Dockerfile
right now CI is failing on https://github.com/tektoncd/chains/pull/70 because it depends on the `embed` package, which should be fixed with the latest version of golang!
=> Bump go version to 1.16.3

prow/config.yaml
I was looking at some PRs and issues today that have been rotten for a
very long time and I was trying to figure out why they weren't getting
automatically closed.
I think that that query was incorrect and was looking for old issues that
were labelled with BOTH stale and rotten, but what we actually want is
issues that are labelled with rotten only, so I think this will do the
trick!
And then I guess we'll see a flurry of automatic closures?? 😅
review them:
=> Fix job that is supposed to close rotten issues/prs 🥀

tekton/ci-workspace/catalog/kustomization.yaml, tekton/ci-workspace/catalog/template.yaml, tekton/ci-workspace/catalog/trigger.yaml, tekton/ci-workspace/jobs/kustomization.yaml, tekton/ci-workspace/jobs/tekton-catalog-catlin-lint.yaml, tekton/ci-workspace/kustomization.yaml, tekton/ci-workspace/shared/common-tasks.yaml
- Catlin Task was not able to perform lint check on the script present
inside the Task. This commit removes extra if condition and directly
performs the `catlin lint script` command.
- Catlin Pipeline was running the finally task ie github-add-comment
when it was not required so adding a Task check-name-matches and
replacing it with condition and guarding other tasks in the pipeline
using when conditions.
- The task `check-name-matches` in `ci-workspace` used to produce the result `passed` even if the name doesn't
matches so re-arranged the condition so that proper result can be
produced.
review them: …
=> Fix check-name-matches Task and add Catlin to `ci-workspace` directory

gubernator/config.yaml, prow/config.yaml
Prior to this commit the pipeline project ran two iterations of its e2e
tests as part of a single prow job: first for "stable" feature gate and then for "alpha". This doubled
the running time of the `pull-tekton-pipeline-integration-tests` job.
This commit adds a new job specifically for running integration tests under
"alpha" feature gate. This allows the two test runs to occur concurrently and should
hopefully reduce the iteration time on PRs. When the new alpha prow job is run
an environment variable is added which  pipelines' `test/e2e-tests.sh` file
will recognize and use to set the feature gate.
review them: …
=> Run pipeline's alpha tests as separate prow job

tekton/cd/results/base/kustomization.yaml, tekton/cd/results/overlays/ingress.yaml
This should allow results to have its own DNS name + TLS for serving
results externally.
Largely based off of https://github.com/tektoncd/plumbing/blob/main/tekton/cd/dashboard/overlays/dogfooding/ingress.yaml
I'm not 100% confident that this is correct, so would definitely appreciate a thorough look at this PR. 🙏 
review them:
=> Add ingress overlay for results.

robocat/certificates/clusterissuer.yaml, tekton/cronjobs/dogfooding/manifests/kustomization.yaml, tekton/cronjobs/robocat/helm/cert-manager-nightly/cronjob.yaml, tekton/cronjobs/robocat/helm/cert-manager-nightly/kustomization.yaml
Update to the latest version of cert-manager (1.3).
The latest chart supports deploying the CRDs, so enable that
and disable the pre-deploy CRD deployment.
Add the cronjobs that deploys the robocat cronjobs to
kustomize so that the cronjob definition is updated nightly.
review them:
/kind misc
=> Update cert-manager helm deployment to robocat

scripts/presubmit-tests.sh
If a command is already quoted, things like `foo="$(cat \"foo.txt\")"` are interpreted as read file `"foo.txt"`, which does not exist and causes failures such as:
```
cat: '"/tmp/tmp.5KnFwQPJrS/changed_files"': No such file or directory
==========================================='========================================
==== NO CHANGED FILES REPORTED, ASSUMING IT'S AN ERROR AND RUNNING TESTS ANYWAY ====
==========================================='========================================
```
See
https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_experimental/731/pull-tekton-experimental-unit-tests/1395436805712515072/
for an example.
This is a partial rollback of https://github.com/tektoncd/plumbing/commit/657b8cc432691ef28c89fbc8532c4a1e7144a3e7
These are the …
=> presubmit-tests.sh: Remove quote escaping from already quoted commands.

prow/config.yaml
https://github.com/tektoncd/experimental/issues/750
webhooks-extension has been deprecated for over 9 months and is now
being deleted. Remove the postsubmit job on the experimental repo
that was used to publish the webhooks-extension image as it's no
longer required.
review them:
=> Remove postsubmit job for the webhooks-extension

tekton/cd/results/README.md, tekton/cd/results/base/kustomization.yaml, tekton/cd/results/overlays/dogfooding/bec.yaml, tekton/cd/results/overlays/dogfooding/kustomization.yaml, tekton/cd/results/overlays/dogfooding/service.yaml
This adds GCP annotions to configure the GCP load balancer for use with gRPC +
a BackendConfig for configuring the load balancer health checks so that
traffic can be successfully routed to the backend.
The BackendConfig uses the prometheus port as a quick and dirty
mechanism to check whether the pod is alive. This can be replaced with a
more comprehensive health check later if needed.
https://medium.com/google-cloud/gke-grpc-ingress-loadbalancing-4b9cdbc09758
was used as a model for many of these configuration settings.
review them:
=> Results API: Add GCP LB specific annotations + resources.

tekton/resources/nightly-release/overlays/dashboard/template.yaml
I noticed that the dashboard nightly has timed out at 1h a few times now.
review them:
=> Increase Dashboard nightly timeout to 1h30m

tekton/ci/jobs/tasks.yaml
The `kind-label` task is used in the check pr kind label CI job.
It used to rely on the HOME variable being set by Tekton.
From release v0.24.x the default changed and now the HOME variable
is not set anymore by Tekton, so fixing the task to work with
the new default.
review them:
/kind bug
=> Fix the check-pr-kind CI job by restoring HOME

tekton/resources/nightly-tests/bastion-p/deploy_tekton_pipeline.yaml, tekton/resources/nightly-tests/bastion-p/deploy_tekton_triggers.yaml, tekton/resources/nightly-tests/operator-deploy-test-ppc64le-template.yaml
Signed-off-by: Siddhesh Ghadi <Siddhesh.Ghadi@ibm.com>
ppc64le nightly tests mount docker credentials secret to `/tekon/home/.docker`. With latest pipeline version, this fails due to change in default `disable-home-env-overwrite`. Changed mount location to `/root/.docker`.
review them:
/kind bug
cc: @afrittoli
=> Change mount location for ppc64le nightly tests

tekton/ci/interceptors/add-pr-body/tekton/publish.yaml, tekton/ci/interceptors/add-team-members/tekton/publish.yaml
Before Tekton Pipelines v0.24.x, $HOME and workDir were implicitly set,
which rendered the cp command redundant and hid the issue.
Partially fixes #856
review them:
/kind bug
=> Fix the cp command in the release publish task

tekton/ci/interceptors/github/examples/trigger.yaml, tekton/resources/org-permissions/peribolos-trigger.yaml
Since triggers v0.14.x specs.serviceType is not supported anynore.
Use spec.resources.kubernetesResources.serviceType instead.
This fixes CD of resources which is currently blocked because of
the unsupported spec.
review them:
/kind misc
=> Stop using spec.serviceType in event listeners

catlin/pkg/validator/task_validator.go, catlin/pkg/validator/task_validator_test.go
According to [CIS Benchmarks][1]:
> 5.4.1 Prefer using secrets as files over secrets as environment
> variables
We should discourage the usage of secretKeyRef in step env and thus this
proposal to report warning.
See [tektoncd/catalog#717][2] as well.
[1]: https://cloud.google.com/kubernetes-engine/docs/concepts/cis-benchmarks
[2]: https://github.com/tektoncd/catalog/issues/717
Catlin: Generate warning when using secretKeyRef in env
review them:
=> Catlin: Generate warning when using secretKeyRef in env

docs/dogfooding.md, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/dashboard-nightly-test/README.md, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/dashboard-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/dashboard-nightly-test/kustomization.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/kustomization.yaml, tekton/resources/nightly-tests/bastion-p/k8s_cluster_setup.yaml, tekton/resources/nightly-tests/bastion-p/kustomization.yaml, tekton/resources/nightly-tests/dashboard-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/eventlistener.yaml, tekton/resources/nightly-tests/kustomization.yaml
- Add ssh secret details to docs.
- Update nightly-test EventListener to include dashboard test for ppc64le architecture.
- Add TriggerTemplate for nightly dashboard test on ppc64le.
- Add cronjob to trigger nightly ppc64le dashboard test.
- Add tasks to create/delete ppc64le k8s cluster on remote hardware.
Signed-off-by: Siddhesh Ghadi <Siddhesh.Ghadi@ibm.com>
review them:
=> Add nightly e2e dashboard test for ppc64le

tekton/resources/nightly-release/overlays/dashboard/template.yaml
Revert to the older PipelineRun `timeout` field for the Dashboard
nightly release until we have the new Dashboard release pipeline or
dogfooding is updated to Pipelines 0.25 or later with support for the
new `timeouts` field.
review them:
=> Fix Dashboard nightly builds

catlin/README.md, catlin/pkg/consts/consts.go, catlin/pkg/validator/content_validator.go, catlin/pkg/validator/validate_test.go
- Catlin shows recommendation to use platforms annotation
- Catlin checks the format of platforms specification, expecting to get "OS/ARCH" format
/kind feature
review them:
=> Add platforms annotation verification to Catlin

tekton/resources/release/base/github_release.yaml
Fix https://github.com/tektoncd/triggers/issues/1145
From release v0.24.x the default changed and now the HOME variable
is not set anymore by Tekton, so fixing the task to work with
the new default.
review them:
=> Add HOME env to create-release-draft step template

tekton/ci-workspace/community/template.yaml, tekton/ci-workspace/jobs/kustomization.yaml, tekton/ci-workspace/jobs/tekton-org-validation.yaml
Add a pull-community-org-validation job on tektoncd/community
repository that will run peribolos in *dry-run* (not actually updating
the github org) to validate that the file is ok.
Should help keeping the file correct overtime 😛 
/cc @afrittoli @sbwsg @nikhil-thomas 
review them:
=> community#418: Add org.yaml peribolos validation 🧙

tekton/ci-workspace/jobs/tekton-org-validation.yaml
CI job failing  with below error 
```
invalid input resources for task peribolos-dry-run: Task's declared required resources are missing from the TaskRun: [repo]
```
Updated `peribolos-dry-run` task to use workspaces instead of input resources.
Verified by updating `peribolos-dry-run` task on dogfooding cluster 
https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/pull-community-org-validation-9jxvj?pipelineTask=clone-repo&step=clone
review them:
=> Update peribolos-dry-run task to use workspaces

tekton/resources/nightly-tests/bastion-p/test_tekton_cli.yaml, tekton/resources/nightly-tests/bastion-z/test_tekton_cli.yaml
With the recent [commit](https://github.com/tektoncd/cli/pull/1419) to cli test code, SYSTEM_NAMESPACE env variable
is expected to be set. The fix is provided for Z and Power setups.
/kind misc
review them:
=> Add SYSTEM_NAMESPACE env variable to fix cli tests for Z and Power

tekton/images/ko-gcloud/Dockerfile
An `ARG` declared before a `FROM` is outside of a build stage, so it can’t be
used in any instruction after a `FROM`. To use the default value of an `ARG`
declared before the first `FROM` use an `ARG` instruction without a value
inside of a build stage.
https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
This meant that we were failing to download and extract the go tarball as the GO_VERSION
was unset:
```
INFO[0731] RUN tar -C /usr/local -xzf go${GO_VERSION}.tar.gz 
INFO[0731] cmd: /bin/sh                                 
INFO[0731] args: [-c tar -C /usr/local -xzf go${GO_VERSION}.tar.gz] 
tar: invalid magic
tar: short read
```
review them: …
=> Fix ko-gcloud build

tekton/ci/README.md, tekton/ci/jobs/conditions.yaml, tekton/ci/jobs/tasks.yaml, tekton/ci/jobs/tekton-yamllint.yaml, tekton/ci/templates/plumbing-template.yaml
As part of TEP-0074 (https://github.com/tektoncd/community/pull/480) I'm
trying to update some of the plumbing use of PipelineResources to not
use them anymore.
I picked this yamllint pipeline as a simple example; I thought I'd need
the experimental pipeline to taskrun controller, but in this case
conditions are in the mix - when expressions are the way to update those
but they aren't supported in the pipeline to taskrun controller yet.
Also the original version would run 3 separate pods, and each would
separately clone the git resource. So in this updated version, even
though it will run 4 separate pods, it will only clone the git repo once
which seems like an optimization. And once we support when expressions
in the pipeline to taskrun controller (seems like it could be easy
enough? …
=> Update yamllint to not use resources 🤩

tekton/cd/results/base/kustomization.yaml, tekton/cd/results/overlays/dogfooding/ingress.yaml
Upgrades Results to v0.3.0 to test new results release candidate before
we tag + publish it.
Adds option to ingress to allow a temp certificate to be provision to
to let cert-manager play nice with the GKE Ingress loadbalancer.
See https://cert-manager.io/docs/faq/acme/#http01-troubleshooting for
more details.
(hopefully) Fixes #880 
review them:
=> Bump Results to v0.3.0, enable temp certs for cert-manager.

tekton/images/test-runner/Dockerfile
This updates the version of golangci-lint installed in our presubmit images.
This accompanies https://github.com/tektoncd/pipeline/pull/4206, which should make
tests pass for tektoncd/pipeline with this update.
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>
review them:
=> Bump golangci-lint to v1.42.0.

tekton/cd/results/overlays/dogfooding/kustomization.yaml, tekton/cd/results/overlays/dogfooding/watcher.yaml
Since the API service is configured with the SSL cert for
`results.dogfooding.tekton.dev`, the watcher is unable to connect to the
API via the internal service hostname. This changes the watcher to use
the external hostname so that the SSL cert validation succeeds and we
can successfully connect.
We cannot terminate TLS at the ingress, since gRPC requires encrypted
connections when used with credentials. A potential alternative would be to set
up a different SSL cert for the internal host, but I'm not sure
that gives us significant added benefit over using the external hostname.
Fixes https://github.com/tektoncd/results/issues/131
review them:
- [n/a] Includes …
=> results dogfooding: Use external DNS hostname in watcher.

bots/buildcaptain/README.md
I used the adjustpermissions.py script to give @AlanGreene access to our
clusters for creating Dashboards releases.
(When we re-create these projects
(https://github.com/tektoncd/plumbing/issues/865) we might revisit how
we give out these permissions and make it more reliable and less just
based on me running a script XD)
I also added reasons to other non-build-captain folks who have access.
review them:
=> Record that Alan Greene has access to our clusters 📝

tekton/resources/images/docker-multi-arch-template.yaml, tekton/resources/images/eventlistener.yaml, tekton/resources/images/ko-multi-arch-template.yaml, tekton/resources/images/kustomization.yaml
At this moment `docker buildx` is used to build multi-arch images. In some cases `ko` tool can better fit to the multi-arch building process.
Proposed extension adds new template to run multi-arch image build using `ko` tool, when buildType parameter in payload is equal to `ko`. Docker build is done when buildType parameter us equal to `docker`.
If `platform`s parameter is not specified at all, standard single image build for `linux/amd64` is done.
/kind feature
review them:
=> Add option to build multi-arch images using ko tool

tekton/cd/results/overlays/dogfooding/kustomization.yaml, tekton/cd/results/overlays/dogfooding/rbac.yaml
While we could grant access to individual human users, we're not 100%
confident this is a good idea yet (since we'd need users to pass a valid
GCP credential). This is a workaround to let users
who have access to the cluster to get the token for this user, which
is scoped to have minimal RO permissions for result resources.
review them:
=> Add tekton-results-viewer service account.

tekton/cronjobs/README.md, tekton/cronjobs/bases/image-build/trigger-image-build.yaml, tekton/cronjobs/dogfooding/images/alpine-git-nonroot-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/go-rest-api-test-nightly/README.md, tekton/cronjobs/dogfooding/images/go-rest-api-test-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/go-rest-api-test-nightly/kustomization.yaml, tekton/cronjobs/dogfooding/images/kustomization.yaml, tekton/cronjobs/dogfooding/images/skopeo-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/teps-community-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/tkn-nightly/cronjob.yaml
`go-rest-api-test` image is used in many Tekton catalog tests. To be able to run the same tests for different architectures, the image should be multi-arch one.
To build the multi-arch image new nightly cronjob is introduced.
Also 2 values for `build type` parameter of multi-arch image build are introduced - `docker` and `ko` to specify which tool to use for the build. From eventlistener side both types are already supported.
/kind feature
review them:
=> Build multi-arch go-rest-api-test image

tekton/images/ko-gcloud/Dockerfile, tekton/images/ko/Dockerfile, tekton/images/test-runner/Dockerfile
v0.9.2 fixes a regression introduced in v0.9.1 where the built
entrypoint binary would not be correctly added to PATH. Users who
invoked a ko-built container with cmd:my-app would see failures, while
users who invoked with cmd:/ko-app/my-app would not. This is fixed in
v0.9.2.
review them:
=> Update ko to v0.9.2

label_sync/labels.yaml
Set the description for the label to 2021 instead of 2020.
review them:
/kind misc
=> Update the hacktoberfest label to 2021

tekton/cd/dashboard/overlays/dogfooding/extensions.yaml, tekton/cd/dashboard/overlays/dogfooding/kustomization.yaml
Use the dashboard extensions capability to display cronjobs available
in the dogfooding cluster via the dashboard.
review them:
/kind misc
=> Add cronjobs to the dashboard

tekton/images/test-runner/Dockerfile
Pipeline's TestYaml integration test uses `ko create` to deploy and run
yamls. There was a small bug in `ko create` that lead to it running `kubectl
apply` instead of `kubectl create` behind the scenes and in turn this
lead to TestYaml failing.
This commit pins `ko` to 0.8.3 in the `test-runner` image to get integration
moving again and we can pin to the new version of `ko` when it's released with
the fix.
Edit:
Here's an example PR with failed integration: https://github.com/tektoncd/pipeline/pull/4345
Here's the fix: https://github.com/google/ko/pull/494
review them:
=> Pin ko to 0.8.3

tekton/resources/nightly-release/overlays/dashboard/template.yaml
The Dashboard build requires more storage than I realised. Increase
the storage request as a temporary measure while we work on reducing
this on the Dashboard side.
Example of failure with current config: https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns/dashboard-release-nightly-gdmn4?pipelineTask=build&step=build-static
Passing build with the increased storage request in place: https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns/dashboard-release-nightly-6b7cs?pipelineTask=report-bucket&step=create-results
review them:
=> Update Dashboard nightly release storage request

tekton/ci-workspace/jobs/tekton-image-build.yaml
The param that TaskLoop attempts to iterate on when releasing new plumbing
images is named context but the kaniko4ci task exposes a param named CONTEXT.
It looks like this was a source of failure during last nights plumbing-image-build
(PipelineRun [plumbing-image-build-jcqhr](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/plumbing-image-build-jcqhr?pipelineTask=clone-repo&step=clone) in dogfooding).
This commit updates the param TaskLoop is looking for from context to CONTEXT.
review them:
=> Match iterator TaskLoop variable to match kaniko param

tekton/ci-workspace/catalog/template.yaml, tekton/ci-workspace/catalog/trigger.yaml, tekton/ci-workspace/jobs/tekton-catalog-diff-task.yaml
This job will run in the catalog repo and compare the previous version of tasks with the new one and post a
diff to the PR thread.
It incorporates the script of @chmouel https://github.com/tektoncd/catalog/blob/main/hack/diff-task-version for a very large part.
Closes #704 
review them:
=> Add diff-task job

tekton/resources/nightly-tests/operator-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/operator-deploy-test-s390x-template.yaml
Recently the env variable to skip cluster installation for Tekton Operator e2e tests was changed. Skip is required for Power and Z nightly tests. 
The fix does renaming of the env variable to the current correct one.
/kind misc
review them:
=> Fix operator nightly tests for s390x and ppc64le

tekton/resources/cd/folder-template.yaml
The deployment template fails if there is a Warning in the log file.
Fixes: #932
/kind bug
review them:
=> Ignore warnings when deploying resources

tekton/ci-workspace/jobs/e2e-kind.yaml, tekton/ci-workspace/jobs/kustomization.yaml, tekton/ci-workspace/kustomization.yaml, tekton/ci-workspace/pipeline/kustomization.yaml, tekton/ci-workspace/pipeline/template.yaml, tekton/ci-workspace/pipeline/trigger.yaml, tekton/ci/README.md, tekton/cronjobs/dogfooding/images/kind-e2e-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/kind-e2e-nightly/kustomization.yaml, tekton/cronjobs/dogfooding/images/kustomization.yaml, tekton/images/kind-e2e/Dockerfile, tekton/images/kind-e2e/setup-kind.sh
Add a kind-e2e container image with an embedded setup-kind script.
The kind-e2e image includes libraries need to run E2E tests.
Add a cronjob to build the image nightly.
Add a task which runs dind in a sidecar and which triggers
the setup-kind and can run a script on top of the kind cluster.
Setup a generic pipeline which clones a repo and runs the kind
tasks. The repo is used to source the test job.
Add a CI job the pipeline repo that uses the e2e-kind pipeline.
review them:
/kind feature
=> Setup e2e tests on kind

tekton/resources/cd/eventlistener.yaml
The tekton-events event listeners filters out git-clone tasks
at the beginning of CI jobs as no notifications should be fired
for those.
The latest tekton release dropped the `-<random>` part suffix from
resource names which causes the CEL filters for git-clone tasks
to break. Remove the trailing "-" should fix the issue.
review them:
/kind misc
=> Detect git clone tasks in the tekton-events el

adjustpermissions.py
The only level of access currently grantable by the permissions
script includes sensitive permissions like storage admin.
This commit provides a default option for a lower level of access
to the dogfooding cluster.
Please note: I have not audited all the permissions provided by
the viewer role. While it doesn't include access to contents of secrets,
it does include a large number of other permissions. This is simply
meant as a safer default option.
Closes #920.
review them:
/kind misc
=> Add GCP Viewer role to adjustpermissions.py

tekton/cd/pipeline/overlays/dogfooding/feature-flags.yaml, tekton/cd/triggers/overlays/dogfooding/feature-flags.yaml, tekton/cd/triggers/overlays/dogfooding/kustomization.yaml
Enable alpha features in pipeline and triggers.
OCI bundles and custom tasks are already enabled in pipeline. Replace
the individual settings with the global alpha setting.
For Triggers, alpha is required to dogfood TriggerGroups.
review them:
/kind misc
=> Use alpha features in pipeline and triggers

bots/mariobot/README.md, tekton/mario-bot/mario-github-comment.yaml, tekton/mario-bot/mario-image-build-trigger.yaml
PipelineResources are now deprecated, and most of them are replaced with Catalog Tasks.
This commit rewrites the Mario Bot to not use PipelineResources.
The resulting triggers and pipelines have been tested in the dogfooding cluster.
In a subsequent commit, Mario Bot can be used to dogfood the pipeline -> taskrun feature.
Closes #931.
Co-authored-by: Christie Wilson christiewilson@google.com @bobcatfish 
Co-authored-by: Dibyo Mukherjee dibyajyoti@google.com @dibyom 
review them:
/kind cleanup
=> Rewrite MarioBot to use Pipelines and Workspaces

tekton/cronjobs/dogfooding/configmaps/labels-sync-hourly/cronjob.yaml
The cronjob that deploys the labels for CI purposes deployes now
to the tekton-ci namespace, and it should use the default SA in
that namespace instead of that of the tektonci namespace.
review them:
/kind misc
=> Use the correct account to deploy labels to tekton-ci

docs/dogfooding.md, tekton/cd/pipeline/overlays/dogfooding/config-defaults.yaml
Knative eventing + Kafka broken is now available in dogfooding, and it's
used to transport cloudevents generated by Tekton pipelines to
consumers.
Document the installation process, the knative triggers used to get
messages to consumers and alter the tekton pipeline configuration to
send events to the broker.
review them:
/kind misc
=> Document the eventing setup in dogfooding

tekton/ci/pipeline/trigger.yaml, tekton/ci/plumbing/trigger.yaml, tekton/ci/shared/trigger.yaml, tekton/ci/website/trigger.yaml
After the migration away from the tektonci namespace, a couple more
issues are left:
- wrong event type in some triggers
- tektonci namespace for the add-pr-body interceptor
review them:
/kind bug
=> Fix a few more issues related to the removal of tektonci

tekton/ci/jobs/tekton-image-build.yaml
Add the /busybox/sh shebang to match what's available in the
kaniko debug image.
Use the --no-push flag since we are not publishing images in the CI
job anyways.
Fixes #934
review them:
/kind bug
=> Fix the image build CI job

tekton/cronjobs/dogfooding/nightly-tests/s390x/catalog-nightly-test/README.md, tekton/cronjobs/dogfooding/nightly-tests/s390x/catalog-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/s390x/catalog-nightly-test/kustomization.yaml, tekton/resources/nightly-tests/README.md, tekton/resources/nightly-tests/catalog-deploy-test-s390x-template.yaml, tekton/resources/nightly-tests/eventlistener.yaml, tekton/resources/nightly-tests/kustomization.yaml
- add corresponding cronjob to trigger s390x tekton catalog tests
- add template to run s390x catalog test pipeline
- git clone catalog repo
- k8s cluster installation
- e2e tests for tasks marked as runnable for linux/s390x
- k8s cluster removal
/kind feature
review them:
=> Add pipeline to run s390x catalog tests

tekton/cronjobs/dogfooding/nightly-tests/s390x/kustomization.yaml
In connection to https://github.com/tektoncd/plumbing/pull/959, the new catalog s390x nightly test should be added to kustomization config to be applied to Tekton dogfooding cluster.
/kind misc
review them:
=> Add catalog s390x nightly test cronjob to kustomization config

tekton/ci/README.md, tekton/ci/catalog/template.yaml, tekton/ci/catalog/trigger.yaml, tekton/ci/community/trigger.yaml, tekton/ci/pipeline/trigger.yaml, tekton/ci/plumbing/trigger.yaml, tekton/ci/shared/eventlistener.yaml, tekton/ci/shared/trigger.yaml, tekton/ci/website/trigger.yaml
TriggerGroups are a new alpha feature in Triggers that allow define
a set of interceptors that will be processed before Trigger resources
for a filtered group of Triggers.
All triggers in CI jobs deal with GitHub event so they share a large
surface of the interceptors. Using TriggerGroups makes it easier to
maintain the triggers for all projects.
The change is not only cosmetic though: interceptors like github,
cel, add-pr-body will be processed only once. The hash in the GitHub
event is going to be validated once. The PR definition will be pulled
from the GitHub API once (per trigger group) instead of once per
trigger.
This paves the way for further changes:
- add the add-team-member custom interceptor and logic so we only
run tests for authorised users
- add a trigger group to add …
=> Use TriggerGroups for CI Jobs 🥳

tekton/ci/shared/eventlistener.yaml
All trigger resources are still v1alpha1.
Migrating the CI event listener for now since it's required by
for trigger groups: https://github.com/tektoncd/plumbing/pull/956
/kind misc
review them:
=> Migrate CI event listener to v1beta1

tekton/ci/shared/eventlistener.yaml
When introducing trigger groups, the event listener secret name
for GitHub CI events was inadvertently changed. Restored the
correct one.
review them:
/kind misc
=> Fix github CI secret name

tekton/resources/ci/github-template.yaml
Change the name of the notification taskruns, from a generated
one to a fixed one that includes buildUUID and gitHubCheckStatus
only.
The buildUUID is GitHub event ID, so it will be different between
a PR created, PR sync and comment added events, but it will stay
the same throughout the lifecycle of the PipelineRun triggered by
the event.
The gitHubCheckStatus is set to "pending" by all pipeline run
status except for success and fail. This way, once we run the
<buildUUID>-pending taskrun, it won't be possible to run it again
as the name will already be in the cluster.
On a busy cluster it still may happen that the "pending" taskrun
runs after the "pass/fail" one, but this change reduces the
likelyhood.
These are the criteria …
=> Reduce the likelyhood of pending CI jobs

tekton/ci/community/trigger.yaml, tekton/ci/pipeline/trigger.yaml, tekton/ci/plumbing/trigger.yaml, tekton/ci/shared/eventlistener.yaml, tekton/ci/shared/trigger.yaml, tekton/ci/website/trigger.yaml
Old style interceptors won't work with trigger groups.
Until https://github.com/tektoncd/plumbing/pull/967 is merged,
leave the add-pr-body interceptor out of the trigger group.
review them:
/kind misc
=> Move the custom interceptor out of trigger groups

tekton/ci/jobs/tekton-catalog-catlin-lint.yaml, tekton/ci/jobs/tekton-kind-label.yaml
Today, the tasks and pipelines in ci/jobs use parameters in the scripts which are interpolated.
As described in #971, this is fragile and poses a security risk.
In this change, we migrate to using environment variables which  are not interpolated in scripts.
Related issue: #971
cc @sbwsg 
review them:
=> CI Jobs: Use Environment Variables instead of Parameters

tekton/ci/shared/common-tasks.yaml
Today, the tasks and pipelines in ci/shared  use parameters
in the scripts which are interpolated.
As described in tektoncd#971, this is fragile and poses a security risk.
In this change, we migrate to using environment variables which
are not interpolated in scripts.
cc @sbwsg 
review them:
=> CI Shared: Use Environment Variables instead of Parameters

tekton/mario-bot/mario-github-comment.yaml
Today, the tasks and pipelines in ci/shared  use parameters in the scripts which are interpolated.
As described in #971, this is fragile and poses a security risk.
In this change, we migrate to using environment variables which are not interpolated in scripts.
cc @sbwsg 
review them:
=> Mario Bot: Use Environment Variables instead of Parameters

tekton/resources/cd/eventlistener.yaml, tekton/resources/ci/bindings.yaml, tekton/resources/ci/github-template.yaml
As part of https://github.com/tektoncd/plumbing/pull/969 I added some
extra labels, however the values in those params are not always fit to
be label values and are causing the taskrun to not be created.
Remove the extra labels but keep the new naming format.
Also restore the checkName as part of the GitHub notification taskrun, since
we may be running more than one CI job per GitHub event.
review them:
/kind misc
=> Remove the extra labels from the github-set-status

catlin/pkg/validator/task_validator.go, catlin/pkg/validator/task_validator_test.go
Prior to this commit catlin unit tests would fail because
the expected error message didn't exactly match the output
of the validator.
This commit removes an unused regex pattern and fixes the
unit test.
review them:
=> Fix two small issues with catlin script param detection

tekton/resources/cd/configmap-template.yaml, tekton/resources/cd/folder-template.yaml, tekton/resources/cd/helm-template.yaml, tekton/resources/images/docker-multi-arch-template.yaml, tekton/resources/images/ko-multi-arch-template.yaml, tekton/resources/nightly-release/tasks.yaml, tekton/resources/nightly-tests/base/deploy_tekton_component.yaml, tekton/resources/nightly-tests/bastion-p/k8s_cluster_setup.yaml, tekton/resources/nightly-tests/bastion-z/k8s_cluster_setup.yaml, tekton/resources/release/base/github_release.yaml, tekton/resources/release/base/install_tekton_release.yaml, tekton/resources/release/base/prerelease_checks.yaml
Prior to this commit we had several script blocks using the syntax
`$(params.foo)` to pull in param values. As per https://github.com/tektoncd/plumbing/issues/971
it is advised to pull these usages into environment variables to
improve robustness (unexpected characters in param values like quotes and ampersands
can cause confusing issues when a script runs) and to remove
one avenue of script injection in scenarios when a param includes
user-submitted content.
This PR patches resources in the cd, images, nightly-release,
nightly-tests and release/base directories to move param referencing
into environment variables.
review them:
_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRI …
=> Sanitize param usage in some plumbing task script blocks

tekton/ci/catalog/trigger.yaml
The trigger needs this interceptor to get the PR body.
This was probably a miss from #968 since the other issue comment
triggers all have the interceptor added back.
review them:
=> Add back add-pr-body to catalog-issue-comment

tekton/mario-bot/mario-github-comment.yaml, tekton/mario-bot/mario-image-build-trigger.yaml
Dogfooding Pipeline to Taskrun is part of our strategy for creating a
successor to PipelineResources. This commit rewrites the mario
image builder trigger template to use a PipelineRun containing a
PipelineToTaskRun, plus a finally Task, and rewrites the mario
github trigger template to use a Run of kind PipelineToTaskRun.
PipelineToTaskRun does not support workspace mountPaths or finally Tasks,
so this commit rewrites existing pipelines to avoid using those features
in a PipelineToTaskRun. In addition, PipelineToTaskRun does not support
OCI bundles, so the pull-request and git-clone tasks were installed
in the mario namespace of the dogfooding cluster.
This commit requires updating Triggers in the dogfooding cluster
to pull in [PR: support Runs in …
=> Dogfood Pipeline to TaskRun with Mario bot

tekton/resources/nightly-tests/base/deploy_tekton_component.yaml, tekton/resources/nightly-tests/bastion-p/k8s_cluster_setup.yaml, tekton/resources/release/base/prerelease_checks.yaml
A few recent PRs improved on the use of params replacement, by setting
up environment variables to be used in scripts instead of resolving
params directly in there. A few "env" however have been misplaced under
the task spec directly, instead of going in a step or stepTemplate.
This PR fixes the issue.
review them:
/kind bug
=> Fix a few misplaced "env" in tasks

tekton/ci/jobs/tekton-github-tasks-completed.yaml
`tekton/ci/jobs/tekton-github-tasks-completed.yaml` was missing a closing double-quote, causing [errors like this](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/check-github-tasks-completed-n4m57?pipelineTask=github-tasks-completed&step=check-github-tasks-completed).
review them:
=> Fix missing double quote in check-github-tasks-completed

tekton/ci/jobs/tekton-kind-label.yaml
The check-kind-labels PipelineRuns are failing with this error:
> NameError: name 'os' is not defined
In this change, we import os which is needed in the python script.
Related PR: https://github.com/tektoncd/plumbing/pull/974
[Example](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/check-pr-labels-rvgp8?pipelineTask=kind-label&step=check-labels)
/cc @sbwsg @dibyom @abayer 
review them:
=> Fix kind-label: import os

tekton/resources/nightly-tests/bastion-z/k8s_cluster_setup.yaml
At this moment REMOTE_HOST env variable is used for port specification in k8s cluster creation task for s390x tests, which is wrong.
It should be REMOTE_PORT instead.
/kind bug
review them:
=> Fix k8s cluster creation for s390x tests

tekton/resources/nightly-release/overlays/operator/template.yaml
Rename the PipelineRef in Operator nightly Triggertemplate
As the same pipeline is used for versioned releases and
nightly releases for the operator now, the PipelineRef name will
be same as in the versioned release PipelineRuns
review them:
=> Fix PipelineRef in Operator nightly

hack/tekton_ci.sh, hack/tekton_in_kind.sh, scripts/deploy-release.sh, scripts/e2e-tests.sh, scripts/library.sh, scripts/presubmit-tests.sh, tekton/cd/pipeline/overlays/robocat/pre/100-inject-minio-creds.sh
Today, these scripts use `#!/bin/bash` which causes errors in Mac.
To make the scripts work for Mac, and any other operating system,
the scripts need to check the version of bash that's set as default
for the systems. So, this commit updates the scripts to use
`#!/usr/bin/env bash`. This allows Mac to use bash 4.
Related issues and pull requests in knative/test-infra: 
- https://github.com/knative/test-infra/pull/1350
- https://github.com/knative-sandbox/net-contour/issues/638
- https://github.com/knative/test-infra/issues/2143
review them:
=> Make Scripts Mac-Friendly

tekton/resources/nightly-tests/dashboard-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/dashboard-deploy-test-s390x-template.yaml
At this moment dashboard nightly tests are failing for Z and P with `no space left on device` error. 
The fix adds extra disk space to the pipelinerun to resolve this problem.
/kind misc
review them:
=> Add extra disk space for dashboard nightly tests to resolve current failure

pipelinerun-logs/Dockerfile, tekton/images/coverage/Dockerfile, tekton/images/kind-e2e/Dockerfile, tekton/images/ko-gcloud/Dockerfile, tekton/images/ko/Dockerfile, tekton/images/kubectl/Dockerfile, tekton/images/test-runner/Dockerfile
Also had to update ones using `golang:1.16.3-alpine12` to `golang:1.16.13-alpine15`, since there's no `-alpine12` image for 1.16.13.
review them:
=> Update Dockerfiles using golang images to Go 1.16.13

tekton/ci/shared/common-tasks.yaml
The PR https://github.com/tektoncd/plumbing/pull/975/files introduced
the use of env variables to avoid param replacement in scripts, however
with env variables we need to use double quotes in a bash script.
review them:
/kind misc
=> Fix single quotes around REGEX

catlin/README.md, catlin/go.mod, catlin/go.sum, catlin/pkg/cmd/bump/bump.go, catlin/pkg/cmd/root.go, catlin/pkg/entry/entry.go, catlin/pkg/entry/entry_test.go, catlin/pkg/entry/version.go, catlin/pkg/entry/version_test.go
Prior to this commit a user developing a new version of a catalog entry would have to
manually copy the existing latest version to a new version directory. e.g.
```
$ ls task/my-task -qh .
0.1  0.2  0.3  0.4  0.5  0.6
$ cp -R "task/my-task/0.6" "task/my-task/0.7"
```
This commit adds a command to Catlin to bump a catalog entry's version.
Example usage: `catlin bump ../../path/to/catalog/task/git-clone`
Contributes to https://github.com/tektoncd/catalog/issues/784
review them:
=> Add `catlin bump` feature to bump catalog entries

docs/dogfooding.md
Updated DNS manager to v0.11.4 on the dogfooding cluster.
The new version handles annotations on `v1` ingresses.
A few changes to the configuration where required:
-  `createCRDs: true` to replace those using v1beta1 CRD with v1 CRD
- `resources.*.memory` to increase memory request / limit as the controller was being killed with OOM
review them:
/kind misc
=> Update DNS manager version

tekton/cronjobs/dogfooding/nightly-tests/ppc64le/catalog-nightly-test/README.md, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/catalog-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/catalog-nightly-test/kustomization.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/kustomization.yaml, tekton/resources/nightly-tests/README.md, tekton/resources/nightly-tests/catalog-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/eventlistener.yaml, tekton/resources/nightly-tests/kustomization.yaml
This PR is similar to #959 to add nightly e2e catalog tests on `ppc64le` cluster.
- add cronjob to trigger ppc64le tekton catalog test
- add trigger template to run ppc64le catalog test pipeline
- git clone catalog repo
- create ppc64le k8s cluster
- e2e tests for tasks marked as runnable for linux/ppc64le
- delete ppc64le k8s cluster
/kind feature
/cc @vdemeester 
review them:
=> Add pipeline to run ppc64le catalog tests

docs/README.md, docs/dogfooding.md, docs/prow.md, robocat/README.md, tekton/cd/dashboard/overlays/dogfooding/ingress.yaml, tekton/cd/dashboard/overlays/robocat/ingress.yaml, tekton/cd/results/overlays/dogfooding/ingress.yaml, tekton/ci/infra/ingress.yaml, tekton/mario-bot/ingress.yaml
The beta1 ingresses are deprecated and will be removed in k8s 1.22.
Since we're now running 1.21 we need update all ingresses.
Prow cluster is running 1.18 for now, so prow's ingress is still
not updated.
review them:
/kind misc
=> Update deprecated v1beta1 ingresses

tekton/resources/org-permissions/peribolos-run.yaml, tekton/resources/org-permissions/peribolos-sync.yaml, tekton/resources/org-permissions/peribolos-trigger.yaml, tekton/resources/org-permissions/peribolos.yaml
Prior to this commit our peribolos sync was using pipelineresources and
didn't have any filtering on the incoming github events.
This commit adds cel filtering to the peribolos trigger and updates the
sync to drop pipelineresources.
review them:
=> Update v1alpha1 Peribolos Task to v1beta1 Pipeline

tekton/resources/org-permissions/kustomization.yaml
The kustomize definition for our org-permissions resources didn't
include the new peribolos-sync pipeline that was added yesterday. This
meant (I think) that the pipeline was not synced into dogfooding and our
peribolos stuff is currently not running.
This commit adds the peribolos-sync pipeline to the kustomization yaml
for the org-permissions resources. After this we should hopefully see
changes to org/org.yaml in community being picked up and run through the
peribolos-sync pipeline.
review them:
=> Sync new peribolos pipeline to dogfooding

tekton/images/ko-gcloud/Dockerfile, tekton/images/ko/Dockerfile, tekton/images/kubectl/Dockerfile
This takes over part of #929.
- ko-gcloud
- ko
- kubectl
This will not affect PRs that uses 1.16.x. Allowing us to quickly do bugfix release to fix CVEs without having to force each component to fix issues with 1.17.
review them:
=> Bump to go 1.17 on images used by release pipelines

tekton/cronjobs/dogfooding/releases/cloudevents-nightly/README.md, tekton/cronjobs/dogfooding/releases/cloudevents-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/releases/cloudevents-nightly/kustomization.yaml, tekton/cronjobs/dogfooding/releases/kustomization.yaml, tekton/resources/nightly-release/kustomization.yaml, tekton/resources/nightly-release/overlays/cloudevents/kustomization.yaml, tekton/resources/nightly-release/overlays/cloudevents/template.yaml, tekton/resources/nightly-release/overlays/cloudevents/trigger.yaml
Cloudevents is an experimental cloudevents controller for Tekton
resource. Add a nightly builds to make it easier to install.
review them:
/kind misc
=> Add nightly build for cloudevents

docs/dogfooding.md
The dns-manager pod was being OOMKilled for a while, making an upgrade
of the hub failing. Bumping the resources request quite a bit to make
sure it has enough room.
=> dogfooding/dns-manager: update resources requests/limits

tekton/images/ko-gcloud/Dockerfile, tekton/images/kubectl/Dockerfile
Bump to go 1.17.8 on images used by release pipelines
- ko-gcloud
- ko
- kubectl
review them:
/kind misc
=> Bump to go 1.17.8 on images used by release pipelines

prow/config.yaml
We shall update the version of golang in our test-runner image,
however since the image is shared by many tests and they always
use the tag "latest", changing the version may brake many tests
out once.
Pin the version in all tests to tag "v20220316-golang-v1-16", so
that we may update the test runner image and then update the
tests one by one or in batches.
review them:
/kind misc
=> Freeze test runner version in prow config

tekton/resources/release/base/github_release.yaml
Create a pipeline that uses git-clone, gcs-download and
create-release-draft instead of the single task with PipelineResources.
Update the template slightly to mark optional fields as comments.
review them:
/kind misc
=> Stop using pipeline resources in create-release-draft

tekton/resources/org-permissions/peribolos-trigger.yaml
The peribolos eventlistener is repeatedly logging the following error:
> error evaluating cel expression: expression \"body.action in ['push']
> && body.repository.full_name == 'tektoncd/community' &&
> body.repository.fork == false && body.base_ref ==
> \\\"refs/heads/main\\\"\" failed to evaluate: no such key: action
This commit attempts a more defensive style to the cel filter to make
it return true or false rather than print an evaluation error.
review them:
=> Make the peribolos trigger's cel filter more defensive

tekton/resources/release/README.md, tekton/resources/release/base/github_release.yaml
The rekor part of the release notes includes some scripts embedded in
the markdown, which is produced through heredoc in a bash script in
the step.
Escaping is a bit challenging because single back-quotes "\`" can be
escaped with a back-slash "\\" like "\\\`" but a sequence of those is
not parsed correctly by bash.
Defining BQ="\\\`" works around it and allows starting and closing
markdown code blocks in herecode through ${BQ}${BQ}${BQ}
Also escaping some dollar signs that I missed before.
review them:
/kind misc
=> Fix escaping of heredoc scripts in markdown

tekton/ci/shared/trigger.yaml
The trigger is using the wrong bindings and failing consistently,
which means that the check-github-tasks-completed job cannot be
re-run by the "/test" command.
review them:
/kind bug
=> Fix the trigger for check-github-tasks-completed on comment

prow/prow.yaml, robocat/cadmin/200-rbac.yaml, robocat/root/cadmin.yaml, tekton/images/koparse/koparse/test_release.yaml
Resources in rbac.authorization.k8s.io/v1beta are deprecated
in k8s v1.17 and removed in v1.22, so update resources accordingly
review them:
/kind misc
=> Update deprecate v1beta1 roles and bindings

tekton/ci/jobs/e2e-kind.yaml, tekton/ci/pipeline/template.yaml
The kind e2e test runs on k8s 1.20 which is not supported by Tekton
anymore. Switch to k8s 1.21 instead.
review them:
/kind feature
=> Change the kind e2e test to k8s 1.21

tekton/images/buildx-gcloud/Dockerfile
Update the docker buildx pluginb from v0.5.1 to v0.8.1 - this will
enable pushing multiple tags at once.
review them:
/kind misc
=> Update the buildx plugin to v0.8.1

tekton/cronjobs/bases/image-build/trigger-image-build.yaml, tekton/cronjobs/dogfooding/images/alpine-git-nonroot-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/buildx-gcloud-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/catlin-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/coverage-image-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/go-rest-api-test-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/hub-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/kind-e2e-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/kind-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/ko-gcloud-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/ko-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/koparse-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/kubectl-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/openssh-server-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/pipeline-test-runner-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/skopeo-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/teps-community-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/images/tkn-nightly/cronjob.yaml, tekton/images/buildx-gcloud/Dockerfile, tekton/resources/images/bindings.yaml, tekton/resources/images/docker-multi-arch-template.yaml, tekton/resources/images/eventlistener.yaml, tekton/resources/images/ko-multi-arch-template.yaml, tekton/resources/images/single-arch-template.yaml
A few changes batched together:
- Remove PipelineResources from the three image build templates:
single arch, multi arch docker, multi arch ko
- Add support for multiple tags. Instead of tagging latest only,
we'll now tag a daily+sha tag and move latest, to allow for
test jobs and infra in general to pin specific versions
- Update trigger resources to v1beta1
review them:
/kind misc
=> Enhance our nightly image builds

scripts/library.sh
Alpine ships the busybox version of mktemp which expects the template
to end with XXXXXX. Move the ".xml" part out of the template name to
make the xml test report working on alpine - for Kind tests.
review them:
/kind misc
=> Fix xml test report for alpine

prow/config.yaml
Change the tekton pipeline integration tests (regular and alpha)
to the test-runner image with golang 1.17.8
review them:
/kind misc
=> Switch pipeline integration tests to golang 1.17.8

prow/config.yaml
Tekton resolution is updating to use latest version of knative to align
with tekton pipelines. Sourcing deps, building etc should now happen
with go 1.17 to match.
This commit updates the prow config for resolution to bring its go
version into step with pipelines.
review them:
=> Update tekton resolution test runner to use go 1.17 image

tekton/resources/cd/ci-triggers.yaml, tekton/resources/cd/eventlistener.yaml, tekton/resources/cd/kustomization.yaml, tekton/resources/cd/notification-triggers.yaml
The tekton-events event listeners receives eventens from Tekton
generated CloudEvents. Migrate it to v1beta1 and start using
TriggerGroups to simplify its configuration, make it easier to
maintain and extend.
This paves the way for new triggers that will setup GCS buckets
in gubernator style to reuse that infra with Tekton jobs.
Related to #1046
review them:
/kind feature
=> Use TriggerGroups and v1beta1 for tekton-events

tekton/resources/ci/gubernator-metadata.yaml, tekton/resources/ci/kustomization.yaml
Store the job metadata and logs in buckets in the format that
gubernator expects. This let us re-use the gubernator application to
manage and visualise logs for CI runs executed through Tekton.
These pipelines are not used that, some updates are required first
for the tekton-events event listener.
Partially addresses #1046
review them:
/kind feature
=> Add pipelines to store job metadata in buckets

docs/prow.md, prow/gce-ssd-retain_storageclass.yaml, prow/ghproxy.yaml
Add the deployment of GitHub proxy from k8s test-infra
https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/ghproxy.yaml
Identical to the original, except for the node selector, since we
don't have a dedicated node for gh-proxy, at least for now, and the
metrics generation, that has been disabled.
This is not used anywhere for now, but we shall integrate it in
all prow components.
We might want to consider running a single cluster for prow and tekton
in future so they can both benefit from a single in cluster gh-proxy
review them:
for …
=> Add GitHub proxy deployment to the prow cluster

adjustpermissions.py
1. Default to non-readonly roles for permission script 🔑
https://github.com/tektoncd/plumbing/pull/926 added a `--readonly` flag
for adding readonly user permissions, however it added it with defualt
"true" which means that by default when running this script to add or
remove permissions, it will only modify the read only permissions and
will leave any write permissions as-is.
This means that when I went to update the governing board permissions -
i.e. adding permissions for new members and removing permissions from
old members, the script did very little and I couldn't figure out why.
This commit switches the default to the writer roles - defaulting to
reader is probably a safer default, however I think it's a confusing
change given how the script has been used so far. Can be convinced …
=> Default not readonly & tolerate missing permissions when removing

adjustpermissions.py
While updating permissions so that @jerop can step in as a governing
board member while I am on leave, I ran into an interruption in the
script execution b/c there was a conditional IAM policy on
tekton-nightly. I traced this back to a conditional policy which gave
@priyawadhwa temporary access (via her Google account at the time) but
had already expired in 2021. After removing this conditional policy the
script ran just fine so I added a brief troubleshooting section to the
script's docs to try to explain this if anyone runs into it in the
future.
review them:
=> Document conditional error with permission script ✍️

prow/config.yaml, testgrid/config.yaml, testgrid/default.yaml
This commit adds a basic testgrid configuration for Tekton's prow instance (under /testgrid),
and configuration for a prow job that runs Configurator (https://github.com/kubernetes/test-infra/tree/master/testgrid/cmd/configurator).
Configurator generates a configuration file that is used by Testgrid, based on our prow configuration and the config added to /testgrid,
and uploads it to the tekton-prow bucket in GCS. This job will run whenever our prow configuration is updated.
The goal of this commit is to get the infrastructure that creates a Testgrid configuration file working, so we can set up
a Tekton dashboard in the Kubernetes TestGrid instance. This configuration has been validated by Configurator, but
it's likely that not all of it is correct. However, this change will not break any …
=> Add basic testgrid config

prow/config.yaml
This commit removes the "prow-job-config" argument from the testgrid postsubmit.
/kind bug
review them:
=> Fix args for testgrid postsubmit prow job

prow/config.yaml
This commit updates the regex used for the TestGrid prow presubmit
to match the configuration files under /testgrid.
/kind misc
review them:
=> Fix regex triggering TestGrid prow job

.github/pull_request_template.md
Pull requests to plumbing must have a "kind" label. This commit updates the PR
template to remind authors to include this label in their PR.
/kind misc
review them:
=> Update pull request template to include kind

prow/config.yaml
This presubmit is working now, so we want to ensure that all changes to testgrid
and prow configuration result in a valid testgrid config.
/kind misc
review them:
=> Make TestGrid plumbing presubmit non-optional

tekton/resources/nightly-release/overlays/chains/template.yaml
The nightly builds of `release.yaml` are being sent to the regular bucket. This commit fixes the issue by explicitly defining which bucket to use.
The chains nightly builds were based on the pipelines nightly builds. There's a non-obvious difference between these two. While the release-pipeline for pipelines uses the [nightly bucket](https://github.com/tektoncd/pipeline/blob/68f2a66c9b2ffcc23ef262bac95d1eb3856021cf/tekton/release-pipeline.yaml#L23) as the default value, chains uses the [prod one](https://github.com/tektoncd/chains/blob/647e29892e2facd8897286fbc782bed74b2264c6/release/release-pipeline.yaml#L40).
=> Use correct bucket for chains nightly

tekton/ci/infra/0001_rbac.yaml, tekton/ci/shared/gubernator-metadata.yaml, tekton/ci/shared/kustomization.yaml, tekton/resources/cd/ci-triggers.yaml, tekton/resources/ci/github-gubernator-template.yaml, tekton/resources/ci/kustomization.yaml
Add templates and triggers to run pipelines that store logs
and metadata for gubernator on GCS buckets.
The target for now is set to a staging bucket for testing
purposes.
review them:
/kind feature
=> Add template and triggers for gubernator logs

tekton/cronjobs/dogfooding/releases/add-pr-body-ci-nightly/README.md, tekton/cronjobs/dogfooding/releases/add-pr-body-ci-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/releases/add-pr-body-ci-nightly/kustomization.yaml, tekton/cronjobs/dogfooding/releases/kustomization.yaml, tekton/resources/nightly-release/kustomization.yaml, tekton/resources/nightly-release/overlays/add-pr-body-ci/kustomization.yaml, tekton/resources/nightly-release/overlays/add-pr-body-ci/template.yaml, tekton/resources/nightly-release/overlays/add-pr-body-ci/trigger.yaml
The ClusterInterceptor version of the add-pr-body interceptor now
gets its own nightly build. The legacy one is deprecated and may
be removed in time.
/kind misc
review them:
=> Add nightly build for the add-pr-body interceptor

tekton/cronjobs/dogfooding/images/catlin-nightly/cronjob.yaml
As we are moving catlin to an independent repo, we need to update
the values of repo name and context path for catlin nightly cronjob
Reference PR:- https://github.com/tektoncd/plumbing/pull/1023
Signed-off-by: Puneet Punamiya <ppunamiy@redhat.com>
review them:
=> Updates the context path for catlin nightly cronjob

tekton/cronjobs/dogfooding/releases/kustomization.yaml, tekton/cronjobs/dogfooding/releases/pipeline-in-pod-nightly/README.md, tekton/cronjobs/dogfooding/releases/pipeline-in-pod-nightly/cronjob.yaml, tekton/cronjobs/dogfooding/releases/pipeline-in-pod-nightly/kustomization.yaml, tekton/resources/nightly-release/kustomization.yaml, tekton/resources/nightly-release/overlays/pipeline-in-pod/kustomization.yaml, tekton/resources/nightly-release/overlays/pipeline-in-pod/template.yaml, tekton/resources/nightly-release/overlays/pipeline-in-pod/trigger.yaml
This commit adds a nightly cronjob and triggers for the ColocatedPipelineRun custom task,
located in tektoncd/experimental/pipeline-in-pod. It uses the custom task release pipeline defined at the
top level of the experimental repo. The cronjob and triggers are copied from other custom task examples
in plumbing.
Needs https://github.com/tektoncd/experimental/pull/872
/kind misc
review them:
=> Add release automation for pipeline-in-pod project

label_sync/labels.yaml
Dependabot uses a "dependencies" label to tab its own PRs.
/kind feature
review them:
=> Add dependencies label

prow/config.yaml
In https://github.com/tektoncd/pipeline/pull/5032, we added the logic for setting embedded status when running end to end tests.
In this change, we set `embedded-status` to `"minimal"` so that we can dogfood the feature alongside other alpha features. This also allows us to run examples with `Matrix` which needs minimal embedded status.
As discussed in slack thread: https://tektoncd.slack.com/archives/CJ4ERJWAU/p1655990546574359
review them:
=> Enable minimal embedded status is alpha integration tests

tekton/resources/release/base/github_release.yaml
In the latest version of rekor the attestation is not base64 encoded
anymore. Adapt the release notes template to account for that.
/kind misc
review them:
=> Change the release note task for rekor 0.8.2

tekton/ci/infra/0001_rbac.yaml, tekton/resources/cd/serviceaccount.yaml, tekton/resources/nightly-tests/bastion-z/cleanup_tekton.yaml, tekton/resources/release/README.md, tekton/resources/release/base/save-release-logs.yaml
Starting with Pipeline v0.37.0, after https://github.com/tektoncd/pipeline/pull/4942 merges, `conditions` will no longer be part of Pipeline. This removes references to `conditions` from the release tooling.
/kind cleanup
review them:
=> Remove `conditions` from release tooling

tekton/cronjobs/dogfooding/peribolos/tektoncd/cronjob.yaml
The peribolos sync runs hourly right now, and it takes 30/40 min to run.
Switch to once per day instead, which was the original plan set in the
base but accidentaly overwritten in the overlay.
/kind misc
review them:
=> Run peribolos daily, not hourly

prow/config.yaml
For now, I'm going with requests of 2 CPUs and 4 gigs of memory, with limits of 4 CPUs and 8 gigs of memory, matching up with Knative's default request/limit from https://github.com/knative/test-infra/blob/main/prow/cluster/build/200-limitrange.yaml
/kind misc
review them:
=> Set requests and limits for Pipeline Prow jobs

tekton/cronjobs/dogfooding/tekton/triggers-to-robotcat-nightly/cronjob.yaml
The nightly deployment of triggers to the robocat clusters does
not include the interceptors, fixing that.
/kind bug
review them:
=> Deploy interceptors in triggers nightly

boskos/boskos.yaml, docs/prow.md, prow/config.yaml, prow/ingress.yaml, prow/plugins.yaml, prow/prow.yaml, prow/prowjob-schemaless_customresourcedefinition.yaml, tekton/ci/interceptors/github/examples/trigger.yaml, tekton/ci/jobs/e2e-kind.yaml, tekton/ci/jobs/tekton-docs-reviews.yaml, tekton/ci/jobs/tekton-golang-lint.yaml, tekton/ci/jobs/tekton-golang-tests.yaml, tekton/ci/jobs/tekton-image-build.yaml, tekton/ci/jobs/tekton-kind-label.yaml, tekton/ci/jobs/tekton-python-unit-tests.yaml, tekton/ci/jobs/tekton-yamllint.yaml, tekton/ci/plumbing/template.yaml
Update Prow to the latest versions used by k8s
Update various Prow and related microservices to the latest
versions used in k8s test-infra.
Reference manifests: https://github.com/kubernetes/test-infra/tree/master/config/prow
- plank has been replaced by prow controller manager
- deck includes spyglass which shall replace gubernator (not removed
yet)
- updated all the container images
- add metric ports and services
- added ghproxy everywhere
- created a Tektoncd wide GitHub oauth app, which is used by deck.
Documented associated process and created the secrets on the cluster.
The k8s test-infra runs boskos janitor, but only for aws and non-gke
resources, while we run it today for gke-resources only.
My impression is that it's merely a naming difference, since upstream
does not configure …
=> Update Prow to the latest versions used by k8s

tekton/ci/cluster-interceptors/add-pr-body/tekton/publish.yaml
The cmd is interceptor and not add-pr-body, which breaks ko-parse.
/kind bug 
review them:
=> Fix the add-pr-body nightly build

tekton/ci/plumbing/template.yaml, tekton/ci/shared/bindings.yaml, tekton/ci/shared/eventlistener.yaml, tekton/ci/shared/gubernator-metadata.yaml, tekton/resources/ci/github-gubernator-template.yaml
Add the build-id cluster interceptor to the root group interceptors
for tekton based CI.
Define a binding to pull the build id into a parameter.
Add this new parameter into the plumbing CI template (for now only
plumbing) and inject that into the existing prow build id
annotation. Change the gubernator jobs to use the value pulled from
the prow annotation as job number.
This should result in having the build id (prow style) in the path
to the logs in the GCS bucket, and ultimately in spyglass displaying
those logs.
/kind feature
review them:
for more …
=> Use the build-id cluster interceptor

tekton/ci/cluster-interceptors/add-pr-body/tekton/release-pipeline.yaml, tekton/ci/cluster-interceptors/build-id/tekton/release-pipeline.yaml, tekton/ci/interceptors/add-pr-body/tekton/release-pipeline.yaml, tekton/ci/interceptors/add-team-members/tekton/release-pipeline.yaml
This is preventing resources from being applied to the cluster,
probably caught by stricter validation in recent releases.
/kind bug
review them:
=> Close some parenthesis left open

tekton/resources/cd/ci-triggers.yaml, tekton/resources/cd/eventlistener.yaml, tekton/resources/ci/bindings.yaml, tekton/resources/ci/github-template.yaml
When Tekton CI job start, set the Tekton dashboard URL for the live
view of logs. When the CI job finishes, set the URL that points to
spyglass.
/kind feature
review them:
=> Use the deck/spyglass URL to view logs on CI jobs

tekton/images/test-runner/Dockerfile, tekton/images/test-runner/setup-kind.sh
This isn't ideal - it means we've got the same file in `tekton/images/kind-e2e/setup-kind.sh` and `tekton/images/test-runner/setup-kind.sh`. But at least for the moment, this seems like the cleanest way to get `setup-kind.sh` (as `/usr/local/bin/kind-e2e`) on an image with Docker-in-Docker support set up properly.
/kind misc
review them:
=> Add /usr/local/bin/kind-e2e to test-runner image

tekton/ci/cluster-interceptors/build-id/cmd/interceptor/main.go, tekton/ci/cluster-interceptors/build-id/config/200-interceptor.yaml
The cluster interceptor framework does not seem to work well with
upper/lower case. Also the current config does not match between
the register call and path set in the CRD.
Use "buildid" everywhere to avoid issues.
/kind misc
review them:
=> Update the buildid cluster interceptor to lower

prow/config.yaml
This will need https://github.com/tektoncd/pipeline/pull/5077 to be merged before it will actually work with any other PRs, but that's fine. =)
Assuming this works, I'll be adding the alpha integration job as well in a follow up.
/kind misc
review them:
=> Add optional Pipeline integration-in-Kind Prow job

prow/config.yaml
Might as well add the `pull-tekton-pipeline-kind-alpha-integration-tests` job too, and simplify the args for the kind `ProwJob`s, since `test-runner` ends up actually ignoring everything before the last `--` in its args other than `--service-account`.
I also changed to use `gcr.io/tekton-releases/dogfooding/test-runner:latest` in the kind jobs for the moment, to avoid needing to make any additional changes needed to `test-runner`, wait for it to merge/release, then update the config again with the new image. We'll switch back to a specific tag once things have stabilized.
And finally, I dropped the reqs/limits for the unit test and coverage Pipeline jobs to `1000m/2Gi` and `2000m/4Gi`, since those jobs legitimately don't need as much CPU/RAM as the integration test and build jobs.
EDIT: …
=> Add Pipeline alpha integration Kind-in-Prow job, tweaks to Pipeline job requests

tekton/images/test-runner/Dockerfile
I'm leaving the `kind` and `kind-e2e` images on v0.11.1 for now, but if I'm going to bump the `test-runner` one, might as well go to latest (v0.14.0).
Note, for what it's worth: here's how I was able to verify that this all actually worked locally (on my Linux box), after building `test-runner`, from `/home/abayer/go/src/github.com/tektoncd/pipeline` with my branch from https://github.com/tektoncd/pipeline/pull/5077 checked out:
```
docker run -v /var/run/docker.sock:/var/run/docker.sock -v /lib/modules:/lib/modules -v /sys/fs/cgroup:/sys/fs/cgroup -v $PWD:/home/prow/go/src/github.com/tektoncd/pipeline --workdir /home/prow/go/src/github.com/tektoncd/pipeline --net=host test-runner -- -- /usr/local/bin/kind-e2e --k8s-version v1.22.x --cluster-suffix whatever --nodes 3 --e2e-script …
```
=> Update kind version in test-runner image

prow/prow.yaml
I noticed this in hook's logs:
```
{"author":"piyush-garg","component":"hook","error":"failed to list prowjobs for pr: prowjobs.prow.k8s.io is forbidden: User \"system:serviceaccount:default:hook\" cannot list resource \"prowjobs\" in API group \"prow.k8s.io\" in the namespace \"default\"","event-GUID":"761697e0-fd3c-11ec-8759-59acd949f680","event-type":"pull_request","file":"k8s.io/test-infra/prow/plugins/trigger/pull-request.go:150","func":"k8s.io/test-infra/prow/plugins/trigger.handlePR","level":"error","msg":"Failed to abort jobs for closed pull request","org":"tektoncd","plugin":"trigger","pr":891,"repo":"operator","severity":"error","time":"2022-07-06T15:01:07Z","url":"https://github.com/tektoncd/operator/pull/891"}
```
...and after checking, saw that the hook role didn't have …
=> Update a couple Prow SA roles to match k8s/test-infra's setup

tekton/resources/ci/bindings.yaml
gitHubRepoUnderscope is sitting in a binding that is not used
anywhere, causing log links to be broken. Move it to the
overlay binding so that it's picked up by the correct trigger
and template.
/kind bug
review them:
=> Move gitHubRepoUnderscope to the right binding

docs/prow.md, prow/config.yaml, prow/tune-sysctls_daemonset.yaml
https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files seems to be the root of cluster launch issues I've been seeing on the kind clusters. I found https://github.com/kubernetes/test-infra/pull/13515 as a solution to this - I took the current version of the daemonset added in that PR, added a sysctl call to set `fs.inotify.max_user_instances=512` as well, and documented it in docs/prow.md. I've applied this by hand to the Prow cluster already, and it appears to have done the trick.
This also reverts us back to 3 worker nodes per kind cluster, since decreasing the cluster size didn't solve the problem, and I saw some real drop in the kind jobs' speed with 2 nodes.
/kind misc …
=> Add daemonset to Prow cluster to tune sysctl for kind, go back to 3 worker nodes

prow/config.yaml
Until https://github.com/tektoncd/pipeline/pull/5077 merges, these jobs will fail on any other PR, so we should make sure they can't accidentally get invoked via `/test all`.
/kind misc
review them:
=> Remove `/test all` from currently optional Pipeline kind-in-Prow jobs

prow/config.yaml
I'm trying to figure out why multiple concurrent jobs will sometimes fail a lot of tests at once. This doesn't seem to be CPU or memory contention specifically, since I've seen jobs be just fine when they're sharing the node with other non-kind beefy jobs, so let's try an experiment: make sure each Pipeline kind job is on its own node, to see if the underlying issue is in fact having multiple kind jobs on the same node.
If that hunch does turn out to be true, I'm not entirely sure what the solution will be. But it'll be good to know one way or the other.
/kind misc
review them:
=> Experiment with requiring that Pipeline kind jobs can't be on the same node

tekton/ci/catalog/template.yaml, tekton/ci/community/template.yaml, tekton/ci/pipeline/template.yaml, tekton/ci/plumbing/template.yaml, tekton/ci/shared/bindings.yaml, tekton/ci/shared/template.yaml, tekton/ci/website/template.yaml, tekton/resources/cd/eventlistener.yaml, tekton/resources/ci/bindings.yaml, tekton/resources/ci/github-gubernator-template.yaml, tekton/resources/ci/github-template.yaml
The CI notification and log upload jobs used a shortened version of the
build ID to make their name unique per source event (from GitHub).
The build ID has been replace with a prow style build ID for the
spyglass integration, which has broken the name uniqueness since the
short version of the prow build ID is repeated.
Add the sourceEventId (X-GitHub-Delivery) to the bindings and templates
and use that as a source for the shortSourceEventId and ultimately to
make taskrun names unique.
/kind bug
review them:
=> Replace shortBuildUUID with shortSourceEventId

prow/config.yaml
It was a bit simpler to delete the old ones and rename the new ones. This also removes the separate YAML-only kind jobs, since the "combined" jobs are fast enough.
Additionally, this sets the CPU requests/limits for the Pipeline build tests job to 8000m, since it's extremely CPU dependent, and this should drop its run time considerably from the 40+ minutes it often is now. We've easily got the capacity for that increased requirement with the e2e jobs moving to separate n2-standard-4s.
/kind misc
review them:
=> Switch Pipeline to Kind-in-Prow e2e jobs

tekton/resources/ci/github-template.yaml
The tekton.dev/pr-number labels makes it possible to filter for
all github notifications and all taskruns in general associated
to a specific PR over time.
Useful for debugging github notifications.
/kind misc
review them:
=> Add the tekton.dev/pr-number to github notifications

tekton/ci/shared/labels.yaml
Cheking label only does not work as label is a map in the input
event.
/kind  bug
review them:
=> Check if label.name startswith kind/

tekton/ci/shared/common-tasks.yaml
I _think_ this should be the last references to `Pipeline`, `PipelineRun`, `Task`, or `TaskRun` with `apiVersion: tekton.dev/v1alpha1`.
/kind misc
review them:
=> Remove last lurking Tasks with apiVersion tekton.dev/v1alpha1

tekton/resources/cd/cleanup-template.yaml, tekton/resources/cd/configmap-template.yaml, tekton/resources/cd/folder-template.yaml
Configmap CD relies on the cluster PipelineResource to target
deployments of resources.
Migrate that to workspaces: a secret stored in the cluster bound
through a workspace is used to target the deployment.
Secrets have been preprovisioned on the cluster, their name is
tektoncd-, their type is kubeconfig.
See #887 for more details.
The change is implemented so that the template interface does not
change and thus all existing cronjobs are still valid.
review them:
=> Migrate the configmap CD service to workspaces

tekton/resources/cd/helm-template.yaml
Helm chart deployment relies on the cluster PipelineResource
to target deployments of resources.
Migrate that to workspaces: a secret stored in the cluster bound
through a workspace is used to target the deployment.
Secrets have been preprovisioned on the cluster, their name is
tektoncd-, their type is kubeconfig.
See #887 for more details.
The change is implemented so that the template interface does not
change and thus all existing cronjobs are still valid.
review them:
=> Migrate the helm template CD service to workspaces

prow/config.yaml
We don't actually need this, since we're only running one cluster in the job, and using a value of `$(PULL_NUMBER)` breaks when building a batch job of multiple PRs.
/kind misc
review them:
=> Remove --cluster-suffix from kind-e2e calls

prow/config.yaml
I just happened to do one of my periodic checks on top pods in the Prow cluster by CPU, and saw one for `post-tekton-pipeline-go-coverage` using 15 CPUs worth. So...yeah, that should have requests/limits!
/kind misc
review them:
=> Set requests/limits on post-tekton-pipeline-go-coverage

tekton/ci/shared/labels.yaml
Currently the shared repo trigger that responds to PR and Comments runs
the github task and label checks which is ok.
The all-repo trigger that reponds to label events runs only the github
task check, but it should instead run the label check.
Fixes: #1168
/kind misc
review them:
=> Fix the label check

tekton/ci/jobs/tekton-image-build.yaml
Right now, a change in `tekton/images/koparse/koparse/test_release.yaml` will result in kaniko4ci trying to build in `tekton/images/koparse/koparse`, but there's no Dockerfile there. So let's have the task traverse parent directories until it either finds a Dockerfile or gets to the root directory.
/kind misc
review them:
=> kaniko4ci should handle changes in subdirectories for images

tekton/cd/pipeline/overlays/robocat/kustomization.yaml
The deployment pipeline uses alpha features, so it requires alpha flags
to be on in the robocat cluster.
/kind misc
review them:
=> Enable pipeline feature flags in robocat

tekton/resources/cd/kustomization.yaml
The clusters.yaml file has been previously removed along with
PipelineResources in tekton/cd resources, but it was left over in the
kustomization.yaml file.
Fix this to restore deployment of resources.
/kind bug
review them:
=> Remove clusters.yaml from list of resources

tekton/resources/cd/install-tekton-release.yaml
Support installing a released called "latest" in the
install_tekton_release pipeline.
Use two mutually exclusive flavours of the fetch release pipeline
task, one that fetches "latest" and the other one "previous/<version>"
depending on the requested version.
The install task depends on both fetch tasks, which is possible now
that we have task scoped when expressions.
/kind misc
review them:
=> Support release "latest" in install tekton release

prow/config.yaml
The image that was previously used had a comment that said it used 1.18,
but actually used 1.17:
```sh
$ docker run gcr.io/tekton-releases/dogfooding/test-runner:v20220721-5c0e8e0e7a@sha256:8680f99c4d068ef3eb2512d9d3a153049b40f719454e21dfa4aaf691d7de4db5 -- go version
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Cloning into '/home/prow/go/src/github.com/google/licenseclassifier'...
fatal: not a git repository (or any of the parent directories): .git
== Running ./runner.sh backward compatibility test runner ===
+ [[ 3 -ne 0 ]]
+ case $1 in
+ shift
+ [[ go == \-\- ]]
+ break
+ go version
go version go1.17.11 linux/amd64
+ EXIT_VALUE=0
+ set +o xtrace
```
/kind misc
These are the …
=> prow: bump test-runners to an image that actually uses go 1.18.3.

prow/config.yaml
This reverts commit 80875d194dbcbb783d5cd90b380016598264e790.
The change breaks build jobs on at least pipeline, operator and CLI.
We should do this incrementally along with fixes to the lintinig issues
or linting configuration.
/kind misc
review them:
=> Revert "prow: bump test-runners to an image that actually uses go 1.18.3."

tekton/images/test-runner/entrypoint.sh
If directory ${GOPATH}/src/github.com/google/licenseclassifier exists and is not empty we should skip clone again or will cause an error.
Related Issue: https://github.com/tektoncd/pipeline/issues/5193
review them:
=> Fix: determine whether the destination path already exists before clone

cmd/combine/README.md, cmd/combine/main.go
This updates cmd/combine to optionally allow combining 3+ base images
together, in addition to the 2 base images previously supported.
Some users may need support for multiple versions of Windows, which this
enables.
https://github.com/tektoncd/pipeline/issues/5327
/kind feature 
review them:
=> combine: Support multiple base images

prow/plugins.yaml
we would like to enable the cherrypicker plugin in prow for operator repository
https://github.com/kubernetes/test-infra/tree/master/prow/external-plugins/cherrypicker
eg.
```
/cherrypick release-1.10
```
following the docs at https://github.com/kubernetes/test-infra/blob/master/prow/plugins/README.md#external-plugins
enabling the cherrypicker external plugin for operator repository
review them:
=> Enables cherry-pick plugin in prow for tektoncd/operator

tekton/resources/cd/folder-template.yaml
Replacing a service account on the cluster causes k8s to create a
service account token every time.
Using kubectl apply avoids that behaviour, but we still want to
use create/replace for other resources. To solve this, use
dry-run first on kubectl create to place all resources in a file,
then use yq to separate service accounts in a dedicated file, and
finally apply the service accounts file.
/kind bug
review them:
=> Apply ServiceAccount to the cluster

tekton/cd/pipeline/overlays/robocat/feature-flags.yaml
Related to https://github.com/tektoncd/plumbing/pull/1171
Robocat is stuck on Pipelines `v20220727-55665765e4` due to an error in the nightly deploy TaskRun, see for example https://dashboard.dogfooding.tekton.dev/#/namespaces/default/taskruns/deploy-pipeline-release-robocat-chpl9-install-tekton-release?step=deploy-tekton-project
```
2022-08-30T03:01:38.142511933Z error: trouble configuring builtin PatchStrategicMergeTransformer with config: `
2022-08-30T03:01:38.142587504Z paths:
2022-08-30T03:01:38.142595931Z - config-artifact-bucket.yaml
2022-08-30T03:01:38.142602021Z - feature-flags.yaml
2022-08-30T03:01:38.142607828Z `: evalsymlink failure on '/workspace/resources/plumbing/tekton/cd/pipeline/overlays/robocat/feature-flags.yaml' : lstat …
```
=> Add missing feature-flags overlay for Pipelines robocat deploy

tekton/resources/cd/folder-template.yaml
The resource deployment task was failing on permission issues. Ensure the 2nd step can write extra files in the workspace. Only apply files that are non-empty. For instance the cronjob deployment job does not have any service account.
/kind bug
review them:
=> Fix the resource deployment

tekton/resources/cd/folder-template.yaml
Otherwise the `PipelineRun` fails when there are no changes, because it tries to write to the resource path but exited the first step before getting to the `chmod`.
/kind misc
review them:
=> Make resources path writeable earlier

prow/config.yaml
- Removes dind for operator-build-test (not needed)
- Add dind label for experimental integration tests instead of the env
/kind misc
review them:
=> prow/config: only set docker-in-docker with labels

tekton/resources/cd/eventlistener.yaml, tekton/resources/ci/bindings.yaml, tekton/resources/ci/github-template.yaml
Closes #483
I could have added a new `TriggerTemplate`, but it made more sense to just turn the existing `tekton-ci-github-check-end` into a `PipelineRun`.
I did have to add a couple new parameters - the bare repo name (since I wrote up the PR commenter to have the org as a global configuration), and a boolean for pass/fail. It may make sense to tweak the PR commenter to handle `org/repo` instead of just `repo`, and `"success"` or `"failure"` instead of `true` or `false`, but I thought I'd wait to see what people think. =)
/kind feature
review them:
=> Turn on PRCommenter on completion of PR builds

tekton/resources/cd/eventlistener.yaml, tekton/resources/ci/bindings.yaml, tekton/resources/ci/github-template.yaml
Specifically reverting #1220 and #1225
Something's wrong with how this is actually working in practice - I'm not seeing the `PipelineRun` get created, so I'm _guessing_ something's awry in the eventlistener. But I don't know enough to figure out what's wrong. So let's revert this for the moment.
/kind misc
review them:
=> Revert turning on PRCommenter in triggers

tekton/resources/nightly-release/overlays/pipeline-in-pod/template.yaml
This commit adds an "images" parameter to the pipeline-in-pod nightly release pipeline template. Since this custom task has only a controller (no webhook) it can't use the default values for this param (which includes building a webhook).
/kind misc
review them:
=> Add "images" param to pipeline-in-pod release

tekton/cronjobs/dogfooding/releases/concurrency/README.md, tekton/cronjobs/dogfooding/releases/concurrency/cronjob.yaml, tekton/cronjobs/dogfooding/releases/concurrency/kustomization.yaml, tekton/cronjobs/dogfooding/releases/kustomization.yaml, tekton/resources/nightly-release/kustomization.yaml, tekton/resources/nightly-release/overlays/concurrency/kustomization.yaml, tekton/resources/nightly-release/overlays/concurrency/template.yaml, tekton/resources/nightly-release/overlays/concurrency/trigger.yaml
This commit adds a nightly cronjob and triggers for the experimental concurrency reconciler located in tektoncd/experimental/concurrency. It uses the custom task release pipeline defined at the top level of the experimental repo. The cronjob and triggers are copied from other custom task examples in plumbing.
/kind misc
review them:
=> Add nightly release for concurrency project

tekton/resources/ci/github-template.yaml
As it turns out, the problem wasn't the params stuff but that I misformatted the `PipelineRun` in the trigger template. But hey, I still think this is better than needing new param values, so tada.
/kind misc
review them:
=> Turn pr-commenter back on, using existing params

tekton/resources/cd/cleanup-template.yaml
Because the `TaskRun`s are currently failing like:
```
Defaulted container "step-cleanup-pr-tr" out of: step-cleanup-pr-tr, prepare (init), place-scripts (init)
+ '[[' 200 -eq 0 -o 200 '=='  ]]
+ tkn pr delete -n default --keep 200
Error: json: cannot unmarshal object into Go value of type []string
Are you sure you want to delete all PipelineRuns in namespace "default" keeping 200 PipelineRuns (y/n): %
```
/kind misc
review them:
=> Add `-f` to cleanup's `tkn ... delete` calls

tekton/ci/custom-tasks/pr-status-updater/config/500-controller.yaml, tekton/ci/custom-tasks/pr-status-updater/pkg/reconciler/reconciler.go
In dogfooding, it's failing with a "not found" error (which can mean any number of things), but it's working for me locally. I've made a small tweak to the deployment, in case not having `GIT_USER` is causing problems (I don't think it is, but this change matches what's in the configuration for `pr-commenter`), and added some debug logging to better determine what it's actually doing/failing on.
EDIT: Turns out the failure was due to an old version of `pr-status-updater` being installed. Oops. Well, I still think this is worth adding for logging purposes.
/kind misc
review them:
=> Log errors with SCM client in pr-status-updater

pipelinerun-logs/Dockerfile, tekton/images/coverage/Dockerfile, tekton/images/kind-e2e/Dockerfile, tekton/images/kind/Dockerfile, tekton/images/ko-gcloud/Dockerfile, tekton/images/ko/Dockerfile, tekton/images/kubectl/Dockerfile, tekton/images/test-runner/Dockerfile
1.18.7 is the latest version of 1.18 and fixes some CVEs.
/kind misc
review them:
=> Dockerfiles: bump go to 1.18.7 everywhere

prow/config.yaml
This is required for https://github.com/tektoncd/pipeline/pull/5130.
By doing that though, we are not testing on 1.22 anymore which is our min version required, so I am not sure if that's fine or not. https://github.com/tektoncd/pipeline/pull/5130 *will* move the minimum version to 1.23.
/kind misc
review them:
=> prow: bump kind clusters to 1.23

tekton/ci/custom-tasks/pr-commenter/pkg/reconciler/reconciler.go, tekton/ci/custom-tasks/pr-commenter/pkg/reconciler/reconciler_test.go
This doesn't fix whatever the underlying problem (i.e., events being processed more than once, causing the triggers for a specific `TaskRun` failure to fire periodically) is, and can still result in a single outdated comment being added for a stale event, but it should at least prevent that same single outdated comment from being deleted and recreated over and over again.
/kind misc
review them:
=> Don't delete/create identical PR comments

scripts/library.sh
The previously used image, cos, is no longer supported on GKE version 1.24 and later:
https://cloud.google.com/kubernetes-engine/docs/concepts/node-images
/kind bug
review them:
=> Use cos_containerd image for testing

prow/config.yaml
This commit changes the upgrade test env to run on local kind cluster.
Related: https://github.com/tektoncd/pipeline/pull/5726
Fixes: https://github.com/tektoncd/pipeline/issues/5689
review them:
=> Kind cluster upgrade test

tekton/images/test-runner/setup-kind.sh
Add support for projects running their e2e tests on Kubernetes 1.24 or 1.25. Image SHAs are taken from the latest kind release v0.17.0.
/kind misc
review them:
=> Add options for Kubernetes 1.24 and 1.25 to the test-runner kind script

prow/config.yaml
This commit adds the decorate:true for job path to debug the issue where
pipeline repo is not cloned correctly for upgrade test.
review them:
=> Update prow config for upgrade test job

prow/config.yaml
This commit migrates upgrade test from relying on GKE only to be 
using kind cluster setup. And this follows the guide in docs/kind-e2e.md.
/kind misc
review them:
=> [Upgrade test] Update config for upgrade test

prow/config.yaml
Should have been `preset-dind-enabled`, not `preset-dind-enable`. And while I'm here, I'm removing the unneeded anti-affinity rules to make things a bit clearer. Those were from the very early days of the `kind` work to ensure that multiple jobs couldn't end up on the same node before we switched to dedicated nodes of an appropriate size to not be able to have multiple running on them at once.
/kind cleanup
review them:
=> Fix operator integration test configuration, cleanup unneeded affinity rules

prow/config.yaml
/cc @abayer @afrittoli 
/kind misc
review them:
=> Fix the name of the e2e-tests script for operator integration test

tekton/ci/custom-tasks/pr-commenter/config/500-controller.yaml, tekton/ci/custom-tasks/pr-status-updater/config/500-controller.yaml
Just noticed these weren't working since we upgraded k8s on dogfooding - well, specifically pr-commenter wasn't, because it must have had to recreate its pod since the upgrade, while pr-status-updater was still up. Anyway, here's a fix.
(I manually updated the deployments, but they'll obviously break again until this is merged)
/kind misc
review them:
=> Fix PodSecurity for pr-commenter and pr-status-updater custom tasks

tekton/ci/jobs/tekton-golang-coverage.yaml, tekton/ci/repos/pipeline/template.yaml
This PR tries to address issue https://github.com/tektoncd/plumbing/issues/1297.
After looking at some other tasks, it seems like the GitHub token file is named `bot-token`, not `token`. 
/kind bug
review them:
=> renaming token to bot-token

tekton/ci/infra/0001_rbac.yaml, tekton/mario-bot/mario-image-build-trigger.yaml, tekton/resources/cd/serviceaccount.yaml, tekton/resources/nightly-tests/serviceaccount.yaml
After upgrading to triggers v0.22.0, event listeners stopped running, because of interceptors missing in roles
/kind misc
review them:
=> Add interceptor to trigger roles

tekton/cronjobs/dogfooding/releases/workflows-nightly/cronjob.yaml
All of our other nightly releases use v1 CronJobs, and it looks like that change was made concurrently with adding a workflows release cronjob, so the workflows cronjob was left out.
/kind bug
review them:
=> Use v1 CronJob for Workflows nightly release

.gitignore, tekton/cd/pipeline/overlays/dogfooding/feature-flags.yaml, tekton/ci/jobs/tekton-golang-tests.yaml, tekton/ci/jobs/tekton-image-build.yaml
TaskLoop has been superseded by matrix and the taskloop custom controller is not maintained anymore, so remote TaskLoops and replace them with matrix.
Matrix requires minimal embedded status, so enable that too.
/kind misc
review them:
=> Remove usage of TaskLoop

tekton/ci/bases/trigger.yaml, tekton/ci/shared/eventlistener.yaml, tekton/ci/shared/labels.yaml, tekton/mario-bot/mario-image-build-trigger.yaml, tekton/resources/cd/ci-triggers.yaml, tekton/resources/cd/eventlistener.yaml, tekton/resources/cd/notification-triggers.yaml, tekton/resources/images/eventlistener.yaml, tekton/resources/nightly-tests/eventlistener.yaml, tekton/resources/org-permissions/peribolos-trigger.yaml, tekton/resources/release/release-logs/release-logs-triggers.yaml
Due to https://github.com/tektoncd/triggers/issues/1499, all our event listeners were failing. I've pushed an image of `eventlistenersink` built from https://github.com/abayer/triggers/tree/default-to-clusterinterceptor (just one commit on top of Triggers v0.22.0) that fixes this and configured the `tekton-triggers-controller` deployment to use that image (gcr.io/abayer-jclouds-test1/eventlistenersink-7ad1faa98cddbcb0c24990303b220bb8@sha256:6d7769173bec31635bc9994fa5ffa3ae40c493315bf4ae7cca5aff24d824a889) as its `-el-image` argument, which has gotten everything working again, but if we'd prefer to run vanilla v0.22.0, this PR adds an explicit `kind: ClusterInterceptor` to every interceptor reference I could find, which should have the same effect.
/kind bug
These are the criteria that …
=> Explicitly specify `kind: ClusterInterceptor` on interceptor references

tekton/ci/repos/pipeline/template.yaml
When the prefix and suffix were being added to the name `pull-tekton-pipeline-go-coverage-using-tekton`, the admission web hook was throwing an error that the name was too long (> 63 characters). Renaming this to `pull-tekton-pipeline-go-coverage-df` to ensure that it obeys the character limit.
review them:
/kind bug
=> make the name shorter to avoid webhook failure

tekton/ci/custom-tasks/pr-commenter/Makefile, tekton/ci/custom-tasks/pr-commenter/tools/go.mod, tekton/ci/custom-tasks/pr-status-updater/Makefile, tekton/ci/custom-tasks/pr-status-updater/tools/go.mod, tekton/images/test-runner/Dockerfile
Upgraded golangci-lint to 1.50.1 (latest).
This will make some new linters (like `dupword`) available; see https://github.com/tektoncd/pipeline/pull/5918.
Context: https://github.com/tektoncd/pipeline/issues/5899
/kind cleanup
- [N/A] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=> Upgraded golangci-lint to 1.50.1 (latest).

tekton/ci/jobs/tekton-golang-coverage.yaml
There was a typo in tekton-golang-coverage.yaml that was creating wrong artifacts directory named `artifacts"` instead of `artifacts`. This PR fixes that typo.
/kind bug
review them:
=> Fix Typo in tekton-golang-coverage.yaml

label_sync/cluster/label_sync_cron_job.yaml, label_sync/cluster/label_sync_job.yaml
Part of [tektoncd-catalog#3][#3]. This commit adds the `tektoncd-catalog` org to the `orgs` parameter of label syncer so that the `tektoncd-catalog` org can automatically maintain the labels as `tektoncd`. There is no change to the `labels.yaml` file itself.
Comma separated orgs based on: https://github.com/kubernetes/test-infra/blob/master/label_sync/main.go#L144
[#3]: https://github.com/tektoncd-catalog/.github/issues/3
review them:
=> Apply label_sync to tektoncd-catalog org

tekton/ci/custom-tasks/pr-commenter/README.md, tekton/ci/custom-tasks/pr-commenter/config/201-clusterrole.yaml, tekton/ci/custom-tasks/pr-commenter/pkg/reconciler/controller.go, tekton/ci/custom-tasks/pr-commenter/pkg/reconciler/params.go, tekton/ci/custom-tasks/pr-commenter/pkg/reconciler/params_test.go, tekton/ci/custom-tasks/pr-commenter/pkg/reconciler/reconciler.go, tekton/ci/custom-tasks/pr-commenter/pkg/reconciler/reconciler_test.go, tekton/ci/custom-tasks/pr-status-updater/README.md, tekton/ci/custom-tasks/pr-status-updater/config/201-clusterrole.yaml, tekton/ci/custom-tasks/pr-status-updater/pkg/reconciler/controller.go, tekton/ci/custom-tasks/pr-status-updater/pkg/reconciler/params.go, tekton/ci/custom-tasks/pr-status-updater/pkg/reconciler/params_test.go, tekton/ci/custom-tasks/pr-status-updater/pkg/reconciler/reconciler.go, tekton/ci/custom-tasks/pr-status-updater/pkg/reconciler/reconciler_test.go
This is two commits on purpose to make it easier to revert the `CustomRun`->`Run` change later.
First, I added `customruns` to the permissions for the `pr-commenter` and `pr-status-updater` service accounts, which was kinda needed if they're trying to watch `CustomRun`s. =)
But once I fixed that in-cluster manually, I realized that the custom tasks invoked by various triggered `PipelineRun`s for these particular custom tasks...were being generated as `Run`s. That's because the `PipelineRun` reconciler only recently added a feature flag to enable creating `CustomRun`s instead, and that's not switching to the default until v0.44, if I remember correctly. So for now, we need to go back to `Run`s here.
/kind misc …
=> Fix perms for custom tasks, revert those custom tasks back to v1alpha1.Runs for now

tekton/resources/nightly-release/overlays/pipeline/template.yaml
The Pipeline nightly release `PipelineRun` timed out last night, with the default 60m timeout. A subsequent manually-triggered run succeeded in 51m. This suggests to me that it's not unreasonable to expect that the `PipelineRun` could take over 60m in some cases, so let's set an explicit 90m timeout for it.
/kind misc
review them:
=> Add an explicit 90m timeout to Pipeline nightly release

tekton/ci/shared/gubernator-metadata.yaml, tekton/resources/release/release-logs/save-release-logs.yaml
The previous version of the image, with tkn v0.23.1, generated no output (and may have had a non-zero exit status, I forgot to check) when trying to read `PipelineRun` logs, breaking capturing the logs for Tekton jobs on Dogfooding in Gubernator (or in S3, in the case of the release tooling). So let's switch to the latest nightly image, which uses tkn v0.28.0, since I'm pretty sure this is some compatibility issue with some combination of the Pipelines version we have on Dogfooding (v0.41.0 at the moment) and/or Dogfooding's k8s version (v1.23).
/kind misc
review them:
=> Update gubernator and release PipelineRun logs ingest from tkn to use newer dogfooding/tkn image

prow/config.yaml
Follows the guide in docs/kind-e2e.md with a couple of changes to match the current pipeline e2e tests:
1. Use latest builder image for the time being
2. Adds a `pipeline-kind-e2e: "true"` label that is used for podAntiAffinity - we don't want multiple kind jobs running on the same nodes.
Part of tektoncd/triggers#1475
/kind misc
review them:
=> Migrate Triggers e2e test to kind

tekton/ci/cluster-interceptors/add-pr-body/tekton/release-pipeline.yaml, tekton/ci/cluster-interceptors/build-id/tekton/release-pipeline.yaml, tekton/ci/custom-tasks/pr-commenter/tekton/release-pipeline.yaml, tekton/ci/custom-tasks/pr-status-updater/tekton/release-pipeline.yaml, tekton/ci/interceptors/add-pr-body/tekton/release-pipeline.yaml, tekton/ci/interceptors/add-team-members/tekton/release-pipeline.yaml, tekton/ci/jobs/e2e-kind.yaml, tekton/ci/jobs/tekton-catalog-catlin-lint.yaml, tekton/ci/jobs/tekton-catalog-diff-task.yaml, tekton/ci/jobs/tekton-docs-reviews.yaml, tekton/ci/jobs/tekton-golang-coverage.yaml, tekton/ci/jobs/tekton-golang-lint.yaml, tekton/ci/jobs/tekton-golang-tests.yaml, tekton/ci/jobs/tekton-image-build.yaml, tekton/ci/jobs/tekton-org-validation.yaml, tekton/ci/jobs/tekton-python-unit-tests.yaml, tekton/ci/jobs/tekton-teps-validation.yaml, tekton/ci/shared/gubernator-metadata.yaml, tekton/resources/cd/configmap-template.yaml, tekton/resources/cd/folder-template.yaml, tekton/resources/cd/install-tekton-release.yaml, tekton/resources/cd/notification-template.yaml, tekton/resources/release/base/github_release.yaml, tekton/resources/release/release-logs/save-release-logs.yaml
Legacy bundles are not supported in v0.44.0.
Conversion should migrate automatically to the remote resolution syntax, but due to a bug it doesn't work:
- https://github.com/tektoncd/pipeline/issues/6058
Migrate all bundle references to the new format to avoid the issue in the convertion.
/kind misc
review them:
=> Migrate bundles to new syntax

hack/tekton_in_kind.sh, tekton/ci/jobs/tekton-image-build.yaml, tekton/ci/shared/common-tasks.yaml
Matrix does not support array results as inputs yet, so switch to using the first item of the list for now.
/kind bug
review them:
=> Fix matrix usage in dogfooding

tekton/resources/cd/serviceaccount.yaml
The cleaner cronjobs haven't been doing anything for...a while, due to not having `runs` permission. Might as well add `customruns` while I'm here.
/kind misc
review them:
=> Add permissions to tekton-cleaner SA

prow/config.yaml, prow/plugins.yaml
This commit adds `tektoncd-catalog` org to `prow/config.yaml` and `prow/plugins.yaml` files. It applies the same configuration to `tektoncd-catalog` as `tektoncd` org to achieve the same level of automation and administration.
review them:
=> Add tektoncd-catalog org under Prow

gubernator/config.yaml, prow/config.yaml
This commit adds the `pull-tekton-pipelines-beta-integration-test`
review them:
=> Add beta integration test for V1 release

prow/config.yaml
This reverts commit 89106702e317eb026cd895df6aeab28350eb9d18.
We had some new test failures once we switched to kind.
Temporary till we fix tektoncd/triggers#1519
/kind bug
review them:
=> Revert "Migrate Triggers e2e test to kind"

tekton/cd/pipeline/overlays/dogfooding/git-resolver-config.yaml, tekton/cd/pipeline/overlays/dogfooding/kustomization.yaml
I'm not 100% sure if this is right - specifically, this is trying to write to the `git-resolver-config` `ConfigMap` in the `tekton-pipelines-resolvers` namespace, but I put it in the same directory as the rest of the pipelines overlays. @afrittoli - I _think_ this should work correctly, but I defer to you. =)
/kind misc
review them:
=> Configure the git resolver with the GitHub API token

prow/config.yaml, tekton/cd/pipeline/overlays/dogfooding/feature-flags.yaml
This commit removes the `embedded-status` feature flag config for the dogfooding cluster
and the prow env setup.
/kind misc
review them:
=> Remove `embedded-status` feature flag

tekton/ci/jobs/tekton-catalog-catlin-lint.yaml, tekton/ci/repos/catalog/base/kustomization.yaml, tekton/ci/repos/catalog/base/template.yaml, tekton/ci/repos/catalog/community-catalog/kustomization.yaml, tekton/ci/repos/catalog/community-catalog/template.yaml, tekton/ci/repos/catalog/community-catalog/trigger.yaml, tekton/ci/repos/catalog/verified-catalogs/base/kustomization.yaml, tekton/ci/repos/catalog/verified-catalogs/base/template.yaml, tekton/ci/repos/catalog/verified-catalogs/golang/kustomization.yaml, tekton/ci/repos/catalog/verified-catalogs/golang/trigger.yaml, tekton/ci/shared/eventlistener.yaml
This commit adds the required build test infra for the [golang][golang] verified catalog. The functionalities for the [tektoncd/catalog][catalog] repo are unchanged.
Changes include:
- Add an extra `versioning` param to the `catlin-lint` pipeline and task to support both git-based versioning and directory-based versioning path validation
- Update the `eventlistener.yaml` to accept webhook events from both `tektoncd` and `tektoncd-catalog` orgs
- Refactored the directory structure for `/tekton/ci/repos/catalog`, creating sub-directory `verified-catalog` for verified catalog and `community-catalog` for the current [tektoncd/catalog][catalog] repo.
[golang]: https://github.com/tektoncd-catalog/golang
[catalog]: https://github.com/tektoncd/catalog
These are the criteria that every PR should …
=> Add golang verified catalog build test infra

tekton/ci/repos/catalog/kustomization.yaml, tekton/ci/repos/catalog/verified-catalogs/kustomization.yaml
Prior to this change, the `kustomization.yaml` files are missing in the `tekton/ci/repos/catalog/` and the underlying `verified-catalog/` directories. It caused error when running `kustomize build` command from `tekton/` directory. 
This commit adds the missing kustomization files for [#1334][#1334] ([error log][error log]).
/kind bug
[#1334]: https://github.com/tektoncd/plumbing/pull/1334
[error log]: https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelineruns/deploy-resources-tekton-49vpr?pipelineTask=deploy&step=deploy-from-folder
review them:
=> Patch missing kustomization files for verified catalog build tests

tekton/ci/shared/eventlistener.yaml
This commit fixes the extra open parenthesis issue in the event listener.
/kind bug
review them:
=> Fix extra open parenthesis in the event listener

tekton/resources/cd/eventlistener.yaml
Prior to this commit, the cloud events triggered by [post-comment][post-comment] pipeline task pass the `ci-job-triggers` trigger group filter. This causes the corresponding github checks to pass even though the [lint-catalog][lint-catalog] is failed. This commit updates the filter for `post-comment` task run which blocks it from updating github checks.
/kind bug
[lint-catalog]: https://github.com/tektoncd/plumbing/blob/7a844829fdffe75a8fcb0b18b1411776b059ec62/tekton/ci/jobs/tekton-catalog-catlin-lint.yaml#L152
[post-comment]: https://github.com/tektoncd/plumbing/blob/7a844829fdffe75a8fcb0b18b1411776b059ec62/tekton/ci/jobs/tekton-catalog-catlin-lint.yaml#L166
review them: …
=> Add "-post-comment" filter to "ci-job-triggers" trigger group

prow/config.yaml
Switch Kind Cluster to v1.24.X for Beta Integration Test. Last piece of version switching for kind cluster (https://github.com/tektoncd/plumbing/pull/1332)
Signed-off-by: Xinru Zhang [xinruzhang@google.com](mailto:xinruzhang@google.com)
/kind misc
review them:
=> Switch Kind Cluster to v1.24.X for Beta Integration Test

tekton/images/coverage/Dockerfile
The idea is to use the tag+digest so that we can put dependabot in
place to automatically upgrade it. Here for example, as the 1.19 moves
(aka 1.19.6, 1.19.7, …), dependabot would upgrade the digest
automatically with a pull-request (but hopefully should not
automatically to 1.20).
/kind misc
review them:
=> Bump to go 1.19 for coverage Dockerifle

prow/config.yaml
Primarily to upgrade to Go 1.19.
```sh
$ docker run --entrypoint bash -it gcr.io/tekton-releases/dogfooding/test-runner@sha256:9b8548ad06ebb2acc420aa588d47637bd37e9f563588f47c43b22560dc1ce3f8   
root@1c25d7f1b443:/# go version
go version go1.19 linux/amd64
```
NOTE: This may cause some test failures due to changes in gofmt. Repos just need to re-run codegen w/ Go 1.19+ once this is live.
Fixes https://github.com/tektoncd/pipeline/issues/5771
/kind misc
review them:
=> Bump prow test-runner.

cmd/combine/main.go
To avoid a similar future issue to https://github.com/tektoncd/pipeline/pull/6260, ignore `unknown/unknown` which buildkit might start injecting into index manifests in the future.
/kind bug
review them:
PR friction log:
- I forgot to set a `/kind` at first and CI failed; I edited the description to set `/kind` but the label didn't show up, and `/test` didn't rerun the check.
- unit tests failed immediately, but the link goes to a Prow page that says the test has been running for 36 minutes with no link to logs that I can find. `/test` also didn't rerun the check.
=> fix: ignore unknown/unknown platform in cmd/combine

tekton/cd/pipeline/overlays/dogfooding/config-artifact-bucket.yaml, tekton/cd/pipeline/overlays/dogfooding/kustomization.yaml
PipelineResources are not used anymore in dogfooding. The bucket config is incomplete, unused, and it generates a lot of spam in the logs, so removing it.
/kind misc
review them:
=> Remove bucket config

tekton/cronjobs/dogfooding/nightly-tests/ppc64le/dashboard-nightly-test/cronjob.yaml, tekton/resources/nightly-tests/dashboard-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/dashboard-deploy-test-s390x-template.yaml
Move the pcc64le test an hour later to avoid running both in parallel and smooth out the load on the cluster.
Switch the dind storage driver from vfs (not recommended for production, known to be slow) to the recommended overlay2. This speeds up the build of the e2e docker image.
As an example, these stages previously took about 3 - 6 minutes:
```
2023-04-14T09:49:24.018323720Z Step 3/12 : USER node
2023-04-14T09:49:42.620953032Z  ---> Running in 1cf4e8c385da
2023-04-14T09:49:57.520749278Z Removing intermediate container 1cf4e8c385da
2023-04-14T09:49:57.520817169Z  ---> 1bc5a16210f8
2023-04-14T09:49:57.520828507Z Step 4/12 : WORKDIR /home/node
2023-04-14T09:50:09.672928168Z  ---> Running in b5ad065cc3c5
2023-04-14T09:50:25.854761270Z Removing intermediate container b5ad065cc3c5 …
```
=> Improve performance of nightly Dashboard tests on Z and P

tekton/resources/nightly-tests/bastion-z/test_tekton_cli.yaml
pipelineResource is been deprecated in latest release of pipeline. skip those tests while running cli e2e tests and add new plugin related tests. https://github.com/tektoncd/pipeline/pull/6150.
review them:
=> skip pipelineresource tests

tekton/resources/nightly-tests/bastion-p/test_tekton_component.yaml, tekton/resources/nightly-tests/bastion-z/test_tekton_component.yaml, tekton/resources/nightly-tests/pipeline-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/pipeline-deploy-test-s390x-template.yaml
Added missing docker config workspace to push test images.
pipeline e2e and examples tests are failing on Z and PPC64LE platform due to missing /.docker/config.json file. use shared registry workspace available in pipeline to push images to registry.
/kind misc
review them:
=> fix pipelines ci failures due to push permissions

prow/config.yaml
Using the "latest" tag poses security risks and can introduce unanticipated changes into our CI. This commit updates the test-runner image used for tekton pipelines integration tests to be the same one used for unit tests.
/kind bug
review them:
=> Pin test-runner image for pipelines integration tests

prow/config.yaml
A previous commit pinned the test-runner images to an earlier version of the test-runner images. This commit updates it to the correct version that is currently used in unit tests.
/kind bug
review them:
=> Update integration test runner images to go 1.19

tekton/resources/nightly-tests/bastion-p/test_tekton_component.yaml, tekton/resources/nightly-tests/bastion-z/test_tekton_component.yaml
For all CI jobs `registry-shared` workspace is not required. so providing optional flag in the workspace pipelines. This will fix CI Jobs `TaskRunValidationFailed` issue https://dashboard.dogfooding.tekton.dev/#/namespaces/bastion-z/pipelineruns/tekton-triggers-s390x-nightly-run-v5nf8?pipelineTask=e2e-test-triggers&retry=1
/kind misc
Supported kinds are: bug, cleanup, design, documentation, feature, flake, misc, question, tep
-->
review them:
=> Provide workspace optional flag for CI tests

.github/dependabot.yml
Dependabot is currently failing with:
```
Dependabot couldn't find a Dockerfile.
Dependabot requires a Dockerfile to evaluate your Docker dependencies. It had expected to find one at the path: /tekton/images/Dockerfile.
```
This was generated with:
```sh
for dir in `dirname $(find . -type f -name 'Dockerfile' | grep -v "vendor")`; do
p="${dir:1}"
echo "  - package-ecosystem: \"docker\"
directory: \"${p}\"
schedule:
interval: \"weekly\"
labels:
- \"ok-to-test\"
- \"dependencies\"
- \"release-note-none\"
- \"kind/misc\""
done
```
/kind cleanup
review them:
=> Add individual dependabot entries for dockerfile dirs.

tekton/cd/chains/overlays/dogfooding/chains-config.yaml
Chains v0.16 supports attestations for `PipelineRun`, so adding the corresponding settings to the config map to avoid invalid default settings upon deployment.
/kind misc
review them:
=> Add pipelinerun settings for chains v0.16

tekton/images/test-runner/Dockerfile, tekton/images/test-runner/setup-kind.sh
Step 1 for https://github.com/tektoncd/plumbing/issues/1499
This commit
- removes support for EOL k8s versions i.e. 1.20, 1.21, 1.22, 1.23.
- updates support for k8s 1.24 to the latest patch - 1.24.15
- updates support for k8s 1.25 to the latest patch - 1.25.11
- adds support for latest k8s versions including 1.26 and 1.27.
- updates MetalLB to v0.13.10 which doesn't deploy pod security policy which is not supported in k8s 1.25+.
References:
- https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0
- https://metallb.universe.tf/release-notes/#version-0-13-5
Signed-off-by: Chuang Wang <chuangw@google.com>
review them:
_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING …
=> Cleanup supported k8s version in test-runner

prow/config.yaml
The most recent version of pipeline will need 1.25 as minimum version
for Kubernetes, so switching to it.
review them:
=> Use kubernetes 1.25 on kind for pipeline

tekton/images/test-runner/Dockerfile
With debian:bullseye, we are getting an older version of glibc ie less than 2.31 and with golang 1.20 we need a latest version of glibc. debian:bullseye still points to debian 11 whereas other tags have progressed to use debian 12. Updating the debian inplace attracts issues with python
Solution: Use ubuntu 22.10 as it has the recent version of glibc and python also doesn't introduces any new issues. Only change required is of docker installation.
/kind bug
review them:
=> Use Ubuntu instead of debian as base image

prow/config.yaml
One of the dependencies used by chains, cosign, now requires go 1.20. This updates the prow jobs to use that version of go.
review them:
=> Use 1.20 go image for tektoncd/chains

tekton/ci/jobs/tekton-catalog-catlin-lint.yaml
Catlin was running linter on tasks which we are marking as deprecated. Ideally those tasks
should be skipped as those tasks need not to be validated from now on
/kind bug
review them:
=> Ignore deprecated tasks while catlin validate

prow/config.yaml
This will bump k8s version in operator
intergration tests to move to 1.25, to bump
to pipeline 0.51
/kind misc
review them:
=> Bump k8s version in operator jobs

prow/config.yaml
Similar to other repositories, making catalog e2e tests run on kind
/kind feature
review them:
=> Use kind to run e2e CI on catalog

tekton/images/ko/Dockerfile
The Chains controller now requires go 1.20 due to a requirement in one of its dependencies, cosign. Its release pipeline uses the ko image to build the controller binaries. This currently fails because the ko image uses go 1.19. This updates the ko image to use go 1.20.
review them:
=> Update ko image to go 1.20

prow/config.yaml
Catalog nightly jobs were still spawing gke cluster which:
1. takes lot of time to spin
2. there are some issues while testing latest git-clone which runs as non-root
Moving it to kind based so that above problems can be rectified
/kind feature
review them:
=> Use Kind cluster while running nightly catalog e2e

prow/config.yaml
Prior to this change, some rerun and trigger commands did not match the name of the tests. This leads to confusion when trying to use the commands on a pull request.
Ran into this issue when reruning https://github.com/tektoncd/pipeline/pull/6659.
This change adds the prefix `"pull-"` to commands that were missing it, while the test name has that prefix.
/kind misc
review them:
=> Fix Rerun and Trigger Commands

prow/plugins.yaml
As described in tektoncd/community#1092, the `lifecycle` plugin is becoming more of a problem than a solution. See the linked issue for more details.
Closes tektoncd/community#1092
/kind misc
review them:
=> Remove lifecycle plugin from tektoncd org

tekton/ci/jobs/tekton-image-build.yaml
Modified the images-build task to accept matrix input, enabling the build of all modified Docker files. This update replaces the prior method that limited builds to only the first file. This improvement, addresses request [#1531](https://github.com/tektoncd/plumbing/issues/1531).
Updated the images-build task to now accept a matrix input, allowing all modified Docker files in a GitHub commit to be built. This replaces the previous method where only the first file at index [0] was built.
/kind misc
Fixes: #1531
review them:
- [X ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages) …
=> Updated images-build task to utilize matrix as input

prow/config.yaml
This commit adds the prow setup for feature flag tests.
/kind misc
fixes: #1629
review them:
=> Add Prow setup for feature flag tests

tekton/cronjobs/dogfooding/nightly-tests/ppc64le/catalog-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/cli-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/dashboard-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/operator-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/pipeline-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/triggers-nightly-test/cronjob.yaml
Signed-off-by: Valen Mascarenhas [Valen.Mascarenhas@ibm.com](mailto:Valen.Mascarenhas@ibm.com)
This PR modifies the registry for all the tekton nightly jobs for ppc64le . 
We encountered recurring x509 certificate errors on the ppc64le side, causing inconsistency in our operations despite repeated fixes. This inconsistency resulted in significant time wastage and hindered productivity.
To mitigate this issue effectively, we transitioned to a JFrog registry. This solution eliminates the x509 certificate error entirely, providing a reliable and stable environment for our operations
review them:
=> ppc64le job config modified with JFrog registry

robocat/cadmin/200-rbac.yaml
The tekton-deployer service account needs to deploy resolvers as well so grant it the existing roles on the resolvers namespace as well.
/kind misc
review them:
=> Add extra roles to deployer sa for resolvers

tekton/ci/jobs/tekton-github-tasks-completed.yaml, tekton/ci/jobs/tekton-kind-label.yaml
Two tasks have an invalid `.metadata.description` field. Move the description to `.spec.description` instead.
/kind bug
review them:
=> Fix invalid metadata.description

tekton/cronjobs/dogfooding/nightly-tests/ppc64le/catalog-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/cli-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/dashboard-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/operator-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/pipeline-nightly-test/cronjob.yaml, tekton/cronjobs/dogfooding/nightly-tests/ppc64le/triggers-nightly-test/cronjob.yaml, tekton/resources/nightly-tests/catalog-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/cli-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/dashboard-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/operator-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/pipeline-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/triggers-deploy-test-ppc64le-template.yaml
Signed-off-by: Valen Mascarenhas [Valen.Mascarenhas@ibm.com](mailto:Valen.Mascarenhas@ibm.com)
This PR modifies the cronjob timings and timeout for all the tekton nightly jobs for ppc64le .
Due to transitioning to a new automation process, wherein VMs are dynamically provisioned and clusters installed, the time required for cluster creation has increased from 5-7 minutes to 30-35 minutes. Consequently, Tekton jobs are failing due to pipeline timeout errors. To address this, 
1.  the timeout for Tekton jobs has been extended from 2 hours to 3 hours, and 
2. cronjob timings have been adjusted to avoid clashes with other jobs.
review them: …
=> Cronjob timings and timeout modified for ppc64le jobs

tekton/cd/pipeline/overlays/dogfooding/feature-flags.yaml
OCI bundles are still used in dogfooding through the old bundles syntax. The syntax is translated automatically to the remote resolution syntax, but it still requires the oci bundles flag to be enabled first.
/kind misc
review them:
=> Enable OCI bundles use in dogfooding

tekton/ci/jobs/tekton-golang-coverage.yaml, tekton/ci/kustomization.yaml, tekton/ci/stepactions/gcs-upload.yaml, tekton/ci/stepactions/git-batch-merge.yaml, tekton/ci/stepactions/kustomization.yaml
StepActions were released in Tekton Pipelines v0.54.0. This PR uses step actions in our dogfooding cluster. Specifically, it uses stepactions to convert three sequential tasks into a single task with three steps.
Once we have a step action catalog, we can remove the step actions and reference them via remote resolvers.
review them:
/kind misc
=> Dogfood StepActions via go-coverage CI pipeline

tekton/images/test-runner/Dockerfile
Update a bunch of tools in `test-runner` image.
- ko to 0.15.3
- golangci-lint to 1.56.2
- kustomize to 5.3.0
- yq to 4.42.1
Each update is in its own commit to facilitate if we need to revert any bump.
/kind misc
review them:
=> images/test-runner: update a bunch of tools

tekton/ci/jobs/tekton-golang-coverage.yaml
This PR adds the missing workspace bindings for the clone-coverage-upload Task.
It fixes broken test: `pull-tekton-pipeline-go-coverage-df` 🤞 
review them:
=> Fix: Missing workspace bindings for Tasks

tekton/ci/stepactions/git-batch-merge.yaml
The results declared in stepaction was being written to `results.<name>.path` instead of `step.results.<name>.path`. As a result, variable replacement was not being performed. This PR fixes that 🤞.
review them:
=> Fix: StepResults usage typo

prow/config.yaml
This will move CLI e2e job to kind to make
it fast instead of spinning a gcp cluster
on every run
/kind misc
review them:
=> Move CLI e2e job to kind

prow/config.yaml
CLI is upgrading it's golang version to 1.21 and for the same we need to update our test-infra image to use the same golang version ie 1.21
/kind misc
review them:
=> Use test-runner image with golang 1.21

tekton/images/test-runner/Dockerfile
With latest digest of ubuntu, we get the following error
```
ulimit: error setting limit (Invalid argument)
```
refer link:
forums.docker.com/t/etc-init-d-docker-62-ulimit-error-setting-limit-invalid-argument-problem/139424
reverting back to stable digest
/kind bug
review them:
=> Use previous digest of ubuntu 23.04

tekton/images/test-runner/Dockerfile
Also replaces kubetest checkout / go install image with cgr.dev/chainguard/go, since I don't think there's a strong reason why this needs to be tied to the go version, and not using the arg makes this dependabot bumpable.
/kind misc
review them:
=> testrunner: Bump go to 1.22

tekton/resources/cd/catalog-template.yaml
This PR updates the pipeline that is used to publish Tasks to Tekton Bundle hosted at gcr.io/tekton-releases/catalog/upstream.
This PR makes use of the newly added StepAction `tekton-catalog-publush` to publish `Tasks` to `gcr.io/tekton-releases/catalog/upstream/tasks/` and `StepActions` to
`gcr.io/tekton-releases/catalog/upstream/stepactions`.
review them:
/kind misc
=> Publish StepActions to Tekton Bundles

tekton/resources/cd/catalog-template.yaml
This PR fixes a typo that was made in the original PR https://github.com/tektoncd/plumbing/pull/1879.
review them:
/kind bug
=> Fix: typo in workspace reference

tekton/images/test-runner/runner.sh
Resolves issue seen in Dashboard integration tests using latest test-runner image. Would also affect any other docker-in-docker jobs using the latest image.
```
Docker in Docker enabled, initializing...
================================================================================
/etc/init.d/docker: 62: ulimit: error setting limit (Invalid argument)
Waiting for docker to be ready, sleeping for 1 seconds.
Waiting for docker to be ready, sleeping for 2 seconds.
Waiting for docker to be ready, sleeping for [3](https://prow.tekton.dev/spyglass/lens/buildlog/iframe?req=%7B%22artifacts%22%3A%5B%22build-log.txt%22%5D%2C%22index%22%3A1%2C%22src%22%3A%22gs%2Ftekton-prow%2Fpr-logs%2Fpull%2Ftektoncd_dashboard%2F3361%2Fpull-tekton-dashboard-integration-tests%2F1772406843407077376%22%7D&topURL=https …
```
=> Fix ulimit issue introduced with Docker 25 in the test-runner image

tekton/images/ko-gcloud/Dockerfile
For some reason, a previous update removed the `GO_VERSION` arg *and*
the `AS build` (alias), making the build failing.
This also bumps `ko` to 0.15.2.
/kind misc
review them:
=> Fix ko-gcloud image build

prow/config.yaml
This will bump tektoncd/cli integration test CI to have go 1.22
/kind misc
review them:
=> Bum cli e2e job to go 1.22

prow/config.yaml
This will bump tektoncd/hub build, unit and integration test CI image to use go 1.22
/kind misc
review them:
=> Bump Hub build, test and integration CI image to go 1.22

tekton/resources/cd/peribolos-template.yaml
When peribolos is run via cron, it uses a different template, so we must update the secret there too.
review them:
/kind misc
=> Fix peribolos secret in the tekton-cd el

go.mod, tekton/images/test-runner/Dockerfile
This should fixes issues we are getting with `go.mod` files containing
the `toolchain` directive.
See https://github.com/google/go-licenses/issues/128.
/kind misc
review them:
=> Enforce go-licenses v1.0.0

tekton/resources/nightly-tests/bastion-p/test_tekton_component.yaml, tekton/resources/nightly-tests/bastion-z/test_tekton_component.yaml
Stepactions/affinity Testscases are failing in s390x/ppc64le CI environment. Need to enabling the feature flags of pipelines before running testcases. this PR will fix this issues. 
/kind misc
Supported kinds are: bug, cleanup, design, documentation, feature, flake, misc, question, tep
-->
review them:
=> Enable feature flags for running tests on s390x/ppc64le platform

tekton/ci/jobs/tekton-image-build.yaml
When a dockerfile is removed, the build CI job fails today as it see the file in the list of modified ones, but cannot locate it to run the test.
This still logs the missing file condition, but do not fail, so that we may pass CI on PRs that delete a dockerfile, like:
- https://github.com/tektoncd/plumbing/pull/2065
- https://github.com/tektoncd/plumbing/pull/2064
/kind bug
review them:
=> Do not fail on missing dockerfile

tekton/resources/nightly-tests/pipeline-deploy-test-ppc64le-template.yaml
This PR adds the previously missing example-test in the tekton-pipeline CI job for ppc64le
Added the previously missing example-test-pipeline for the tekton-pipeline CI job.
Additionally have hard coded the value for container registry with an insecure local registry to fix pipelines CI failure due to push permission error as mentioned in this PR #1399 
review them:
=> Add example testsuite for tekton-pipeline CI job for ppc64le

tekton/cronjobs/bases/release/trigger-with-uuid.yaml, tekton/cronjobs/dogfooding/releases/pipeline-nightly/cronjob.yaml, tekton/resources/nightly-release/base/template.yaml, tekton/resources/nightly-release/bindings.yaml, tekton/resources/nightly-release/overlays/pipeline/template.yaml
After the following changes on pipeline side:
- Regions configurable: Make image registry regions configurable https://github.com/tektoncd/pipeline#8246
- Auth for ghcr.io: Support separate bucket and image reg creds https://github.com/tektoncd/pipeline#8251
- Link images to project: Add OCI source label to images https://github.com/tektoncd/pipeline#8247
This change enables publishing the nightly build
images to ghcr.io.
/kind misc
review them:
=> Move the pipeline nightly build to ghcr

tekton/cronjobs/dogfooding/releases/pipeline-nightly/cronjob.yaml, tekton/resources/nightly-release/overlays/pipeline/template.yaml
For publishing to ghcr.io, remove the package path from the images, and add "pipeline", so that the images will be in the format:
- ghcr.io/tektoncd/pipeline/<image-name>
as opposed to the current:
- ghcr.io/tektoncd/github.com/tektoncd/pipeline/cmd/<image-name>
/kind misc
review them:
=> Remove the package path from pipeline images

tekton/cronjobs/bases/release/trigger-with-uuid.yaml
The cronjobs for nightly builds has been extended with new values that can be used to adopt a different registry. Until migration is complete, set the values for GCP as default to restore the nightly builds.
/kind misc
review them:
=> Resore default values for nightlies

tekton/cronjobs/robocat/kustomization.yaml
Some of the cronjobs folders in robocat to not contain any resource, which fails with the new version of kustomize.
Remove all empty ones.
/kind misc
review them:
=> Remove empty cronjobs folder from robocat

tekton/images/koparse/koparse/koparse.py, tekton/images/koparse/koparse/test_koparse.py, tekton/images/koparse/koparse/test_release_no_preserve_path.yaml, tekton/resources/images/single-arch-template.yaml
Add support for the case of path not preserved in ko. The implementation is done in a backwards compatible way so that if ko is invoked with the same parameters as before it will work in the same way.
/kind feature
review them:
=> Add koparse support for no-preserve-path

tekton/images/koparse/koparse/koparse.py
See for example: https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns/wait-task-release-nightly-qk72w?pipelineTask=publish-images&step=koparse
```
2024-09-19T09:14:57.305509466Z + IMAGES_PATH=[gcr.io/tekton-nightly/github.com/tektoncd/experimental](http://gcr.io/tekton-nightly/github.com/tektoncd/experimental)
2024-09-19T09:14:57.305584903Z + '[' wait-task '!='  ]
2024-09-19T09:14:57.307406787Z + IMAGES_PATH=[gcr.io/tekton-nightly/github.com/tektoncd/experimental/wait-task](http://gcr.io/tekton-nightly/github.com/tektoncd/experimental/wait-task)
2024-09-19T09:14:57.307428664Z + [IMAGES=gcr.io/tekton-nightly/github.com/tektoncd/experimental/wait-task/cmd/controller:v20240919-2ce2f72e49](http://images=gcr.io/tekton-nightly/github.com/tektoncd/experimental/wait-tas …
```
=> Fix param order in koparse backwards_compatible_params

tekton/cronjobs/dogfooding/releases/dashboard-nightly/cronjob.yaml, tekton/resources/nightly-release/overlays/dashboard/template.yaml
Related to https://github.com/tektoncd/plumbing/issues/2157 and https://github.com/tektoncd/dashboard/pull/3634
Publish the Dashboard nightly release image to ghcr.io
Old images were at:
`gcr.io/tekton-nightly/github.com/tektoncd/dashboard/cmd/<image-name>`
With this change they will now be at:
`ghcr.io/tektoncd/dashboard/<image-name>`
/kind misc
review them:
=> Move the Dashboard nightly image to GHCR

tekton/cronjobs/dogfooding/releases/triggers-nightly/cronjob.yaml, tekton/resources/nightly-release/overlays/triggers/template.yaml
Publish Triggers nightly release image to ghcr.io
Old images were at:
`gcr.io/tekton-nightly/github.com/tektoncd/triggers/cmd/<image-name>`
With this change they will now be at:
`ghcr.io/tektoncd/triggers/<image-name>-<path-hash>`
/kind misc
review them:
=> Switch Triggers nightlies to ghcr.io

tekton/cronjobs/dogfooding/releases/triggers-nightly/cronjob.yaml, tekton/resources/nightly-release/overlays/triggers/template.yaml
Follow-up to https://github.com/tektoncd/plumbing/pull/2206
For example, instead of:
`ghcr.io/tektoncd/github.com/tektoncd/triggers/cmd/webhook:v20240926-96723b346e`
ensure image is published at:
`ghcr.io/tektoncd/triggers/webhook-dd1edc925ee1772a9f76e2c1bc291ef6:v20240926-96723b346e`
/kind misc
review them:
=> Fix path of Triggers images published to ghcr.io

.github/dependabot.yml
The `skopeo` and `openssh-server` images were removed in https://github.com/tektoncd/plumbing/pull/2064 and https://github.com/tektoncd/plumbing/pull/2065
Cleanup the dependabot config as these are no longer needed.
/kind misc
review them:
=> Remove dependabot config for images that have been removed from repo

tekton/resources/images/ko-multi-arch-template.yaml
This is for #2224 
/kind feature
review them:
=> feat: Update credentials for Ko Multi-Arch Images

.github/actions/_chatops_retest.yml, .github/actions/_slash.yml
=> Reusable actions to restest GitHub actions

.gitignore, tekton/catalog/tasks/publish.yaml
Creating .docker in the output workspace fails with permission issues, so using /workspace/.docker instead.
Also, the registry user was missing, which is now fixed.
/kind misc
review them:
=> Fix the publish.yaml from the catalog

prow/config.yaml
Chains E2E tests are covered via GitHub actions in a matrix against various versions of Tekton pipeline and K8s.
AFAIK the same tests are executed in the prow-based integration tests, only for fixed pipeline/k8s versions. I propose to remove it since it consumes infra resources and do not provide better coverage.
/kind misc
review them:
FYI @tektoncd/chains-maintainers WDYT?
=> Remove chains prow-based integration tests

tekton/resources/nightly-tests/cli-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/dashboard-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/operator-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/pipeline-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/triggers-deploy-test-ppc64le-template.yaml
Signed-off-by: Valen Mascarenhas [Valen.Mascarenhas@ibm.com](mailto:Valen.Mascarenhas@ibm.com)
This PR removes the retries: 2 field from all relevant Tekton pipeline templates for ppc64le arch,. The change ensures tasks are not retried automatically on failure
1. Removed retries: 2 field from task definitions in Tekton YAML files.
review them:
=> Remove retries field from Tekton pipeline templates for ppc64le

tekton/ci/jobs/tekton-golang-coverage.yaml
When issuing a `/test` command, the job checks if the CI job name matches, if not the coverage task does not need to run.
Today however the pipeline attempts to run the coverage task and fails because of missing results.
/kind bug
review them:
=> Fix coverage job

prow/config.yaml
Today we run the coverage Job both via prow and via Tekton. Remove the prow (pre-submit) one. The postsubmit is only available as a prow job and remains in place.
/kind cleanup
review them:
=> Remove duplicate coverage job

CONTRIBUTING.md, DEVELOPMENT.md, hack/README.md, hack/tekton_in_kind.sh
When starting the kind cluster using docker with the previous configuration the control-plane kubelet stopped with an error not knowing a feature gate for "EphemeralContainers". This feature is stable since kubernetes 1.24 so this configuration was safely removed.
Closes #2486.
Starting the kind cluster using podman failed when joining the worker-nodes. This is fixed by a minor change on the host. A [troubleshooting](https://github.com/tektoncd/plumbing/pull/2487/files#diff-6a33146cb453cc624d7fa8ebedf1e5f7105e5dc8c835badc012760e18853eb7bR93) section was added to the readme with a link to the fix.
Closes #2522.
Once the kind cluster started using podman the registry could not be connected. This issue was resolved by changing the network mode to "bridge" which is also used in the …
=> Fix failing kind cluster start and update docs

tekton/catalog/pipelines/release.yaml
The latest Tekton is picky on capitalisation(as it should)
Fixing the incorrect `subpath` to `subPath`
/kind bug
review them:
=> Fix subpath capitalisation

bots/buildcaptain/README.md, bots/mariobot/cmd/mario/main.go, bots/mariobot/config/mario.yaml, cmd/combine/README.md, scripts/e2e-tests.sh, scripts/library.sh, tekton/ci/cluster-interceptors/add-pr-body/README.md, tekton/ci/cluster-interceptors/build-id/README.md, tekton/ci/interceptors/add-pr-body/README.md, tekton/ci/interceptors/add-team-members/README.md, tekton/ci/jobs/tekton-image-build.yaml, tekton/ci/repos/plumbing/template.yaml, tekton/ci/stepactions/git-batch-merge.yaml, tekton/cronjobs/README.md, tekton/cronjobs/bases/image-build/trigger-image-build.yaml, tekton/cronjobs/dogfooding/catalog/tekton-upstream/README.md, tekton/images/koparse/koparse/koparse.py, tekton/resources/cd/cleanup-template.yaml, tekton/resources/cd/configmap-template.yaml, tekton/resources/cd/folder-template.yaml, tekton/resources/cd/helm-template.yaml, tekton/resources/nightly-release/README.md, tekton/resources/nightly-tests/bastion-p/test_tekton_component.yaml, tekton/resources/nightly-tests/bastion-z/test_tekton_component.yaml, tekton/resources/release/base/github_release.yaml
Cleanup the remaining refences to tekton-* projects under gcr.io from resources and docs.
/kind misc
review them:
=> Remove references to gcr.io/tekton*

tekton/ci/jobs/tekton-yamllint.yaml, tekton/mario-bot/mario-image-build-trigger.yaml, tekton/resources/nightly-tests/catalog-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/catalog-deploy-test-s390x-template.yaml, tekton/resources/nightly-tests/cli-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/cli-deploy-test-s390x-template.yaml, tekton/resources/nightly-tests/dashboard-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/dashboard-deploy-test-s390x-template.yaml, tekton/resources/nightly-tests/operator-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/operator-deploy-test-s390x-template.yaml, tekton/resources/nightly-tests/pipeline-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/pipeline-deploy-test-s390x-template.yaml, tekton/resources/nightly-tests/triggers-deploy-test-ppc64le-template.yaml, tekton/resources/nightly-tests/triggers-deploy-test-s390x-template.yaml
Update usage of the no longer supported `bundle:` field in `taskRef`. Instead replace it with the bundles remote resolver.
/kind misc
`bundle:` refs are no longer supported by the latest Pipelines releases and this is causing the config sync to dogfooding to fail, e.g.:
`2025-05-22T12:31:32.027419345Z Error from server (BadRequest): error when creating "target.yaml": admission webhook "[validation.webhook.pipeline.tekton.dev](http://validation.webhook.pipeline.tekton.dev/)" denied the request: validation failed: must not set the field(s): spec.tasks[0].taskRef.bundle, spec.tasks[3].taskRef.bundle`
review them:
for …
=> Replace obsolete bundle refs with bundle resolver

tekton/cd/dashboard/overlays/dogfooding/extensions.yaml
`displayname` is deprecated as of Dashboard v0.49 and removed in v0.54.  I have updated `dogfooding` to v0.53 which is the latest release that supports both. Once this PR is merged I will deploy the latest release (v0.60).
/kind misc
review them:
=> Replace deprecated Dashboard extension displayname field

prow/oci/config.yaml, prow/oci/ingress.yaml, prow/oci/kustomization.yaml
In Oracle cloud the prow domain in prow.infra.tekton.dev. We don't run CI jobs there, they must be migrated to GHA.
/kind misc
review them:
=> Add OCI configs for prow

tekton/cd/add-pr-body-ci/overlays/oci-ci-cd/kustomization.yaml, tekton/ci/bases/trigger.yaml, tekton/ci/cluster-interceptors/add-pr-body/config/interceptor-deployment.yaml, tekton/ci/infra/ingress.yaml
* The ingress annotation avoids nginx caching large GitHub payload on disk
* The add-pr-body cluster interceptor requires a different syntax to be used in the trigger
* The service target port for the add-pr-body CI is wrong Fixed it, and also patch it in kustomize until we get a new release with the right port
/kind misc
review them:
=> Small fixes to get the CI webhook running
